// Package audiobookshelf — Audiobookshelf module (scaffolded, draft).
//
// Audiobook and podcast server with mobile apps and progress sync.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package audiobookshelf

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "audiobookshelf"
		displayName: "Audiobookshelf"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Audiobook and podcast server with mobile apps and progress sync."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "128m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: audiobookshelf: foundation.#ServiceDefinition & {
		name:     "audiobookshelf"
		type:     "application"
		image:    "ghcr.io/advplyr/audiobookshelf"
		tag:      "2.36.1"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`audiobooks.{{.domain}}`)"
				port:    80
			}
			networks: ["media-internal"]
		}

		accessPolicy: {
			outerAuth:      "self"
			appAuth:        "oidc-sso"
			ownerBootstrap: "Register Audiobookshelf as an OIDC client in Pocket ID and set issuer https://id.{{.domain}} under Settings > Authentication > OpenID Connect."
		}

		upstream: {
			github: repo: "advplyr/audiobookshelf"
			registry: image: "ghcr.io/advplyr/audiobookshelf"
			track: "minor"
		}

		volumes: [
			{
				source: "audiobookshelf-config"
				target: "/config"
				type:   "volume"
				backup: true
			},
			{
				source: "audiobookshelf-metadata"
				target: "/metadata"
				type:   "volume"
				backup: true
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/healthcheck"
				port:   80
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "128m"
			memoryMax: "1g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Audiobookshelf dashboard"
	}
}
