// Package stalwart — Stalwart Mail Server module (scaffolded, draft).
//
// Stalwart Mail Server upstream catalog: the own mail server of the Mail main use case (ADR-0046). The native-v2 mail-server workload owns the governed entrypoint, the custody-held fallback administrator, the published mail ports and the owner-approved domain setup. Cloud nodes only.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package stalwart

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "stalwart"
		displayName: "Stalwart Mail Server"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Stalwart Mail Server upstream catalog: the own mail server of the Mail main use case (ADR-0046). The native-v2 mail-server workload owns the governed entrypoint, the custody-held fallback administrator, the published mail ports and the owner-approved domain setup. Cloud nodes only."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "512m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: stalwart: foundation.#ServiceDefinition & {
		name:     "stalwart"
		type:     "application"
		image:    "docker.io/stalwartlabs/stalwart"
		tag:      "v0.16.23@sha256:be215678796691bc39bdda918ecc50d14a9032a099a1d1950e51950aec7e2592"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`mail-server.{{.domain}}`)"
				port:    8080
			}
			networks: ["mail-server-internal"]
		}

		accessPolicy: {
			outerAuth: "self"
			appAuth:   "self-auth"
		}

		upstream: {
			github: repo: "stalwartlabs/stalwart"
			registry: image: "docker.io/stalwartlabs/stalwart"
			track: "minor"
		}

		volumes: [
			{
				source: "stalwart-data"
				target: "/var/lib/stalwart"
				type:   "volume"
				backup: true
			},
			{
				source: "stalwart-config"
				target: "/etc/stalwart"
				type:   "volume"
				backup: false
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/healthz/ready"
				port:   8080
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "512m"
			memoryMax: "1g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Stalwart Mail Server dashboard"
	}
}
