// Package immich_kiosk — Immich Kiosk module (scaffolded, draft).
//
// Slideshow of Immich albums and people for picture frames, TVs and browsers.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package immich_kiosk

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "immich-kiosk"
		displayName: "Immich Kiosk"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Slideshow of Immich albums and people for picture frames, TVs and browsers."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "64m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: "immich-kiosk": foundation.#ServiceDefinition & {
		name:     "immich-kiosk"
		type:     "application"
		image:    "ghcr.io/damongolding/immich-kiosk"
		tag:      "0.44.1"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`kiosk.{{.domain}}`)"
				port:    3000
			}
			networks: ["immich-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "none"
			reason:    "Read-only slideshow; Kiosk has no user store, so the gateway login protects it."
		}

		upstream: {
			github: repo: "damongolding/immich-kiosk"
			registry: image: "ghcr.io/damongolding/immich-kiosk"
			track: "minor"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/health"
				port:   3000
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "64m"
			memoryMax: "256m"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Immich Kiosk dashboard"
	}
}
