// Package speechkit — kombify SpeechKit module (scaffolded, draft).
//
// kombify SpeechKit server with local speech providers only (whisper.cpp speech-to-text, Kokoro text-to-speech, the node's Ollama for Assist); OpenAI-compatible audio routes for the chat module behind a bearer token on the private AI network.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package speechkit

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "speechkit"
		displayName: "kombify SpeechKit"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "kombify SpeechKit server with local speech providers only (whisper.cpp speech-to-text, Kokoro text-to-speech, the node's Ollama for Assist); OpenAI-compatible audio routes for the chat module behind a bearer token on the private AI network."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "2g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: {
		speechkit: foundation.#ServiceDefinition & {
			name:     "speechkit"
			type:     "application"
			image:    "ghcr.io/kombifyio/speechkit-server"
			tag:      "v0.0.0-placeholder@sha256:0000000000000000000000000000000000000000000000000000000000000000"
			required: false
			status:   "implemented"

			network: networks: ["private-ai-internal"]

			upstream: {
				github: repo: "kombifyio/SpeechKit"
				registry: image: "ghcr.io/kombifyio/speechkit-server"
				track: "minor"
			}

			healthCheck: {
				enabled: true
				http: {
					path:   "/healthz"
					port:   8080
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "kombify SpeechKit application (internal)"
		}
		"speechkit-whisper": foundation.#ServiceDefinition & {
			name:     "speechkit-whisper"
			type:     "application"
			image:    "ghcr.io/ggml-org/whisper.cpp"
			tag:      "main@sha256:fd7ca21c83126b08f610d02a50f68878a66388a4b96e90e2637ced84397013b5"
			required: false
			status:   "implemented"

			network: networks: ["base_net"]

			upstream: {
				github: repo: "ggml-org/whisper.cpp"
				registry: image: "ghcr.io/ggml-org/whisper.cpp"
				track: "minor"
			}

			healthCheck: {
				enabled: true
				http: {
					path:   "/"
					port:   8080
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "1g"
				memoryMax: "3g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "kombify SpeechKit application (internal)"
		}
		"speechkit-tts": foundation.#ServiceDefinition & {
			name:     "speechkit-tts"
			type:     "application"
			image:    "ghcr.io/remsky/kokoro-fastapi-cpu"
			tag:      "v0.9.0@sha256:ee3111d6a2c903ed62f3b4fa19543c6901205ed39fce3c177e895b34a8386b9c"
			required: false
			status:   "implemented"

			network: networks: ["base_net"]

			upstream: {
				github: repo: "remsky/Kokoro-FastAPI"
				registry: image: "ghcr.io/remsky/kokoro-fastapi-cpu"
				track: "minor"
			}

			healthCheck: {
				enabled: true
				http: {
					path:   "/health"
					port:   8880
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "512m"
				memoryMax: "2g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "kombify SpeechKit application (internal)"
		}
	}
}
