// Package emby — Emby module (scaffolded, draft).
//
// Emby media server with native TV and mobile apps. Closed source; some client features need an Emby Premiere licence.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package emby

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "emby"
		displayName: "Emby"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Emby media server with native TV and mobile apps. Closed source; some client features need an Emby Premiere licence."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "1g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: emby: foundation.#ServiceDefinition & {
		name:     "emby"
		type:     "application"
		image:    "docker.io/emby/embyserver"
		tag:      "4.10.0.40"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`media.{{.domain}}`)"
				port:    8096
			}
			networks: ["media-internal"]
		}

		accessPolicy: {
			outerAuth:      "tinyauth-pocketid"
			appAuth:        "self-auth"
			ownerBootstrap: "Emby has no OIDC login: TinyAuth forward-auth (Pocket ID) guards the web app; Emby users stay app-local."
		}

		upstream: {
			github: repo: "MediaBrowser/Emby.Releases"
			registry: image: "emby/embyserver"
			track: "minor"
		}

		volumes: [
			{
				source: "emby-config"
				target: "/config"
				type:   "volume"
				backup: true
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/emby/System/Ping"
				port:   8096
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "512m"
			memoryMax: "4g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Emby dashboard"
	}
}
