import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const root = dirname(here);
const contractPath = join(root, "schemas", "stackkits-webmcp-v2alpha1.schema.json");
const catalogPath = join(root, "schemas", "stackkits-webmcp-catalog-v2alpha1.schema.json");
const schemaTypesPath = join(root, "src", "generated", "schema-types.ts");
const toolSchemasPath = join(root, "src", "generated", "tool-schemas.ts");
const catalogSchemaPath = join(root, "src", "generated", "catalog-schema.ts");

const contract = JSON.parse(await readFile(contractPath, "utf8"));
const catalog = JSON.parse(await readFile(catalogPath, "utf8"));
if (contract.$id !== "https://stackkit.cc/schemas/stackkits-webmcp-v2alpha1.schema.json") {
  throw new Error("unsupported StackKits WebMCP schema identity");
}
if (catalog.$id !== "https://stackkit.cc/schemas/stackkits-webmcp-catalog-v2alpha1.schema.json") {
  throw new Error("unsupported StackKits WebMCP catalog schema identity");
}
if (contract.$defs?.schemaVersion?.const !== "stackkits-webmcp/v2alpha1") {
  throw new Error("StackKits WebMCP schema has an unknown result version");
}

const toolEntries = Object.entries(contract.tools ?? {});
const toolSchemas = {};
const toolDataSchemas = {};
const syntheticDefinitions = { ...contract.$defs };
const syntheticProperties = {};
const typeNames = {
  stackkits_list_catalog: ["ListCatalogInput", "ListCatalogData"],
  stackkits_get_module_profiles: ["GetModuleProfilesInput", "ModuleProfilesData"],
  stackkits_assess_capacity: ["AssessCapacityInput", "CapacityData"],
  stackkits_prepare_handoff: ["PrepareHandoffInput", "HandoffData"],
};

for (const [name, definition] of toolEntries) {
  if (!/^stackkits_[a-z0-9_]+$/.test(name) || name.length >= 30) {
    throw new Error(`invalid WebMCP tool name: ${name}`);
  }
  if (typeof definition.description !== "string" || definition.description.length > 500) {
    throw new Error(`WebMCP tool description exceeds the public budget: ${name}`);
  }
  const names = typeNames[name];
  if (!names || typeof definition.data?.$ref !== "string") throw new Error(`tool contract mapping is incomplete: ${name}`);
  const inputKey = names[0][0].toLowerCase() + names[0].slice(1);
  syntheticDefinitions[inputKey] = definition.input;
  syntheticProperties[inputKey] = { $ref: `#/$defs/${inputKey}` };
  const dataKey = definition.data.$ref.slice("#/$defs/".length);
  syntheticProperties[dataKey] = definition.data;
  const registeredInputSchema = dereferenceLocalSchema(definition.input, contract.$defs);
  for (const description of schemaDescriptions(registeredInputSchema)) {
    if (description.length > 150) {
      throw new Error(`WebMCP parameter description exceeds the public budget: ${name}`);
    }
  }
  toolSchemas[name] = registeredInputSchema;
  toolDataSchemas[name] = definition.data;
}

for (const key of [
  "outcome",
  "capacityStatus",
  "capacityReasonCode",
  "notice",
  "effects",
  "provenance",
  "selection",
  "declaredCapacity",
  "partialDeclaredCapacity",
  "moduleProfileSelection",
  "useCaseSelection",
]) {
  if (!contract.$defs[key]) continue;
  syntheticProperties[key] = { $ref: `#/$defs/${key}` };
}

const compileOptions = {
  bannerComment: "",
  format: true,
  style: { semi: true, singleQuote: false, bracketSpacing: true, printWidth: 120, tabWidth: 2, useTabs: false },
  maxItems: 0,
  ignoreMinAndMaxItems: true,
};
let contractTypes = await compile(toCompilerSchema({
  $schema: contract.$schema,
  title: "StackKits WebMCP schema types",
  type: "object",
  additionalProperties: false,
  required: Object.keys(syntheticProperties),
  properties: syntheticProperties,
  $defs: syntheticDefinitions,
}), "StackKitsWebMcpSchemaTypes", compileOptions);
let catalogTypes = await compile(toCompilerSchema(catalog), "StackKitsWebMcpGeneratedCatalog", compileOptions);
catalogTypes = catalogTypes.replace(/^export type (?:Sha40|Sha64|ContractId|ProfileId) = .*;\r?\n/gm, "");
contractTypes += `\nexport type CapacityAxis = CapacityCheck["axis"];\nexport type NoticeSeverity = Notice["severity"];\nexport type CompactModuleProfile = CompactProfile;\nexport type CompactModuleProfileSet = CompactModuleProfiles;\n`;

const toolNames = toolEntries.map(([name]) => JSON.stringify(name)).join(" | ");
const inputMap = toolEntries.map(([name]) => `  ${name}: ${typeNames[name][0]};`).join("\n");
const dataMap = toolEntries.map(([name]) => `  ${name}: ${typeNames[name][1]};`).join("\n");
const generatedTypes = `// Generated by scripts/generate-types.mjs from the two public JSON Schemas.\n// Do not edit this file directly.\n\nexport const SCHEMA_VERSION = ${JSON.stringify(contract.$defs.schemaVersion.const)} as const;\n\n${contractTypes}\n${catalogTypes}\nexport type WebMcpCatalog = StackKitsWebMCPGeneratedCatalog;\nexport type CatalogKit = Kit;\nexport type TierProfile = Tier;\nexport type ModuleRuntimeRequirement = ModuleRequirement;\nexport type OperationMetadata = Operation;\nexport type ToolName = ${toolNames};\n\nexport interface ToolInputMap {\n${inputMap}\n}\n\nexport interface ToolDataMap {\n${dataMap}\n}\n\nexport interface WebMcpResult<TData = unknown> {\n  schema_version: typeof SCHEMA_VERSION;\n  tool: ToolName;\n  outcome: Outcome;\n  provenance: Provenance;\n  selection?: Selection;\n  data: TData;\n  notices: Notice[];\n  effects: Effects;\n}\n\nexport type ToolResultMap = {\n  [T in ToolName]: WebMcpResult<ToolDataMap[T]>;\n};\n`;
const generatedV2Types = generatedTypes
  .replace("StackKitsWebMCPGeneratedCatalog", "StackKitsWebMCPModuleProfileCatalogV2Alpha1")
  .replace(
    "export type TierProfile = Tier;\nexport type ModuleRuntimeRequirement = ModuleRequirement;",
    "export type CatalogModule = Module;\nexport type ModuleComputeProfile = ComputeProfile;\nexport type ModuleAxisProfile = AxisProfile;\nexport type CatalogUseCase = UseCase;\nexport type CatalogUseCaseAlternative = UseCaseAlternative;",
  );
await writeFile(schemaTypesPath, generatedV2Types, "utf8");

const generatedSchemas = `// Generated by scripts/generate-types.mjs from schemas/stackkits-webmcp.schema.json.\n// Do not edit this file directly.\n\nexport const WEBMCP_SCHEMA_DEFINITIONS = ${JSON.stringify(contract.$defs, null, 2)} as const;\n\nexport const TOOL_INPUT_SCHEMAS = ${JSON.stringify(toolSchemas, null, 2)} as const;\n\nexport const TOOL_DATA_SCHEMAS = ${JSON.stringify(toolDataSchemas, null, 2)} as const;\n`;
await writeFile(
  toolSchemasPath,
  generatedSchemas.replace("schemas/stackkits-webmcp.schema.json", "schemas/stackkits-webmcp-v2alpha1.schema.json"),
  "utf8",
);
await writeFile(
  catalogSchemaPath,
  `// Generated by scripts/generate-types.mjs from schemas/stackkits-webmcp-catalog-v2alpha1.schema.json.\n// Do not edit this file directly.\n\nexport const WEBMCP_CATALOG_SCHEMA = ${JSON.stringify(catalog, null, 2)} as const;\n`,
  "utf8",
);

function toCompilerSchema(value) {
  if (Array.isArray(value)) return value.map(toCompilerSchema);
  if (!value || typeof value !== "object") return value;
  const result = Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, toCompilerSchema(entry)]));
  if (result.type === "array" && Array.isArray(result.prefixItems)) {
    result.items = result.prefixItems;
    result.minItems = result.prefixItems.length;
    result.maxItems = result.prefixItems.length;
    delete result.prefixItems;
  }
  return result;
}

function dereferenceLocalSchema(value, definitions, stack = []) {
  if (Array.isArray(value)) return value.map((entry) => dereferenceLocalSchema(entry, definitions, stack));
  if (!value || typeof value !== "object") return value;
  if (typeof value.$ref === "string") {
    const prefix = "#/$defs/";
    if (!value.$ref.startsWith(prefix)) throw new Error(`unsupported registered schema reference: ${value.$ref}`);
    const name = value.$ref.slice(prefix.length);
    if (stack.includes(name)) throw new Error(`cyclic registered schema reference: ${[...stack, name].join(" -> ")}`);
    const target = definitions[name];
    if (!target) throw new Error(`unknown registered schema reference: ${value.$ref}`);
    const siblings = Object.fromEntries(Object.entries(value).filter(([key]) => key !== "$ref"));
    return {
      ...dereferenceLocalSchema(target, definitions, [...stack, name]),
      ...dereferenceLocalSchema(siblings, definitions, stack),
    };
  }
  return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, dereferenceLocalSchema(entry, definitions, stack)]));
}

function schemaDescriptions(value) {
  if (Array.isArray(value)) return value.flatMap(schemaDescriptions);
  if (!value || typeof value !== "object") return [];
  return [
    ...(typeof value.description === "string" ? [value.description] : []),
    ...Object.values(value).flatMap(schemaDescriptions),
  ];
}
