package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kombifyio/stackkits/internal/composition"
	cueval "github.com/kombifyio/stackkits/internal/cue"
	"github.com/kombifyio/stackkits/pkg/models"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestE2E_IdentityPipeline exercises the full generate pipeline:
// StackSpec → CompositionEngine → TFVars with OIDC → Fragment generation.
func TestE2E_IdentityPipeline(t *testing.T) {
	modulesDir := filepath.Join("..", "..", "..", "modules")
	if _, err := os.Stat(modulesDir); os.IsNotExist(err) {
		t.Skipf("modules directory not found: %s", modulesDir)
	}

	spec := &models.StackSpec{
		Name:       "e2e-homelab",
		StackKit:   "base-kit",
		AdminEmail: "admin@e2e.local",
		Domain:     "homelab.local",
	}
	stackkit := &models.StackKit{
		Metadata: models.StackKitMetadata{Name: "base-kit"},
		Application: map[string]models.ApplicationDef{
			"self-hosting": {},
		},
	}

	// Step 1: Load real CUE contracts
	reader := cueval.NewModuleReader()
	contracts, err := reader.ReadAllModules(modulesDir)
	require.NoError(t, err, "failed to load module contracts")
	require.NotEmpty(t, contracts)

	// Step 2: Run composition engine
	engine := composition.NewCompositionEngine(contracts, stackkit, spec)
	cr, err := engine.Resolve()
	require.NoError(t, err, "composition engine resolve failed")
	require.NotEmpty(t, cr.EnabledModules, "no modules enabled")

	t.Run("identity_config_resolved", func(t *testing.T) {
		require.NotNil(t, cr.Identity, "identity config should be resolved")

		ic := cr.Identity
		assert.True(t, ic.TinyAuthEnabled, "TinyAuth should be enabled")
		assert.True(t, ic.PocketIDEnabled, "PocketID should be enabled for the default passkey identity provider")
		assert.NotEmpty(t, ic.AdminEmail, "admin email should be set")
		assert.NotEmpty(t, ic.OIDCClientID, "OIDC client ID should be generated")
		assert.Empty(t, ic.OIDCClientSecret, "default TinyAuth→PocketID uses a public PKCE client instead of a shared secret")
		// PocketIDEncryptionKey is provisioned file-based by the CLI
		// (cmd/stackkit/commands/generate.go via EnsureEncryptionKey),
		// not by the composition engine.
		assert.Equal(t, "https://id.homelab.local", ic.OIDCIssuerURL)
		assert.Equal(t, "https://id.homelab.local", ic.PocketIDAppURL)
		assert.True(t, ic.TinyAuthOAuthEnabled, "TinyAuth OAuth should be enabled when PocketID is active")

		if ic.TinyAuthEnabled {
			assert.NotEmpty(t, ic.TinyAuthSessionSecret, "TinyAuth session secret should be generated")
		}
	})

	t.Run("tfvars_with_identity_overlay", func(t *testing.T) {
		data, err := generateTfvarsJSON(spec, cr)
		require.NoError(t, err, "generateTfvarsJSON failed")

		var tfvars map[string]any
		require.NoError(t, json.Unmarshal(data, &tfvars), "tfvars is not valid JSON")

		// Core fields
		assert.NotEmpty(t, tfvars["domain"], "domain should be set")
		assert.Equal(t, "admin@e2e.local", tfvars["admin_email"])

		// Admin password should be generated by composition engine
		assert.NotEmpty(t, tfvars["admin_password_plaintext"], "admin_password_plaintext should be in tfvars")
		assert.NotEmpty(t, tfvars["tinyauth_users"], "tinyauth_users should be in tfvars")

		// Identity overlay (when PocketID enabled). pocketid_encryption_key is
		// injected by generate.go (file-based via EnsureEncryptionKey), not by
		// generateTfvarsJSON, so it is intentionally absent from this overlay.
		assert.NotEmpty(t, tfvars["pocketid_app_url"], "pocketid_app_url should be in tfvars")
		assert.NotEmpty(t, tfvars["tinyauth_oidc_client_id"], "tinyauth_oidc_client_id should be in tfvars")
		assert.Equal(t, "", tfvars["tinyauth_oidc_client_secret"], "public PKCE client does not require a shared secret")
		assert.NotEmpty(t, tfvars["tinyauth_oidc_issuer"], "tinyauth_oidc_issuer should be in tfvars")
		assert.Equal(t, true, tfvars["tinyauth_oidc_enabled"])
	})

	t.Run("fragment_generation_from_composition", func(t *testing.T) {
		// buildModuleGraphFromComposition does NOT mutate contracts (uses internal clone)
		graph, err := buildModuleGraphFromComposition(contracts, cr)
		require.NoError(t, err, "buildModuleGraphFromComposition failed")
		require.NotEmpty(t, graph.Ordered, "module graph should have ordered modules")

		// Verify graph contains all enabled modules from composition
		for _, modName := range cr.EnabledModules {
			_, exists := graph.Modules[modName]
			assert.True(t, exists, "enabled module %q should be in graph", modName)
		}

		// Generate to temp dir
		dir := t.TempDir()
		gen := cueval.NewGenerator("homelab.local")
		err = gen.GenerateAll(graph, dir)
		require.NoError(t, err, "GenerateAll failed")

		// Verify core TF files
		for _, name := range []string{"providers.tf", "networks.tf", "variables.tf", "terraform.tfvars.json"} {
			path := filepath.Join(dir, name)
			info, err := os.Stat(path)
			require.NoError(t, err, "expected file %s not generated", name)
			assert.Greater(t, info.Size(), int64(0), "%s should not be empty", name)
		}

		// Verify per-module .tf files are emitted at the OpenTofu root. OpenTofu
		// does not load .tf files from arbitrary nested directories.
		for _, modName := range graph.Ordered {
			tfPath := filepath.Join(dir, modName+".tf")
			_, err := os.Stat(tfPath)
			assert.NoError(t, err, "module %q missing generated .tf file", modName)
		}

		// Verify generated tfvars.json has enable flags matching composition
		tfvarsData, err := os.ReadFile(filepath.Join(dir, "terraform.tfvars.json"))
		require.NoError(t, err)
		var genTfvars map[string]any
		require.NoError(t, json.Unmarshal(tfvarsData, &genTfvars))

		for _, modName := range graph.Ordered {
			// Generator writes enable_<module> = true for each enabled module
			// moduleVarName replaces hyphens with underscores
			varName := strings.ReplaceAll(modName, "-", "_")
			key := "enable_" + varName
			val, exists := genTfvars[key]
			if exists {
				assert.Equal(t, true, val, "enable flag for %q should be true", modName)
			}
		}
	})
}

func TestE2E_ObservabilityProfileCoverage(t *testing.T) {
	modulesDir := filepath.Join("..", "..", "..", "modules")
	if _, err := os.Stat(modulesDir); os.IsNotExist(err) {
		t.Skipf("modules directory not found: %s", modulesDir)
	}

	reader := cueval.NewModuleReader()
	contracts, err := reader.ReadAllModules(modulesDir)
	require.NoError(t, err, "failed to load module contracts")
	require.NotEmpty(t, contracts)

	tests := []struct {
		name                 string
		capabilityCtx        models.NodeContext
		cpuCores             int
		memoryGB             int
		spec                 *models.StackSpec
		wantSecureCookie     bool
		wantMonitoringCore   bool
		wantRemoteWrite      string
	}{
		{
			name:          "pi-4b",
			capabilityCtx: models.ContextPi,
			cpuCores:      4,
			memoryGB:      4,
			spec: &models.StackSpec{
				Name:     "pi-4b-smoke",
				StackKit: "base-kit",
				Context:  string(models.ContextPi),
				Domain:   models.DomainHomeLab,
				Compute:  models.ComputeSpec{Tier: models.ComputeTierLow},
				Nodes: []models.NodeSpec{{
					Name:      "pi-4b",
					Role:      "standalone",
					IP:        "192.168.1.44",
					CPUCores:  4,
					RAMGB:     4,
					StorageGB: 64,
				}},
			},
			wantSecureCookie: false,
		},
		{
			name:          "pi-5",
			capabilityCtx: models.ContextPi,
			cpuCores:      4,
			memoryGB:      8,
			spec: &models.StackSpec{
				Name:     "pi-5-smoke",
				StackKit: "base-kit",
				Context:  string(models.ContextPi),
				Domain:   models.DomainHomeLab,
				Compute:  models.ComputeSpec{Tier: models.ComputeTierStandard},
				Nodes: []models.NodeSpec{{
					Name:      "pi-5",
					Role:      "standalone",
					IP:        "192.168.1.55",
					CPUCores:  4,
					RAMGB:     8,
					StorageGB: 128,
				}},
			},
			wantSecureCookie: false,
		},
		{
			name:          "low-memory-vps",
			capabilityCtx: models.ContextCloud,
			cpuCores:      2,
			memoryGB:      2,
			spec: &models.StackSpec{
				Name:       "low-memory-vps",
				StackKit:   "base-kit",
				Context:    string(models.ContextCloud),
				Domain:     "edge.example.com",
				AdminEmail: "ops@example.com",
				Compute:    models.ComputeSpec{Tier: models.ComputeTierLow},
				Nodes: []models.NodeSpec{{
					Name:      "edge-vps",
					Role:      "standalone",
					IP:        "10.0.0.24",
					CPUCores:  2,
					RAMGB:     2,
					StorageGB: 40,
				}},
			},
			wantSecureCookie: true,
		},
		{
			name:          "multi-node-homelab",
			capabilityCtx: models.ContextCloud,
			cpuCores:      4,
			memoryGB:      8,
			spec: &models.StackSpec{
				Name:       "multi-node-homelab",
				StackKit:   "modern-homelab",
				Context:    string(models.ContextCloud),
				Domain:     "cluster.example.com",
				AdminEmail: "ops@example.com",
				Compute:    models.ComputeSpec{Tier: models.ComputeTierStandard},
				Addons:     []string{"monitoring-core"},
				Nodes: []models.NodeSpec{
					{Name: "manager-1", Role: "control-plane", IP: "10.0.0.10", CPUCores: 4, RAMGB: 8, StorageGB: 100},
					{Name: "worker-1", Role: "worker", IP: "10.0.0.11", CPUCores: 4, RAMGB: 8, StorageGB: 100},
					{Name: "worker-2", Role: "worker", IP: "10.0.0.12", CPUCores: 4, RAMGB: 8, StorageGB: 100},
				},
			},
			wantSecureCookie:   true,
			wantMonitoringCore: true,
			wantRemoteWrite:    "http://victoriametrics:8428/api/v1/write",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			setCapabilitiesProfile(t, tt.capabilityCtx, tt.cpuCores, tt.memoryGB)

			stackkit := &models.StackKit{
				Metadata: models.StackKitMetadata{Name: tt.spec.StackKit},
				Application: map[string]models.ApplicationDef{
					"self-hosting": {},
				},
			}

			engine := composition.NewCompositionEngine(contracts, stackkit, tt.spec)
			cr, err := engine.Resolve()
			require.NoError(t, err, "composition engine resolve failed")
			assert.Contains(t, cr.EnabledModules, "monitoring-agent", "OTLP monitoring-agent should remain enabled")
			if tt.wantMonitoringCore {
				assert.Contains(t, cr.EnabledModules, "monitoring-core", "monitoring-core add-on should be enabled")
			} else {
				assert.NotContains(t, cr.EnabledModules, "monitoring-core", "monitoring-core should stay opt-in")
			}

			data, err := generateTfvarsJSON(tt.spec, cr)
			require.NoError(t, err, "generateTfvarsJSON failed")

			var tfvars map[string]any
			require.NoError(t, json.Unmarshal(data, &tfvars), "tfvars is not valid JSON")

			assert.Equal(t, fmt.Sprintf("%t", tt.wantSecureCookie), tfvars["tinyauth_secure_cookie"])
			assert.Equal(t, "standard", tfvars["monitoring_agent_profile"])
			assert.Equal(t, "30s", tfvars["monitoring_agent_collection_interval"])
			assert.Equal(t, "30s", tfvars["monitoring_agent_batch_timeout"])
			assert.Equal(t, "256MiB", tfvars["monitoring_agent_gomemlimit"])
			assert.Equal(t, "200", tfvars["monitoring_agent_memory_limit_mib"])
			assert.Equal(t, "50", tfvars["monitoring_agent_memory_spike_limit_mib"])
			assert.Equal(t, "unix:///var/run/docker.sock", tfvars["monitoring_agent_docker_endpoint"])

			endpoint, ok := tfvars["monitoring_agent_otlp_endpoint"].(string)
			require.True(t, ok, "monitoring_agent_otlp_endpoint should be a string")
			assert.NotEmpty(t, endpoint)
			assert.True(t, strings.HasSuffix(endpoint, ":4317"), "agent endpoint should remain an OTLP/gRPC target: %s", endpoint)

			if tt.wantMonitoringCore {
				assert.Equal(t, tt.wantRemoteWrite, tfvars["monitoring_core_gateway_remote_write_endpoint"])
				assert.Equal(t, "256MiB", tfvars["monitoring_core_gateway_gomemlimit"])
			} else {
				_, exists := tfvars["monitoring_core_gateway_remote_write_endpoint"]
				assert.False(t, exists, "monitoring-core tfvars should be absent when addon is disabled")
			}
		})
	}
}

func setCapabilitiesProfile(t *testing.T, ctx models.NodeContext, cpuCores, memoryGB int) {
	t.Helper()

	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("USERPROFILE", home)

	capsDir := filepath.Join(home, ".stackkits")
	require.NoError(t, os.MkdirAll(capsDir, 0750))

	caps := models.DockerCapabilities{
		ResolvedContext:  ctx,
		BridgeNetworking: true,
		StorageDriver:    models.StorageOverlay2,
		CPUCores:         cpuCores,
		MemoryGB:         float64(memoryGB),
		PrivateIP:        "192.168.1.50",
	}

	data, err := json.Marshal(caps)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(capsDir, "capabilities.json"), data, 0600))
}
