package commands

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kombifyio/stackkits/internal/composition"
	cueval "github.com/kombifyio/stackkits/internal/cue"
	"github.com/kombifyio/stackkits/pkg/models"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestE2E_IdentityPipeline exercises the full generate pipeline:
// StackSpec → CompositionEngine → TFVars with OIDC → Fragment generation.
func TestE2E_IdentityPipeline(t *testing.T) {
	modulesDir := filepath.Join("..", "..", "..", "modules")
	if _, err := os.Stat(modulesDir); os.IsNotExist(err) {
		t.Skipf("modules directory not found: %s", modulesDir)
	}

	spec := &models.StackSpec{
		Name:       "e2e-homelab",
		StackKit:   "base-kit",
		AdminEmail: "admin@e2e.local",
		Domain:     "homelab.local",
	}
	stackkit := &models.StackKit{
		Metadata: models.StackKitMetadata{Name: "base-kit"},
		Application: map[string]models.ApplicationDef{
			"self-hosting": {},
		},
	}

	// Step 1: Load real CUE contracts
	reader := cueval.NewModuleReader()
	contracts, err := reader.ReadAllModules(modulesDir)
	require.NoError(t, err, "failed to load module contracts")
	require.NotEmpty(t, contracts)

	// Step 2: Run composition engine
	engine := composition.NewCompositionEngine(contracts, stackkit, spec)
	cr, err := engine.Resolve()
	require.NoError(t, err, "composition engine resolve failed")
	require.NotEmpty(t, cr.EnabledModules, "no modules enabled")

	t.Run("identity_config_resolved", func(t *testing.T) {
		require.NotNil(t, cr.Identity, "identity config should be resolved")

		ic := cr.Identity
		assert.True(t, ic.TinyAuthEnabled, "TinyAuth should be enabled")
		assert.True(t, ic.PocketIDEnabled, "PocketID should be enabled for the default passkey identity provider")
		assert.NotEmpty(t, ic.AdminEmail, "admin email should be set")
		assert.NotEmpty(t, ic.OIDCClientID, "OIDC client ID should be generated")
		assert.Empty(t, ic.OIDCClientSecret, "default TinyAuth→PocketID uses a public PKCE client instead of a shared secret")
		// PocketIDEncryptionKey is provisioned file-based by the CLI
		// (cmd/stackkit/commands/generate.go via EnsureEncryptionKey),
		// not by the composition engine.
		assert.Equal(t, "https://id.homelab.local", ic.OIDCIssuerURL)
		assert.Equal(t, "https://id.homelab.local", ic.PocketIDAppURL)
		assert.True(t, ic.TinyAuthOAuthEnabled, "TinyAuth OAuth should be enabled when PocketID is active")

		if ic.TinyAuthEnabled {
			assert.NotEmpty(t, ic.TinyAuthSessionSecret, "TinyAuth session secret should be generated")
		}
	})

	t.Run("tfvars_with_identity_overlay", func(t *testing.T) {
		data, err := generateTfvarsJSON(spec, cr)
		require.NoError(t, err, "generateTfvarsJSON failed")

		var tfvars map[string]any
		require.NoError(t, json.Unmarshal(data, &tfvars), "tfvars is not valid JSON")

		// Core fields
		assert.NotEmpty(t, tfvars["domain"], "domain should be set")
		assert.Equal(t, "admin@e2e.local", tfvars["admin_email"])

		// Admin password should be generated by composition engine
		assert.NotEmpty(t, tfvars["admin_password_plaintext"], "admin_password_plaintext should be in tfvars")
		assert.NotEmpty(t, tfvars["tinyauth_users"], "tinyauth_users should be in tfvars")

		// Identity overlay (when PocketID enabled). pocketid_encryption_key is
		// injected by generate.go (file-based via EnsureEncryptionKey), not by
		// generateTfvarsJSON, so it is intentionally absent from this overlay.
		assert.NotEmpty(t, tfvars["pocketid_app_url"], "pocketid_app_url should be in tfvars")
		assert.NotEmpty(t, tfvars["tinyauth_oidc_client_id"], "tinyauth_oidc_client_id should be in tfvars")
		assert.Equal(t, "", tfvars["tinyauth_oidc_client_secret"], "public PKCE client does not require a shared secret")
		assert.NotEmpty(t, tfvars["tinyauth_oidc_issuer"], "tinyauth_oidc_issuer should be in tfvars")
		assert.Equal(t, true, tfvars["tinyauth_oidc_enabled"])
	})

	t.Run("fragment_generation_from_composition", func(t *testing.T) {
		// buildModuleGraphFromComposition does NOT mutate contracts (uses internal clone)
		graph, err := buildModuleGraphFromComposition(contracts, cr)
		require.NoError(t, err, "buildModuleGraphFromComposition failed")
		require.NotEmpty(t, graph.Ordered, "module graph should have ordered modules")

		// Verify graph contains all enabled modules from composition
		for _, modName := range cr.EnabledModules {
			_, exists := graph.Modules[modName]
			assert.True(t, exists, "enabled module %q should be in graph", modName)
		}

		// Generate to temp dir
		dir := t.TempDir()
		gen := cueval.NewGenerator("homelab.local")
		err = gen.GenerateAll(graph, dir)
		require.NoError(t, err, "GenerateAll failed")

		// Verify core TF files
		for _, name := range []string{"providers.tf", "networks.tf", "variables.tf", "terraform.tfvars.json"} {
			path := filepath.Join(dir, name)
			info, err := os.Stat(path)
			require.NoError(t, err, "expected file %s not generated", name)
			assert.Greater(t, info.Size(), int64(0), "%s should not be empty", name)
		}

		// Verify per-module .tf files are emitted at the OpenTofu root. OpenTofu
		// does not load .tf files from arbitrary nested directories.
		for _, modName := range graph.Ordered {
			tfPath := filepath.Join(dir, modName+".tf")
			_, err := os.Stat(tfPath)
			assert.NoError(t, err, "module %q missing generated .tf file", modName)
		}

		// Verify generated tfvars.json has enable flags matching composition
		tfvarsData, err := os.ReadFile(filepath.Join(dir, "terraform.tfvars.json"))
		require.NoError(t, err)
		var genTfvars map[string]any
		require.NoError(t, json.Unmarshal(tfvarsData, &genTfvars))

		for _, modName := range graph.Ordered {
			// Generator writes enable_<module> = true for each enabled module
			// moduleVarName replaces hyphens with underscores
			varName := strings.ReplaceAll(modName, "-", "_")
			key := "enable_" + varName
			val, exists := genTfvars[key]
			if exists {
				assert.Equal(t, true, val, "enable flag for %q should be true", modName)
			}
		}
	})
}
