package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"text/template"

	"github.com/kombifyio/stackkits/internal/registry"
	"github.com/spf13/cobra"
)

var (
	registryEmitMintlifySrcInput string
	registryEmitMintlifyOutDir   string
)

var registryEmitMintlifyCmd = &cobra.Command{
	Use:   "emit-mintlify",
	Short: "Render Mintlify MDX tool documentation from the registry snapshot",
	Long: `Render guides/stackkits/services/<slug>.mdx for every tool in the snapshot
that carries published content (tool.content != null). Tools without content
are skipped — their handwritten MDX is left untouched.

Reads the snapshot JSON (default: internal/registry/data/registry_snapshot.json)
and renders deterministically. The header carries the content_hash so drift is
detectable. CI regenerates from the committed snapshot and diffs.`,
	RunE: runRegistryEmitMintlify,
}

func init() {
	registryEmitMintlifyCmd.Flags().StringVar(&registryEmitMintlifySrcInput, "input", defaultSnapshotPath(), "Snapshot JSON to render from")
	registryEmitMintlifyCmd.Flags().StringVar(&registryEmitMintlifyOutDir, "output-dir", filepath.Join("guides", "stackkits", "services"), "Output directory for generated MDX files")
	registryCmd.AddCommand(registryEmitMintlifyCmd)
}

func runRegistryEmitMintlify(_ *cobra.Command, _ []string) error {
	raw, err := os.ReadFile(registryEmitMintlifySrcInput) // #nosec G304
	if err != nil {
		return fmt.Errorf("read snapshot %s: %w", registryEmitMintlifySrcInput, err)
	}
	var snap registry.Snapshot
	if err := json.Unmarshal(raw, &snap); err != nil {
		return fmt.Errorf("decode snapshot %s: %w", registryEmitMintlifySrcInput, err)
	}
	if snap.SchemaVersion != registry.SnapshotVersion {
		return fmt.Errorf("snapshot schema version mismatch: got %d, expected %d",
			snap.SchemaVersion, registry.SnapshotVersion)
	}

	if err := os.MkdirAll(registryEmitMintlifyOutDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", registryEmitMintlifyOutDir, err)
	}

	sorted := append([]registry.Tool(nil), snap.Tools...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Slug < sorted[j].Slug })

	generated := 0
	for _, tool := range sorted {
		if tool.Content == nil {
			continue
		}
		mdx, err := renderToolDocMDX(tool, snap)
		if err != nil {
			return fmt.Errorf("render %s: %w", tool.Slug, err)
		}
		outPath := filepath.Join(registryEmitMintlifyOutDir, tool.Slug+".mdx")
		if err := os.WriteFile(outPath, []byte(mdx), 0o644); err != nil { // #nosec G306
			return fmt.Errorf("write %s: %w", outPath, err)
		}
		generated++
	}

	printSuccess("emit-mintlify: wrote %d tool docs to %s", generated, registryEmitMintlifyOutDir)
	printInfo("snapshot_source=%s content_hash=%s tools_total=%d tools_with_content=%d",
		snap.Source, orNone(snap.ContentHash), len(snap.Tools), generated)
	return nil
}

var toolDocTemplate = template.Must(template.New("tool-doc").Funcs(template.FuncMap{
	"yamlIndent": func(s string) string { return strings.ReplaceAll(s, "\n", "\n") },
}).Parse(`---
title: "{{ .Tool.DisplayName }}"
description: "{{ .Description }}"
sidebarTitle: "{{ .Tool.DisplayName }}"
icon: {{ .Icon }}
generated: true
generated_by: "stackkit registry emit-mintlify"
content_hash: "{{ .Tool.Content.ContentHash }}"
source_hash: "{{ .SnapshotHash }}"
---

{/* Code generated by 'stackkit registry emit-mintlify'. DO NOT EDIT. */}

{{ .Sections.Overview }}
{{ if .Sections.VendorInfo }}
**Vendor:** {{ .Sections.VendorInfo }}
{{ end }}{{ if .Tool.DocumentationURL }}
**Documentation:** [{{ .Tool.DisplayName }} Docs]({{ .Tool.DocumentationURL }})
{{ end }}{{ if .Tool.RepoURL }}
**Repository:** [{{ .Tool.RepoURL }}]({{ .Tool.RepoURL }})
{{ end }}
{{ .Tool.DisplayName }} is served at ` + "`" + `{{ .ServiceSlug }}.<domain>` + "`" + `.
{{ if .Sections.EnableSnippet }}
## Enable {{ .Tool.DisplayName }}

` + "```yaml stack-spec.yaml" + `
{{ .Sections.EnableSnippet }}
` + "```" + `
{{ end }}{{ if .HasAlternatives }}
<Note>
  {{ .AlternativesNote }}
</Note>
{{ end }}{{ if .Sections.Steps }}
## Steps

<Steps>{{ range .Sections.Steps }}
  <Step title="{{ .Title }}">
    {{ .Body }}
  </Step>{{ end }}
</Steps>
{{ end }}{{ if .Sections.Verify }}
## Verify

{{ range .Sections.Verify }}- {{ . }}
{{ end }}{{ end }}{{ if .Sections.UseCases }}
## Use Cases

{{ range .Sections.UseCases }}- {{ . }}
{{ end }}{{ end }}
## Next steps

<CardGroup cols={2}>
  <Card title="Tool alternatives" icon="shuffle" href="/stackkits/reference/tool-alternatives">
    Compare {{ .Tool.DisplayName }} with alternatives.
  </Card>
  <Card title="Node Hub" icon="grid-2" href="/guides/stackkits/node-hub">
    See all service URLs after rollout.
  </Card>
</CardGroup>
{{ if .Sections.Troubleshooting }}
## Troubleshooting

<AccordionGroup>{{ range .Sections.Troubleshooting }}
  <Accordion title="{{ .Title }}">
    {{ .Body }}
  </Accordion>{{ end }}
</AccordionGroup>
{{ end }}`))

type toolDocData struct {
	Tool             registry.Tool
	Sections         registry.ToolContentSections
	SnapshotHash     string
	Description      string
	Icon             string
	ServiceSlug      string
	HasAlternatives  bool
	AlternativesNote string
}

func renderToolDocMDX(tool registry.Tool, snap registry.Snapshot) (string, error) {
	sec := tool.Content.Sections

	description := sec.Overview
	if len(description) > 120 {
		if idx := strings.Index(description[:120], "."); idx > 30 {
			description = description[:idx+1]
		} else {
			description = description[:120] + "..."
		}
	}

	icon := toolIcon(tool.Category)
	alternatives := findAlternatives(tool, snap)

	data := toolDocData{
		Tool:             tool,
		Sections:         sec,
		SnapshotHash:     snap.ContentHash,
		Description:      description,
		Icon:             icon,
		ServiceSlug:      tool.Slug,
		HasAlternatives:  len(alternatives) > 0,
		AlternativesNote: formatAlternativesNote(tool, alternatives),
	}

	var buf strings.Builder
	if err := toolDocTemplate.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func toolIcon(category string) string {
	switch category {
	case "ingress", "reverse-proxy":
		return "globe"
	case "auth":
		return "lock"
	case "dns":
		return "shield"
	case "observability":
		return "chart-line"
	case "dev-platform":
		return "rocket"
	case "media":
		return "film"
	case "storage":
		return "folder"
	case "secrets":
		return "key"
	case "database":
		return "database"
	case "webserver":
		return "server"
	case "automation":
		return "robot"
	default:
		return "cube"
	}
}

func findAlternatives(tool registry.Tool, snap registry.Snapshot) []string {
	for _, sg := range snap.ServiceGroups {
		if sg.DefaultModuleSlug == tool.Slug {
			for _, kit := range snap.StackKits {
				for _, sel := range kit.ServiceSelections {
					if sel.ServiceGroupSlug == sg.Slug && len(sel.AlternativeModuleSlugs) > 0 {
						return sel.AlternativeModuleSlugs
					}
				}
			}
		}
	}
	for _, kit := range snap.StackKits {
		for _, sel := range kit.ServiceSelections {
			if slices.Contains(sel.AlternativeModuleSlugs, tool.Slug) {
				others := []string{sel.SelectedModuleSlug}
				for _, a := range sel.AlternativeModuleSlugs {
					if a != tool.Slug {
						others = append(others, a)
					}
				}
				return others
			}
		}
	}
	return nil
}

func formatAlternativesNote(tool registry.Tool, alternatives []string) string {
	if len(alternatives) == 0 {
		return ""
	}
	links := make([]string, 0, len(alternatives))
	for _, alt := range alternatives {
		links = append(links, fmt.Sprintf("[%s](/guides/stackkits/services/%s)", alt, alt))
	}
	return fmt.Sprintf("%s and %s are interchangeable — pick one. See [tool alternatives](/stackkits/reference/tool-alternatives).",
		tool.DisplayName, strings.Join(links, ", "))
}
