// Package docling — Docling module (scaffolded, draft).
//
// Docling Serve (CPU image with built-in layout, table and OCR models) that converts scanned and complex documents for Open WebUI; no route.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package docling

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "docling"
		displayName: "Docling"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Docling Serve (CPU image with built-in layout, table and OCR models) that converts scanned and complex documents for Open WebUI; no route."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: false
		minMemory:         "1g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: docling: foundation.#ServiceDefinition & {
		name:     "docling"
		type:     "application"
		image:    "quay.io/docling-project/docling-serve-cpu"
		tag:      "v1.35.0@sha256:79e5fcd19ab227ed36323fa5fa31820d14d53efc4f073417ba37be7931c7af0a"
		required: false
		status:   "implemented"

		network: networks: ["private-ai-internal"]

		upstream: {
			github: repo: "docling-project/docling-serve"
			registry: image: "quay.io/docling-project/docling-serve-cpu"
			track: "minor"
		}

		environment: {
			DOCLING_SERVE_ENABLE_UI:     "false"
			DOCLING_SERVE_MAX_SYNC_WAIT: "600"
			HF_HUB_OFFLINE:              "1"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/health"
				port:   5001
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "1g"
			memoryMax: "6g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Docling application (internal)"
	}
}
