// Package euro_office — Euro-Office module (scaffolded, draft).
//
// Euro-Office Document Server (ONLYOFFICE fork) for editing documents, spreadsheets and presentations in the browser; connects to Nextcloud through the eurooffice-nextcloud app.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package euro_office

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "euro-office"
		displayName: "Euro-Office"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Euro-Office Document Server (ONLYOFFICE fork) for editing documents, spreadsheets and presentations in the browser; connects to Nextcloud through the eurooffice-nextcloud app."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "2g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: documentserver: foundation.#ServiceDefinition & {
		name:     "documentserver"
		type:     "application"
		image:    "ghcr.io/euro-office/documentserver"
		tag:      "v9.3.4-hotfix.1"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`office.{{.domain}}`)"
				port:    80
			}
			networks: ["files-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "none"
			reason:    "Document Server has no user login; editors open it from Nextcloud with JWT-signed requests, and TinyAuth (Pocket ID) guards the route."
		}

		upstream: {
			github: repo: "Euro-Office/DocumentServer"
			registry: image: "ghcr.io/euro-office/documentserver"
			track: "minor"
		}

		volumes: [
			{
				source: "euro-office-data"
				target: "/var/www/onlyoffice/Data"
				type:   "volume"
				backup: true
			},
			{
				source: "euro-office-logs"
				target: "/var/log/onlyoffice"
				type:   "volume"
				backup: false
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/healthcheck"
				port:   80
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "2g"
			memoryMax: "4g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Euro-Office dashboard"
	}
}
