// Code generated by internal/architecturev2/cmd/bundlegen; DO NOT EDIT.

package resolvedplan

// pinnedProductDistributionFingerprint is regenerated from the exact product
// CUE sources plus their complete concrete Catalog and Definition projections.
const pinnedProductDistributionFingerprint = "sha256:8ab4c1db56fa34a5c305845d127f6f8172cc82b917970186ebc3919f8fbbb403"
