// Code generated by internal/architecturev2/cmd/bundlegen; DO NOT EDIT.

package resolvedplan

// pinnedProductDistributionFingerprint is regenerated from the exact product
// CUE sources plus their complete concrete Catalog and Definition projections.
const pinnedProductDistributionFingerprint = "sha256:8479d2511196772ec95e215f5a6b917815d83f90129193c6907fd943ffe79183"
