// Code generated by internal/architecturev2/cmd/bundlegen; DO NOT EDIT.

package resolvedplan

// pinnedProductDistributionFingerprint is regenerated from the exact product
// CUE sources plus their complete concrete Catalog and Definition projections.
const pinnedProductDistributionFingerprint = "sha256:017a3590a50d5005465baa5a2731583c2fa3f93a455657c5313971813407aead"
