// Package navidrome — Navidrome module (scaffolded, draft).
//
// Music server and streamer compatible with Subsonic clients.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package navidrome

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "navidrome"
		displayName: "Navidrome"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Music server and streamer compatible with Subsonic clients."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "128m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: navidrome: foundation.#ServiceDefinition & {
		name:     "navidrome"
		type:     "application"
		image:    "docker.io/deluan/navidrome"
		tag:      "0.64.2"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`music.{{.domain}}`)"
				port:    4533
			}
			networks: ["media-internal"]
		}

		accessPolicy: {
			outerAuth:      "tinyauth-pocketid"
			appAuth:        "self-auth"
			ownerBootstrap: "TinyAuth forward-auth (Pocket ID); Navidrome can map the forwarded user through ND_REVERSEPROXYUSERHEADER."
		}

		upstream: {
			github: repo: "navidrome/navidrome"
			registry: image: "deluan/navidrome"
			track: "minor"
		}

		volumes: [
			{
				source: "navidrome-data"
				target: "/data"
				type:   "volume"
				backup: true
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/ping"
				port:   4533
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "128m"
			memoryMax: "512m"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Navidrome dashboard"
	}
}
