// Package comfyui — ComfyUI module (scaffolded, draft).
//
// ComfyUI image and video generation on an NVIDIA GPU with reviewed workflow templates; no ComfyUI-Manager, custom nodes or API nodes; private route behind the kit login.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package comfyui

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "comfyui"
		displayName: "ComfyUI"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "ComfyUI image and video generation on an NVIDIA GPU with reviewed workflow templates; no ComfyUI-Manager, custom nodes or API nodes; private route behind the kit login."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "2g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: comfyui: foundation.#ServiceDefinition & {
		name:     "comfyui"
		type:     "application"
		image:    "ghcr.io/saladtechnologies/comfyui-api"
		tag:      "comfy0.35.0-torch2.13.0-cuda13.0-runtime@sha256:5cc4f79f21e61b9da46e94286c29ef8185520117452027a6f5574cf6125c0ff8"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`ai-image-video.{{.domain}}`)"
				port:    8188
			}
			networks: ["private-ai-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "none"
			reason:    "ComfyUI has no user store or sign-in, so only the gateway login protects the private route."
		}

		upstream: {
			github: repo: "Comfy-Org/ComfyUI"
			registry: image: "ghcr.io/saladtechnologies/comfyui-api"
			track: "minor"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/system_stats"
				port:   8188
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "2g"
			memoryMax: "28g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "ComfyUI dashboard"
	}
}
