// Package ollama — Ollama module (scaffolded, draft).
//
// Ollama for owner-controlled private AI. Models require an explicit owner download.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package ollama

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "ollama"
		displayName: "Ollama"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Ollama for owner-controlled private AI. Models require an explicit owner download."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "1g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: ollama: foundation.#ServiceDefinition & {
		name:     "ollama"
		type:     "application"
		image:    "docker.io/ollama/ollama"
		tag:      "0.34.0@sha256:684d8674b4315fa18f4f0e973a118ec2652ed96f67563277839985175858e0ba"
		required: false
		status:   "implemented"

		network: networks: ["private-ai-internal"]

		upstream: {
			github: repo: "ollama/ollama"
			registry: image: "ollama/ollama"
			track: "minor"
		}

		volumes: [
			{
				source: "ollama-data"
				target: "/root/.ollama"
				type:   "volume"
				backup: false
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/api/tags"
				port:   11434
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "512m"
			memoryMax: "6g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Ollama application (internal)"
	}
}
