// Package esphome — ESPHome module (scaffolded, draft).
//
// Builds and updates firmware for ESP32/ESP8266 devices that report natively to Home Assistant.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package esphome

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "esphome"
		displayName: "ESPHome"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Builds and updates firmware for ESP32/ESP8266 devices that report natively to Home Assistant."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "256m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: esphome: foundation.#ServiceDefinition & {
		name:     "esphome"
		type:     "application"
		image:    "ghcr.io/esphome/esphome"
		tag:      "2026.9.0"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`esphome.{{.domain}}`)"
				port:    6052
			}
			networks: ["smart-home-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "none"
			reason:    "The ESPHome dashboard has no user store, so the gateway login protects it."
		}

		upstream: {
			github: repo: "esphome/esphome"
			registry: image: "ghcr.io/esphome/esphome"
			track: "minor"
		}

		volumes: [
			{
				source: "esphome-config"
				target: "/config"
				type:   "volume"
				backup: true
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/"
				port:   6052
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "256m"
			memoryMax: "2g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "ESPHome dashboard"
	}
}
