// Package gitea — Gitea module (scaffolded, draft).
//
// Gitea image and storage catalog. Executable owner bootstrap is the native-v2 dev workload; this legacy scaffold is not an unattended installer.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package gitea

import "github.com/kombifyio/stackkits/foundation"

_runtimeImages: foundation.ArchitectureV2ModuleImages["stackkits-gitea-runtime"]

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "gitea"
		displayName: "Gitea"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Gitea image and storage catalog. Executable owner bootstrap is the native-v2 dev workload; this legacy scaffold is not an unattended installer."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "256m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: gitea: foundation.#ServiceDefinition & {
		name:     "gitea"
		type:     "application"
		image:    _runtimeImages["gitea"].image
		tag:      _runtimeImages["gitea"].tag
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`dev.{{.domain}}`)"
				port:    3000
			}
			networks: ["gitea-internal"]
		}

		accessPolicy: {
			outerAuth: "self"
			appAuth:   "self-auth"
		}

		upstream: {
			github: repo: "go-gitea/gitea"
			registry: image: "docker.gitea.com/gitea"
			track: "minor"
		}

		volumes: [
			{
				source: "gitea-data"
				target: "/var/lib/gitea"
				type:   "volume"
				backup: true
			},
			{
				source: "gitea-config"
				target: "/etc/gitea"
				type:   "volume"
				backup: true
			},
		]

		environment: {
			GITEA__actions__ENABLED:              "false"
			GITEA__repository__FORCE_PRIVATE:     "true"
			GITEA__security__INSTALL_LOCK:        "true"
			GITEA__server__DISABLE_SSH:           "true"
			GITEA__service__DISABLE_REGISTRATION: "true"
			GITEA__service__REQUIRE_SIGNIN_VIEW:  "true"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/api/healthz"
				port:   3000
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "256m"
			memoryMax: "2g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Gitea dashboard"
	}
}
