package architecturev2renderer

import (
	"context"
)

const (
	basementCoreTerramateUnitID      = "terramate"
	basementCoreTerramateTemplateRef = "builtin://basement/core/terramate/v1"

	basementCoreTerramateOpenTofuOutputRef = "platform/basement-core/main.tf"
	basementCoreTerramateRootOutputRef     = "platform/basement-core/terramate.tm.hcl"
	basementCoreTerramateStackOutputRef    = "platform/basement-core/stack.tm.hcl"
)

const basementCoreTerramateSchema = `stackkit.basement-core-terramate/v1|artifact-revision:2|runtime-listeners:catalog-bound|engine:terramate|underlay:opentofu|outputs:main.tf,stack.tm.hcl,terramate.tm.hcl|execution-instance:node-local|credentials:none|cloud:none`

const basementCoreTerramateRoot = `terramate {
  required_version = "~> 0.17"
}
`

const basementCoreTerramateStack = `stack {
  name        = "StackKit Basement Core"
  description = "Standalone Basement lifecycle stack generated by StackKits"
  id          = "stackkit-basement-core"
  tags        = ["basement", "opentofu", "stackkit"]
}
`

type basementCoreTerramateRenderer struct {
	contract RendererContract
}

// BasementCoreTerramateRendererContract returns the immutable renderer
// identity for the Terramate orchestration layer over the existing OpenTofu
// Basement module.
func BasementCoreTerramateRendererContract() RendererContract {
	return basementCoreContract("terramate", basementCoreTerramateTemplateRef, basementCoreTerramateSchema)
}

func newBasementCoreTerramateRenderer() basementCoreTerramateRenderer {
	return basementCoreTerramateRenderer{contract: BasementCoreTerramateRendererContract()}
}

func (r basementCoreTerramateRenderer) RenderUnit(ctx context.Context, unit RenderUnit) ([]UnitOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if err := validateBasementCoreTerramateUnit(unit, r.contract); err != nil {
		return nil, err
	}
	domain, _ := unit.NetworkDomainBase()
	return []UnitOutput{
		{Ref: basementCoreTerramateOpenTofuOutputRef, Bytes: renderBasementCoreOpenTofu(domain)},
		{Ref: basementCoreTerramateRootOutputRef, Bytes: []byte(basementCoreTerramateRoot)},
		{Ref: basementCoreTerramateStackOutputRef, Bytes: []byte(basementCoreTerramateStack)},
	}, nil
}

func validateBasementCoreTerramateUnit(unit RenderUnit, contract RendererContract) error {
	outputs := []string{
		basementCoreTerramateOpenTofuOutputRef,
		basementCoreTerramateStackOutputRef,
		basementCoreTerramateRootOutputRef,
	}
	if err := validateBasementCoreUnitOutputs(
		unit,
		contract,
		basementCoreTerramateUnitID,
		outputs,
	); err != nil {
		return err
	}
	return nil
}

var _ UnitRenderer = basementCoreTerramateRenderer{}
