package architecturev2renderer

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"strings"
)

const (
	homeAssistantWorkloadModuleID    = "stackkits-home-assistant-runtime"
	homeAssistantWorkloadUnitID      = "home-assistant"
	homeAssistantWorkloadTemplateRef = "builtin://workloads/home-assistant/bundle/v2.json"
	homeAssistantWorkloadVersion     = "2.0.0"
	homeAssistantWorkloadOutputRef   = "workloads/home-assistant/bundle.json"
	homeAssistantImageRef            = "ghcr.io/home-assistant/home-assistant:2026.7.2"
	homeAssistantImageDigest         = "sha256:1476924357b46e80735c13e94232ba5c853cac052e9df4bb28d50fa56348097b"
)

const homeAssistantWorkloadRendererSchema = `stackkit.workload-bundle/v2|HomeAssistantWorkloadBundle|application-adapter|route:authority-bound-module-route-v1|provider-lifecycle:not-owned|components:home-assistant|release:2026.7.2|secret-material:not-included|native-product-mcp:/api/mcp|config-baseline:http-trusted-proxies+homelab-name`

func renderHomeAssistantConfigurationYAML(host string) string {
	var body strings.Builder
	body.WriteString(`# StackKits-owned Home Assistant baseline. Regenerated by stackkit generate.
default_config:

homeassistant:
  name: Homelab
`)
	if host = strings.TrimSpace(host); host != "" {
		body.WriteString("  external_url: https://")
		body.WriteString(host)
		body.WriteByte('\n')
	}
	body.WriteString(`
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 127.0.0.1
    - ::1
    - fd00::/8
`)
	return body.String()
}

type HomeAssistantWorkloadBundleDescriptor struct {
	WorkloadRef string
	ModuleRef   string
	Release     string
	SiteRef     string
	NodeRef     string
	InstanceRef string
	Components  []SelectedPaaSWorkloadComponentDescriptor
	Route       ApplicationDeliveryRouteDescriptor
}

func HomeAssistantWorkloadBundleRendererContract() RendererContract {
	sum := sha256.Sum256([]byte(homeAssistantWorkloadRendererSchema))
	return RendererContract{
		Kind: "native-config", RendererRef: "stackkit",
		TemplateRef: homeAssistantWorkloadTemplateRef, Version: homeAssistantWorkloadVersion,
		ContractHash: "sha256:" + hex.EncodeToString(sum[:]),
	}
}

type homeAssistantWorkloadBundleRenderer struct{ contract RendererContract }

func newHomeAssistantWorkloadBundleRenderer() homeAssistantWorkloadBundleRenderer {
	return homeAssistantWorkloadBundleRenderer{contract: HomeAssistantWorkloadBundleRendererContract()}
}

func (r homeAssistantWorkloadBundleRenderer) RenderUnit(ctx context.Context, unit RenderUnit) ([]UnitOutput, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	bundle, err := validateHomeAssistantWorkloadUnit(unit, r.contract)
	if err != nil {
		return nil, err
	}
	data, err := json.Marshal(bundle)
	if err != nil {
		return nil, wrap(ErrRendererFailure, "renderer.home-assistant-workload", "marshal governed workload bundle", err)
	}
	return []UnitOutput{{Ref: homeAssistantWorkloadOutputRef, Bytes: append(data, '\n')}}, nil
}

func ParseHomeAssistantWorkloadBundle(data []byte) (HomeAssistantWorkloadBundleDescriptor, error) {
	path := "homeAssistantWorkloadBundle"
	var bundle selectedPaaSWorkloadBundle
	if err := decodeStrict(data, &bundle); err != nil {
		return HomeAssistantWorkloadBundleDescriptor{}, wrap(ErrInvalidPlan, path, "decode closed Home Assistant workload bundle", err)
	}
	if bundle.APIVersion != "stackkit.workload-bundle/v2" || bundle.Kind != "HomeAssistantWorkloadBundle" ||
		bundle.Workload.Ref != "smart-home" || bundle.Workload.AlternativeRef != "home-assistant" ||
		bundle.Workload.ModuleRef != homeAssistantWorkloadModuleID || bundle.Workload.Release != "2026.7.2" ||
		bundle.Workload.Delivery != "application-adapter" || bundle.Workload.EntryComponent != homeAssistantWorkloadUnitID ||
		bundle.Ownership.ExecutionAdapter != "selected-application-adapter" ||
		bundle.Ownership.ProviderLifecycle != "not-owned" || bundle.Ownership.Credentials != "opaque-references-only" {
		return HomeAssistantWorkloadBundleDescriptor{}, fail(ErrInvalidPlan, path, "workload or ownership identity differs from the closed Home Assistant 2026.7.2 contract")
	}
	if len(bundle.SecretRefs) != 0 {
		return HomeAssistantWorkloadBundleDescriptor{}, fail(ErrInvalidPlan, path+".secretRefs", "Home Assistant single-container contract accepts no secret material")
	}
	if err := validateHomeAssistantConfigFiles(bundle.ConfigFiles, path+".configFiles"); err != nil {
		return HomeAssistantWorkloadBundleDescriptor{}, err
	}
	components, err := validateHomeAssistantRuntimeComponents(bundle.Components, path+".components")
	if err != nil {
		return HomeAssistantWorkloadBundleDescriptor{}, err
	}
	if err := validateHomeAssistantServiceEndpoint(bundle.Route, path+".route"); err != nil {
		return HomeAssistantWorkloadBundleDescriptor{}, err
	}
	if bundle.DeliveryRoute != nil {
		if err := validateParsedApplicationDeliveryRoute(*bundle.DeliveryRoute, homeAssistantWorkloadModuleID, "smart-home", 8123, path+".deliveryRoute"); err != nil {
			return HomeAssistantWorkloadBundleDescriptor{}, err
		}
	}
	descriptor := HomeAssistantWorkloadBundleDescriptor{
		WorkloadRef: "smart-home", ModuleRef: homeAssistantWorkloadModuleID, Release: "2026.7.2",
		SiteRef: bundle.Target.SiteRef, NodeRef: bundle.Target.NodeRef, InstanceRef: bundle.Target.InstanceRef,
		Components: make([]SelectedPaaSWorkloadComponentDescriptor, len(components)),
	}
	if bundle.DeliveryRoute != nil {
		descriptor.Route = bundle.DeliveryRoute.descriptor()
	}
	for index, component := range components {
		descriptor.Components[index] = SelectedPaaSWorkloadComponentDescriptor{
			ID: component.ID, Lifecycle: component.Lifecycle,
			ImageRef: component.Image.Ref, ImageDigest: component.Image.Digest,
		}
	}
	return descriptor, nil
}

func validateHomeAssistantWorkloadUnit(unit RenderUnit, contract RendererContract) (selectedPaaSWorkloadBundle, error) {
	path := "resolvedPlan.modules." + homeAssistantWorkloadModuleID + ".renderUnits." + homeAssistantWorkloadUnitID
	if unit.ModuleID() != homeAssistantWorkloadModuleID || unit.ID() != homeAssistantWorkloadUnitID {
		return selectedPaaSWorkloadBundle{}, fail(ErrInvalidPlan, path, "renderer accepts only %s/%s", homeAssistantWorkloadModuleID, homeAssistantWorkloadUnitID)
	}
	if unit.Kind() != contract.Kind || unit.RendererRef() != contract.RendererRef ||
		unit.TemplateRef() != contract.TemplateRef || unit.Version() != contract.Version ||
		unit.ContractHash() != contract.ContractHash {
		return selectedPaaSWorkloadBundle{}, fail(ErrOutputChanged, path, "render-unit implementation identity differs from the registered Home Assistant workload contract")
	}
	engine, hasEngine := unit.RuntimeEngine()
	imageRef, hasImage := unit.ContainerImageRef()
	imageDigest, hasDigest := unit.ContainerImageDigest()
	entry, hasEntry := unit.RuntimeEntryComponentRef()
	if unit.RuntimeKind() != "container" || unit.RuntimeDelivery() != "application-adapter" ||
		!hasEngine || engine != "docker" || !hasImage || imageRef != homeAssistantImageRef ||
		!hasDigest || imageDigest != homeAssistantImageDigest || !hasEntry || entry != homeAssistantWorkloadUnitID {
		return selectedPaaSWorkloadBundle{}, fail(ErrInvalidPlan, path+".runtime", "runtime identity must match the exact Home Assistant 2026.7.2 contract")
	}
	siteRef, hasSite := unit.SiteRef()
	nodeRef, hasNode := unit.NodeRef()
	if unit.InstanceScope() != "node-local" || !hasSite || !hasNode ||
		!exactStringList(unit.LogicalSiteRefs(), []string{siteRef}) ||
		!exactStringList(unit.LogicalNodeRefs(), []string{nodeRef}) {
		return selectedPaaSWorkloadBundle{}, fail(ErrInvalidPlan, path+".instances", "Home Assistant requires one exact node-local target")
	}
	_, hasDaemonRef := unit.DaemonRef()
	_, hasDaemonInstance := unit.DaemonInstanceRef()
	_, hasDaemonEngine := unit.DaemonEngine()
	_, hasDaemonSocket := unit.DaemonSocketPath()
	if hasDaemonRef || hasDaemonInstance || hasDaemonEngine || hasDaemonSocket {
		return selectedPaaSWorkloadBundle{}, fail(ErrInvalidPlan, path+".instances", "selected-PaaS workload receives no daemon or socket authority")
	}
	deliveryRoute, err := validateApplicationDeliveryRouteInput(unit, homeAssistantWorkloadModuleID, "smart-home", 8123, path+".inputs")
	if err != nil {
		return selectedPaaSWorkloadBundle{}, err
	}
	if len(unit.SecretInputRefs()) != 0 || !emptyJSONObject(unit.SecretRefsJSON()) ||
		!emptyJSONArray(unit.ProvidedInterfacesJSON()) || !emptyJSONArray(unit.RequiredInterfacesJSON()) ||
		!emptyJSONArray(unit.PrivilegedInterfaceApprovalsJSON()) || !emptyJSONArray(unit.RuntimeNetworkBindingsJSON()) {
		return selectedPaaSWorkloadBundle{}, fail(ErrInvalidPlan, path+".inputs", "Home Assistant bundle accepts no free inputs or host authority")
	}
	var placement struct {
		Scope       string `json:"scope"`
		Cardinality string `json:"cardinality"`
	}
	if err := decodeStrict(unit.PlacementJSON(), &placement); err != nil ||
		placement.Scope != "node-local" || placement.Cardinality != "one-per-node" {
		return selectedPaaSWorkloadBundle{}, fail(ErrInvalidPlan, path+".placement", "requires exact node-local/one-per-node placement")
	}
	if outputs := unit.DeclaredOutputs(); len(outputs) != 1 || outputs[0] != homeAssistantWorkloadOutputRef {
		return selectedPaaSWorkloadBundle{}, fail(ErrInvalidPlan, path+".outputs", "requires exactly output %q", homeAssistantWorkloadOutputRef)
	}
	var components []selectedPaaSRuntimeComponent
	if err := decodeStrict(unit.RuntimeComponentsJSON(), &components); err != nil {
		return selectedPaaSWorkloadBundle{}, wrap(ErrInvalidPlan, path+".runtime.components", "decode closed component graph", err)
	}
	components, err = validateHomeAssistantRuntimeComponents(components, path+".runtime.components")
	if err != nil {
		return selectedPaaSWorkloadBundle{}, err
	}
	var endpoints []selectedPaaSServiceEndpoint
	if err := decodeStrict(unit.ServiceEndpointsJSON(), &endpoints); err != nil || len(endpoints) != 1 {
		return selectedPaaSWorkloadBundle{}, fail(ErrInvalidPlan, path+".serviceEndpoints", "requires one exact smart-home endpoint")
	}
	if err := validateHomeAssistantServiceEndpoint(endpoints[0], path+".serviceEndpoints"); err != nil {
		return selectedPaaSWorkloadBundle{}, err
	}
	host := ""
	if deliveryRoute != nil {
		host = strings.TrimSpace(deliveryRoute.Host)
	}
	bundle := selectedPaaSWorkloadBundle{
		APIVersion: "stackkit.workload-bundle/v2", Kind: "HomeAssistantWorkloadBundle",
		SecretRefs: map[string]string{}, Components: components, Route: endpoints[0], DeliveryRoute: deliveryRoute,
		ConfigFiles: []selectedPaaSConfigFile{{Path: "/config/configuration.yaml", Body: renderHomeAssistantConfigurationYAML(host)}},
	}
	bundle.Workload.Ref, bundle.Workload.AlternativeRef = "smart-home", "home-assistant"
	bundle.Workload.ModuleRef, bundle.Workload.Release = homeAssistantWorkloadModuleID, "2026.7.2"
	bundle.Workload.Delivery, bundle.Workload.EntryComponent = "application-adapter", entry
	bundle.Target.SiteRef, bundle.Target.NodeRef, bundle.Target.InstanceRef = siteRef, nodeRef, unit.InstanceID()
	bundle.Ownership.ExecutionAdapter = "selected-application-adapter"
	bundle.Ownership.ProviderLifecycle = "not-owned"
	bundle.Ownership.Credentials = "opaque-references-only"
	return bundle, nil
}

func validateHomeAssistantRuntimeComponents(components []selectedPaaSRuntimeComponent, path string) ([]selectedPaaSRuntimeComponent, error) {
	if len(components) != 1 || components[0].ID != "home-assistant" || components[0].Lifecycle != "daemon" ||
		components[0].Image.Ref != homeAssistantImageRef || components[0].Image.Digest != homeAssistantImageDigest ||
		components[0].Health.Kind != "http" || components[0].Health.Path != "/" || components[0].Health.Port != 8123 {
		return nil, fail(ErrInvalidPlan, path, "Home Assistant runtime graph differs from the closed 2026.7.2 contract")
	}
	want := map[string]selectedPaaSRuntimeVolume{
		"config": {ID: "config", Target: "/config", Class: "persistent", Backup: true},
	}
	if len(components[0].Volumes) != len(want) {
		return nil, fail(ErrInvalidPlan, path+".volumes", "Home Assistant requires the owner-backed config volume")
	}
	for _, volume := range components[0].Volumes {
		expected, ok := want[volume.ID]
		if !ok || volume != expected {
			return nil, fail(ErrInvalidPlan, path+".volumes", "Home Assistant volume %q differs from the closed contract", volume.ID)
		}
	}
	return components, nil
}

func validateHomeAssistantConfigFiles(files []selectedPaaSConfigFile, path string) error {
	if len(files) != 1 || files[0].Path != "/config/configuration.yaml" {
		return fail(ErrInvalidPlan, path, "Home Assistant requires the closed /config/configuration.yaml baseline")
	}
	body := files[0].Body
	if !strings.Contains(body, "name: Homelab") || !strings.Contains(body, "use_x_forwarded_for: true") || !strings.Contains(body, "trusted_proxies:") {
		return fail(ErrInvalidPlan, path, "Home Assistant baseline must name Homelab and trust reverse-proxy headers")
	}
	if strings.Contains(body, "external_url:") && !strings.Contains(body, "external_url: https://") {
		return fail(ErrInvalidPlan, path, "Home Assistant remote URL must be HTTPS")
	}
	return nil
}

func validateHomeAssistantServiceEndpoint(endpoint selectedPaaSServiceEndpoint, path string) error {
	if endpoint.ServiceRef != "smart-home" || endpoint.UpstreamProtocol != "http" || endpoint.TargetPort != 8123 ||
		endpoint.RequiredPrivilege != "user" || endpoint.OriginSelector != "control-authority-site" ||
		endpoint.HealthRef != "home-assistant-http" || endpoint.Data.BindingRef != "smart-home" ||
		endpoint.Data.Locality != "primary-site" || !exactStringList(endpoint.Data.RequiredClasses, []string{"personal"}) ||
		!exactStringList(endpoint.AllowedIngressProtocols, []string{"http", "https"}) ||
		!sameStringSet(endpoint.AllowedExposures, []string{"local", "remote-private", "public"}) {
		return fail(ErrInvalidPlan, path, "smart-home route authority differs from the governed Home Assistant endpoint")
	}
	return nil
}
