// Code generated by architecture-v2 bundlegen from the compiled CUE authority; DO NOT EDIT.
// Exact selected-PaaS workload images from foundation.ArchitectureV2Catalog.

package architecturev2renderer

const (
	homeAssistantImageRef        = "ghcr.io/home-assistant/home-assistant:2026.7.2"
	homeAssistantImageDigest     = "sha256:1476924357b46e80735c13e94232ba5c853cac052e9df4bb28d50fa56348097b"
	homeAssistantRelease         = "2026.7.2"
	jellyfinImageRef             = "docker.io/jellyfin/jellyfin:10.10.7"
	jellyfinImageDigest          = "sha256:7ae36aab93ef9b6aaff02b37f8bb23df84bb2d7a3f6054ec8fc466072a648ce2"
	jellyfinRelease              = "10.10.7"
	vaultwardenImageRef          = "ghcr.io/dani-garcia/vaultwarden:1.37.2"
	vaultwardenImageDigest       = "sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912"
	vaultwardenRelease           = "1.37.2"
	privateAIImageRef            = "ghcr.io/open-webui/open-webui:v0.11.3"
	privateAIImageDigest         = "sha256:41daa0cf2561a5d4c8d1ff31ee2a98d93ab4d3ac2605cac69366ff6a3374a933"
	privateAIRelease             = "v0.11.3"
	giteaImageRef                = "docker.gitea.com/gitea:1.27.3-rootless"
	giteaImageDigest             = "sha256:1c17ecaead42eb3b5391553d8708103a4beb0e86edf5b9ebc1eb269c318845f2"
	giteaRelease                 = "1.27.3-rootless"
	giteaCommandJSON             = "[\"/bin/sh\",\"-ec\",\"gitea -c \\\"$GITEA_APP_INI\\\" migrate \\u0026\\u0026 users=$(gitea -c \\\"$GITEA_APP_INI\\\" admin user list) \\u0026\\u0026 owner=$(printf '%s\\\\n' \\\"$users\\\" | awk '$1 ~ /^[0-9]+$/ \\u0026\\u0026 $2 == \\\"owner\\\" {print $3 \\\" \\\" $4 \\\" \\\" $5}') \\u0026\\u0026 if [ -n \\\"$owner\\\" ]; then [ \\\"$owner\\\" = \\\"$STACKKITS_OWNER_EMAIL true true\\\" ] || { echo 'Existing Gitea owner does not match local custody' \\u003e\\u00262; exit 1; }; else count=$(printf '%s\\\\n' \\\"$users\\\" | awk '$1 ~ /^[0-9]+$/ {n++} END {print n+0}'); [ \\\"$count\\\" = 0 ] || { echo 'Existing Gitea users require explicit owner reconciliation' \\u003e\\u00262; exit 1; }; gitea -c \\\"$GITEA_APP_INI\\\" admin user create --username owner --email \\\"$STACKKITS_OWNER_EMAIL\\\" --password \\\"$STACKKITS_OWNER_PASSWORD\\\" --admin --must-change-password=false; fi \\u0026\\u0026 unset STACKKITS_OWNER_PASSWORD \\u0026\\u0026 exec gitea -c \\\"$GITEA_APP_INI\\\" web\"]"
	paperlessImageRef            = "ghcr.io/paperless-ngx/paperless-ngx:3.1.3"
	paperlessImageDigest         = "sha256:aa810a36942c63d4ee70d00eda7236cd3d6acfb7eb3f7987fb568ed14df8817a"
	paperlessRelease             = "3.1.3"
	paperlessPostgresImageRef    = "docker.io/library/postgres:18"
	paperlessPostgresImageDigest = "sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280"
	paperlessPostgresRelease     = "18"
	paperlessValkeyImageRef      = "docker.io/valkey/valkey:9-alpine"
	paperlessValkeyImageDigest   = "sha256:a0dbf4c1d5708782907c10e2c72deff317518518b5288a58416981d9db95d30b"
	paperlessValkeyRelease       = "9-alpine"
	paperlessValkeyCommandJSON   = "[\"valkey-server\"]"
	ollamaImageRef               = "docker.io/ollama/ollama:0.34.0"
	ollamaImageDigest            = "sha256:684d8674b4315fa18f4f0e973a118ec2652ed96f67563277839985175858e0ba"
	ollamaRelease                = "0.34.0"
)
