// Package zigbee2mqtt — Zigbee2MQTT module (scaffolded, draft).
//
// Zigbee bridge that exposes Zigbee devices over MQTT to Home Assistant; needs a Zigbee USB adapter and an MQTT broker.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package zigbee2mqtt

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "zigbee2mqtt"
		displayName: "Zigbee2MQTT"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Zigbee bridge that exposes Zigbee devices over MQTT to Home Assistant; needs a Zigbee USB adapter and an MQTT broker."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "128m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: zigbee2mqtt: foundation.#ServiceDefinition & {
		name:     "zigbee2mqtt"
		type:     "application"
		image:    "ghcr.io/koenkk/zigbee2mqtt"
		tag:      "2.14.1"
		required: false
		status:   "implemented"
		needs: ["mosquitto"]

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`zigbee.{{.domain}}`)"
				port:    8080
			}
			networks: ["smart-home-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "none"
			reason:    "The Zigbee2MQTT frontend has no user store, so the gateway login protects it."
		}

		upstream: {
			github: repo: "Koenkk/zigbee2mqtt"
			registry: image: "ghcr.io/koenkk/zigbee2mqtt"
			track: "minor"
		}

		volumes: [
			{
				source: "zigbee2mqtt-data"
				target: "/app/data"
				type:   "volume"
				backup: true
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/"
				port:   8080
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "128m"
			memoryMax: "512m"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Zigbee2MQTT dashboard"
	}
}
