// Package mosquitto — Eclipse Mosquitto module (scaffolded, draft).
//
// MQTT broker for Home Assistant, Zigbee2MQTT and ESPHome devices.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package mosquitto

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "mosquitto"
		displayName: "Eclipse Mosquitto"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "MQTT broker for Home Assistant, Zigbee2MQTT and ESPHome devices."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "32m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: mosquitto: foundation.#ServiceDefinition & {
		name:     "mosquitto"
		type:     "application"
		image:    "docker.io/library/eclipse-mosquitto"
		tag:      "2.0.22"
		required: false
		status:   "implemented"

		network: networks: ["smart-home-internal"]

		upstream: {
			github: repo: "eclipse-mosquitto/mosquitto"
			registry: image: "eclipse-mosquitto"
			track: "minor"
		}

		volumes: [
			{
				source: "mosquitto-data"
				target: "/mosquitto/data"
				type:   "volume"
				backup: true
			},
			{
				source: "mosquitto-config"
				target: "/mosquitto/config"
				type:   "volume"
				backup: true
			},
		]

		healthCheck: {
			enabled:  true
			command:  "mosquitto_sub -t $$SYS/broker/uptime -C 1 -W 3"
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "32m"
			memoryMax: "128m"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Eclipse Mosquitto application (internal)"
	}
}
