// Package immich_public_proxy — Immich Public Proxy module (scaffolded, draft).
//
// Share Immich albums and photos publicly without exposing the Immich instance itself.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package immich_public_proxy

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "immich-public-proxy"
		displayName: "Immich Public Proxy"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Share Immich albums and photos publicly without exposing the Immich instance itself."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "128m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: "immich-public-proxy": foundation.#ServiceDefinition & {
		name:     "immich-public-proxy"
		type:     "application"
		image:    "ghcr.io/alangrainger/immich-public-proxy"
		tag:      "3.4.0"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`share.{{.domain}}`)"
				port:    3000
			}
			networks: ["immich-internal"]
		}

		accessPolicy: {
			outerAuth: "none-explicit"
			appAuth:   "none"
			reason:    "Public by design: serves only the share links the owner creates in Immich, holds no Immich credentials and exposes no Immich login or API."
		}

		upstream: {
			github: repo: "alangrainger/immich-public-proxy"
			registry: image: "ghcr.io/alangrainger/immich-public-proxy"
			track: "minor"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/share/healthcheck"
				port:   3000
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "64m"
			memoryMax: "256m"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
			readOnly: true
			tmpfs: ["/tmp"]
		}

		output: description: "Immich Public Proxy dashboard"
	}
}
