// Package searxng — SearXNG module (scaffolded, draft).
//
// Private meta search that Open WebUI uses for web search; JSON results enabled, limiter off, no route.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package searxng

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "searxng"
		displayName: "SearXNG"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Private meta search that Open WebUI uses for web search; JSON results enabled, limiter off, no route."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: false
		minMemory:         "128m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: searxng: foundation.#ServiceDefinition & {
		name:     "searxng"
		type:     "application"
		image:    "docker.io/searxng/searxng"
		tag:      "2026.9.25-12f8b6515@sha256:5286edb35782454ab8a102c5eff6b54bff745853191b46aeead95f225aa6dfb6"
		required: false
		status:   "implemented"

		network: networks: ["private-ai-internal"]

		upstream: {
			github: repo: "searxng/searxng"
			registry: image: "docker.io/searxng/searxng"
			track: "minor"
		}

		environment: {
			SEARXNG_LIMITER:         "false"
			SEARXNG_PUBLIC_INSTANCE: "false"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/healthz"
				port:   8080
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "128m"
			memoryMax: "512m"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "SearXNG application (internal)"
	}
}
