// Package forgejo — Forgejo module (scaffolded, draft).
//
// Forgejo community Git forge (Gitea fork) with pull requests, issues, packages and Actions.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package forgejo

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "forgejo"
		displayName: "Forgejo"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Forgejo community Git forge (Gitea fork) with pull requests, issues, packages and Actions."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "256m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: forgejo: foundation.#ServiceDefinition & {
		name:     "forgejo"
		type:     "application"
		image:    "codeberg.org/forgejo/forgejo"
		tag:      "16.0.5"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`dev.{{.domain}}`)"
				port:    3000
			}
			networks: ["dev-internal"]
		}

		accessPolicy: {
			outerAuth:      "self"
			appAuth:        "oidc-sso"
			ownerBootstrap: "Register Forgejo as an OIDC client in Pocket ID, then add it with forgejo admin auth add-oauth --provider openidConnect --auto-discover-url https://id.{{.domain}}/.well-known/openid-configuration."
		}

		upstream: {
			github: repo: "forgejo/forgejo"
			registry: image: "codeberg.org/forgejo/forgejo"
			track: "minor"
		}

		volumes: [
			{
				source: "forgejo-data"
				target: "/data"
				type:   "volume"
				backup: true
			},
		]

		environment: {
			FORGEJO__oauth2_client__ENABLE_AUTO_REGISTRATION:   "true"
			FORGEJO__security__INSTALL_LOCK:                    "true"
			FORGEJO__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: "true"
			FORGEJO__service__REQUIRE_SIGNIN_VIEW:              "true"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/api/healthz"
				port:   3000
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "256m"
			memoryMax: "2g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Forgejo dashboard"
	}
}
