// Package immich_power_tools — Immich Power Tools module (scaffolded, draft).
//
// Bulk tools for an Immich library: merge people, find missing locations, manage albums and potential duplicates.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package immich_power_tools

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "immich-power-tools"
		displayName: "Immich Power Tools"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Bulk tools for an Immich library: merge people, find missing locations, manage albums and potential duplicates."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "128m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: "immich-power-tools": foundation.#ServiceDefinition & {
		name:     "immich-power-tools"
		type:     "application"
		image:    "ghcr.io/immich-power-tools/immich-power-tools"
		tag:      "0.24.0"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`photo-tools.{{.domain}}`)"
				port:    3000
			}
			networks: ["immich-internal"]
		}

		accessPolicy: {
			outerAuth:      "tinyauth-pocketid"
			appAuth:        "self-auth"
			ownerBootstrap: "TinyAuth forward-auth (Pocket ID); Power Tools then signs in to Immich with an Immich API key."
		}

		upstream: {
			github: repo: "varun-raj/immich-power-tools"
			registry: image: "ghcr.io/immich-power-tools/immich-power-tools"
			track: "minor"
		}

		volumes: [
			{
				source: "immich-power-tools-data"
				target: "/app/data"
				type:   "volume"
				backup: true
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/"
				port:   3000
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "128m"
			memoryMax: "512m"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Immich Power Tools dashboard"
	}
}
