// Package roundcube — Roundcube Webmail module (scaffolded, draft).
//
// Roundcube Webmail upstream catalog: a webmail client for an existing external IMAP/SMTP mailbox. The native-v2 mail workload owns executable configuration, the custody-derived session key, the owner mailbox endpoints stored by the owner-approved setup action and the device setup documents. No mail server is included.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package roundcube

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "roundcube"
		displayName: "Roundcube Webmail"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Roundcube Webmail upstream catalog: a webmail client for an existing external IMAP/SMTP mailbox. The native-v2 mail workload owns executable configuration, the custody-derived session key, the owner mailbox endpoints stored by the owner-approved setup action and the device setup documents. No mail server is included."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "128m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: roundcube: foundation.#ServiceDefinition & {
		name:     "roundcube"
		type:     "application"
		image:    "docker.io/roundcube/roundcubemail"
		tag:      "1.6.19-apache@sha256:f1256d1ce06ca5c52660f67f8511f3971def5d3b80aab3e3809df970489b1c46"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`mail.{{.domain}}`)"
				port:    80
			}
			networks: ["mail-internal"]
		}

		accessPolicy: {
			outerAuth: "self"
			appAuth:   "self-auth"
		}

		upstream: {
			github: repo: "roundcube/roundcubemail"
			registry: image: "docker.io/roundcube/roundcubemail"
			track: "minor"
		}

		volumes: [
			{
				source: "roundcube-database"
				target: "/var/roundcube/db"
				type:   "volume"
				backup: true
			},
			{
				source: "roundcube-mailbox"
				target: "/var/roundcube/mailbox"
				type:   "volume"
				backup: true
			},
			{
				source: "roundcube-config"
				target: "/var/roundcube/config"
				type:   "volume"
				backup: false
			},
			{
				source: "roundcube-temp"
				target: "/tmp/roundcube-temp"
				type:   "volume"
				backup: false
			},
		]

		environment: {
			ROUNDCUBEMAIL_DB_DIR:       "/var/roundcube/db"
			ROUNDCUBEMAIL_DB_TYPE:      "sqlite"
			ROUNDCUBEMAIL_PLUGINS:      "archive,zipdownload"
			ROUNDCUBEMAIL_REQUEST_PATH: "/"
			ROUNDCUBEMAIL_SKIN:         "elastic"
			ROUNDCUBEMAIL_TEMP_DIR:     "/tmp/roundcube-temp"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/"
				port:   80
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "128m"
			memoryMax: "256m"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Roundcube Webmail dashboard"
	}
}
