package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/kombifyio/stackkits/internal/standaloneoperations"
	"github.com/kombifyio/stackkits/internal/usecasecatalog"
)

const (
	computeTierFitsDocumentPath = "compute-tier-fits.json"
	computeTierFitsSchema       = "stackkits-webmcp-compute-tier-fits/v1"
	operationsDocumentPath      = "operations.json"
	operationsSchema            = "stackkits-webmcp-operations/v1"
)

// webMCPProjectionDocument is the generated bytes plus the exact file digest
// recorded in the authority manifest. The projection intentionally has no
// compiler or host-admission logic; it only republishes already validated
// public authority facts for the WebMCP build.
type webMCPProjectionDocument struct {
	Path string
	Data []byte
}

type computeTierFitsDocument struct {
	SchemaVersion string                   `json:"schemaVersion"`
	SourceSchema  string                   `json:"sourceSchema"`
	UseCases      []usecasecatalog.UseCase `json:"useCases"`
	ContentDigest string                   `json:"contentDigest"`
}

type operationsDocument struct {
	SchemaVersion string                          `json:"schemaVersion"`
	Operations    []standaloneoperations.Contract `json:"operations"`
	ContentDigest string                          `json:"contentDigest"`
}

// generateWebMCPProjectionDocuments reads the two existing authority owners
// and returns deterministic, redacted JSON documents. No generated bundle
// bytes or browser code are involved in this projection.
func generateWebMCPProjectionDocuments(repoRoot string) ([]webMCPProjectionDocument, error) {
	useCases, err := usecasecatalog.LoadUseCaseComputeTiers(repoRoot)
	if err != nil {
		return nil, fmt.Errorf("load use-case compute-tier authority: %w", err)
	}
	sort.Slice(useCases, func(i, j int) bool { return useCases[i].ID < useCases[j].ID })
	for _, useCase := range useCases {
		if strings.TrimSpace(useCase.ID) == "" || strings.TrimSpace(useCase.Title) == "" || strings.TrimSpace(useCase.Description) == "" {
			return nil, fmt.Errorf("use-case compute-tier authority contains an incomplete entry")
		}
		if len(useCase.ComputeTiers) == 0 {
			return nil, fmt.Errorf("use-case %s has no compute-tier authority", useCase.ID)
		}
	}
	compute := computeTierFitsDocument{
		SchemaVersion: computeTierFitsSchema,
		SourceSchema:  usecasecatalog.UseCaseSchema,
		UseCases:      useCases,
	}
	if err := validatePublicProjectionValue(compute); err != nil {
		return nil, fmt.Errorf("validate compute-tier projection: %w", err)
	}
	compute.ContentDigest, err = projectionContentDigest(compute)
	if err != nil {
		return nil, fmt.Errorf("digest compute-tier projection: %w", err)
	}
	computeBytes, err := marshalCanonicalJSON(compute)
	if err != nil {
		return nil, fmt.Errorf("encode compute-tier projection: %w", err)
	}

	if err := standaloneoperations.ValidateCatalog(); err != nil {
		return nil, fmt.Errorf("validate standalone operation authority: %w", err)
	}
	operations := standaloneoperations.All()
	sort.Slice(operations, func(i, j int) bool {
		return string(operations[i].ID) < string(operations[j].ID)
	})
	operationDocument := operationsDocument{
		SchemaVersion: operationsSchema,
		Operations:    operations,
	}
	if err := validatePublicProjectionValue(operationDocument); err != nil {
		return nil, fmt.Errorf("validate operations projection: %w", err)
	}
	operationDocument.ContentDigest, err = projectionContentDigest(operationDocument)
	if err != nil {
		return nil, fmt.Errorf("digest operations projection: %w", err)
	}
	operationBytes, err := marshalCanonicalJSON(operationDocument)
	if err != nil {
		return nil, fmt.Errorf("encode operations projection: %w", err)
	}

	return []webMCPProjectionDocument{
		{Path: computeTierFitsDocumentPath, Data: computeBytes},
		{Path: operationsDocumentPath, Data: operationBytes},
	}, nil
}

func projectionContentDigest(value any) (string, error) {
	data, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	var document map[string]any
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	if err := decoder.Decode(&document); err != nil {
		return "", err
	}
	delete(document, "contentDigest")
	canonical, err := json.Marshal(document)
	if err != nil {
		return "", err
	}
	return contentHash(canonical), nil
}

func marshalCanonicalJSON(value any) ([]byte, error) {
	data, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	return canonicalJSONBytes(data)
}

func canonicalJSONBytes(data []byte) ([]byte, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var document any
	if err := decoder.Decode(&document); err != nil {
		return nil, err
	}
	pretty, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(pretty, '\n'), nil
}

// validatePublicProjectionValue protects this public projection at the
// boundary. Typed projection structs already exclude these fields; walking
// the encoded value makes that exclusion fail closed if an owner adds a new
// field later. URL text is also rejected because this document has no URL
// authority and should remain portable across hosts.
func validatePublicProjectionValue(value any) error {
	data, err := json.Marshal(value)
	if err != nil {
		return err
	}
	var document any
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	if err := decoder.Decode(&document); err != nil {
		return err
	}
	return walkPublicProjectionValue(document, "$")
}

func walkPublicProjectionValue(value any, path string) error {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			lower := strings.ToLower(key)
			for _, forbidden := range []string{"provider", "secret", "credential", "endpoint", "privateurl", "private_url"} {
				if strings.Contains(lower, forbidden) {
					return fmt.Errorf("forbidden public field %s.%s", path, key)
				}
			}
			if err := walkPublicProjectionValue(child, path+"."+key); err != nil {
				return err
			}
		}
	case []any:
		for index, child := range typed {
			if err := walkPublicProjectionValue(child, fmt.Sprintf("%s[%d]", path, index)); err != nil {
				return err
			}
		}
	case string:
		if strings.Contains(typed, "://") {
			return fmt.Errorf("URL value is not allowed at %s", path)
		}
	}
	return nil
}
