// Package open_webui — Open WebUI module (scaffolded, draft).
//
// Open WebUI for owner-controlled private AI. Models require an explicit owner download.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package open_webui

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "open-webui"
		displayName: "Open WebUI"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Open WebUI for owner-controlled private AI. Models require an explicit owner download."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "1g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: "open-webui": foundation.#ServiceDefinition & {
		name:     "open-webui"
		type:     "application"
		image:    "ghcr.io/open-webui/open-webui"
		tag:      "v0.11.3@sha256:41daa0cf2561a5d4c8d1ff31ee2a98d93ab4d3ac2605cac69366ff6a3374a933"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`ai.{{.domain}}`)"
				port:    8080
			}
			networks: ["private-ai-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "self-auth"
		}

		upstream: {
			github: repo: "open-webui/open-webui"
			registry: image: "ghcr.io/open-webui/open-webui"
			track: "minor"
		}

		volumes: [
			{
				source: "open-webui-data"
				target: "/app/backend/data"
				type:   "volume"
				backup: true
			},
		]

		environment: {
			ENABLE_OPENAI_API:               "false"
			ENABLE_SIGNUP:                   "false"
			HF_HUB_OFFLINE:                  "1"
			OFFLINE_MODE:                    "true"
			OLLAMA_BASE_URL:                 "http://ollama:11434"
			RAG_EMBEDDING_MODEL_AUTO_UPDATE: "false"
			WHISPER_MODEL_AUTO_UPDATE:       "false"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/health"
				port:   8080
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "512m"
			memoryMax: "2g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Open WebUI dashboard"
	}
}
