# Generated by StackKit CLI
# Deployment: workspace
# StackKit: dev-homelab
# Variant: default

docker_host = "tcp://vm:2375"
domain = "example.local"
acme_email = "admin@example.com"
variant = "default"
compute_tier = "minimal"

