# Base Homelab - OpenTofu Configuration (Simple Mode, Modular)
# Generated by StackKits
# StackKit: base-homelab v4.0.0
#
# Architecture: Modular — each service is a reusable Terraform module.
# Variants:
#   - default: Dokploy + Uptime Kuma (recommended)
#   - beszel:  Dokploy + Beszel monitoring
#   - minimal: Dockge + Portainer + Netdata

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
  }
}

# =============================================================================
# VARIABLES
# =============================================================================

variable "domain" {
  description = "Optional base domain for proxy hostnames (e.g. homelab.example.com). Not required for ports mode."
  type        = string
  default     = ""
}

variable "acme_email" {
  description = "Optional email for ACME/Let's Encrypt (only used when enable_letsencrypt=true)"
  type        = string
  default     = ""
}

variable "access_mode" {
  description = "Access mode: 'ports' (zero-config, direct ports) or 'proxy' (Traefik routing with optional TLS)"
  type        = string
  default     = "ports"
  validation {
    condition     = contains(["ports", "proxy"], var.access_mode) && (var.access_mode != "proxy" || var.domain != "")
    error_message = "access_mode must be 'ports' or 'proxy'. If access_mode='proxy', you must set a real 'domain'."
  }
}

variable "enable_https" {
  description = "Enable HTTPS on Traefik (proxy mode)"
  type        = bool
  default     = false
}

variable "enable_letsencrypt" {
  description = "Enable Let's Encrypt via ACME (proxy mode only)"
  type        = bool
  default     = false
}

variable "_validate_letsencrypt" {
  description = "Internal validation helper"
  type        = bool
  default     = true
  validation {
    condition = (
      !var.enable_letsencrypt || (
        var.access_mode == "proxy" &&
        var.domain != "" &&
        var.enable_https &&
        var.acme_email != ""
      )
    )
    error_message = "enable_letsencrypt requires: access_mode='proxy', domain set, enable_https=true, and acme_email set."
  }
}

variable "variant" {
  description = "Service variant: default, beszel, or minimal"
  type        = string
  default     = "default"
  validation {
    condition     = contains(["default", "beszel", "minimal"], var.variant)
    error_message = "variant must be 'default', 'beszel', or 'minimal'"
  }
}

variable "compute_tier" {
  description = "Compute tier: high, standard, or low"
  type        = string
  default     = "standard"
  validation {
    condition     = contains(["high", "standard", "low"], var.compute_tier)
    error_message = "compute_tier must be 'high', 'standard', or 'low'"
  }
}

variable "bind_address" {
  description = "IP address to bind service ports on (0.0.0.0 = LAN)"
  type        = string
  default     = "0.0.0.0"
}

variable "advertise_host" {
  description = "Hostname/IP to use in printed links (defaults to <hostname>.local)"
  type        = string
  default     = ""
}

variable "traefik_dashboard_port" {
  description = "Host port for Traefik dashboard"
  type        = number
  default     = 8080
}

variable "dozzle_port" {
  description = "Host port for Dozzle (logs)"
  type        = number
  default     = 8888
}

variable "dokploy_port" {
  description = "Host port for Dokploy"
  type        = number
  default     = 3000
}

variable "uptime_kuma_port" {
  description = "Host port for Uptime Kuma"
  type        = number
  default     = 3001
}

variable "beszel_port" {
  description = "Host port for Beszel"
  type        = number
  default     = 8090
}

variable "dockge_port" {
  description = "Host port for Dockge"
  type        = number
  default     = 5001
}

variable "portainer_port" {
  description = "Host port for Portainer"
  type        = number
  default     = 9000
}

variable "netdata_port" {
  description = "Host port for Netdata"
  type        = number
  default     = 19999
}

variable "whoami_port" {
  description = "Host port for Whoami (test service)"
  type        = number
  default     = 9080
}

variable "stacks_dir" {
  description = "Directory for Docker Compose stacks (minimal variant)"
  type        = string
  default     = "/opt/stacks"
}

# =============================================================================
# LOCALS
# =============================================================================

locals {
  hostname  = try(trimspace(file("/etc/hostname")), "homelab")
  mdns_host = "${local.hostname}.local"
  advertise = var.advertise_host != "" ? var.advertise_host : local.mdns_host

  # Variant flags
  is_default  = var.variant == "default"
  is_beszel   = var.variant == "beszel"
  is_minimal  = var.variant == "minimal"
  use_dokploy = local.is_default || local.is_beszel

  # Common labels
  common_labels = {
    "managed-by" = "kombistack"
    "stackkit"   = "base-homelab"
    "variant"    = var.variant
  }

  # Memory limits based on compute tier
  memory_limits = {
    high     = { dokploy = 2048, monitoring = 1024, logs = 512, test = 128 }
    standard = { dokploy = 1024, monitoring = 512,  logs = 256, test = 64 }
    low      = { dokploy = 512,  monitoring = 256,  logs = 128, test = 32 }
  }
  mem = local.memory_limits[var.compute_tier]

  # Proxy settings (passed to modules)
  use_proxy    = var.access_mode == "proxy"
  proxy_scheme = local.use_proxy && var.enable_https ? "https" : "http"
}

# =============================================================================
# PROVIDER
# =============================================================================

provider "docker" {
}

# =============================================================================
# SHARED NETWORK
# =============================================================================

resource "docker_network" "traefik" {
  name   = "traefik"
  driver = "bridge"

  labels {
    label = "managed-by"
    value = "kombistack"
  }
}

# =============================================================================
# SERVICE MODULES
# =============================================================================

module "traefik" {
  source = "./modules/traefik"

  network_name       = docker_network.traefik.name
  access_mode        = var.access_mode
  enable_https       = var.enable_https
  enable_letsencrypt = var.enable_letsencrypt
  domain             = var.domain
  acme_email         = var.acme_email
  dashboard_port     = var.traefik_dashboard_port
  bind_address       = var.bind_address
  common_labels      = local.common_labels
}

module "dokploy" {
  source = "./modules/dokploy"

  enabled            = local.use_dokploy
  network_name       = docker_network.traefik.name
  access_mode        = var.access_mode
  enable_https       = var.enable_https
  enable_letsencrypt = var.enable_letsencrypt
  domain             = var.domain
  port               = var.dokploy_port
  memory_limit       = local.mem.dokploy
  common_labels      = local.common_labels

  depends_on = [module.traefik]
}

module "monitoring" {
  source = "./modules/monitoring"

  variant            = var.variant
  network_name       = docker_network.traefik.name
  access_mode        = var.access_mode
  enable_https       = var.enable_https
  enable_letsencrypt = var.enable_letsencrypt
  domain             = var.domain
  uptime_kuma_port   = var.uptime_kuma_port
  beszel_port        = var.beszel_port
  netdata_port       = var.netdata_port
  memory_limit       = local.mem.monitoring
  common_labels      = local.common_labels

  depends_on = [module.traefik]
}

module "dozzle" {
  source = "./modules/dozzle"

  network_name       = docker_network.traefik.name
  access_mode        = var.access_mode
  enable_https       = var.enable_https
  enable_letsencrypt = var.enable_letsencrypt
  domain             = var.domain
  port               = var.dozzle_port
  memory_limit       = local.mem.logs
  common_labels      = local.common_labels

  depends_on = [module.traefik]
}

module "whoami" {
  source = "./modules/whoami"

  enabled            = local.use_dokploy
  network_name       = docker_network.traefik.name
  access_mode        = var.access_mode
  enable_https       = var.enable_https
  enable_letsencrypt = var.enable_letsencrypt
  domain             = var.domain
  port               = var.whoami_port
  memory_limit       = local.mem.test
  common_labels      = local.common_labels

  depends_on = [module.traefik]
}

module "dockge" {
  source = "./modules/dockge"

  enabled            = local.is_minimal
  network_name       = docker_network.traefik.name
  access_mode        = var.access_mode
  enable_https       = var.enable_https
  enable_letsencrypt = var.enable_letsencrypt
  domain             = var.domain
  port               = var.dockge_port
  stacks_dir         = var.stacks_dir
  memory_limit       = local.mem.dokploy
  common_labels      = local.common_labels

  depends_on = [module.traefik]
}

module "portainer" {
  source = "./modules/portainer"

  enabled            = local.is_minimal
  network_name       = docker_network.traefik.name
  access_mode        = var.access_mode
  enable_https       = var.enable_https
  enable_letsencrypt = var.enable_letsencrypt
  domain             = var.domain
  port               = var.portainer_port
  memory_limit       = local.mem.dokploy
  common_labels      = local.common_labels

  depends_on = [module.traefik]
}

# =============================================================================
# OUTPUTS
# =============================================================================

output "service_urls" {
  description = "All deployed service URLs"
  value = {
    mode            = var.access_mode
    hostname        = local.hostname
    mdns            = local.mdns_host
    suggested_hosts = [local.mdns_host, local.hostname]
    advertised_host = local.advertise

    ports = {
      traefik_dashboard = {
        name = "Traefik Dashboard"
        url  = "http://${local.advertise}:${var.traefik_dashboard_port}"
      }
      dokploy = local.use_dokploy ? {
        name = "Dokploy"
        url  = "http://${local.advertise}:${var.dokploy_port}"
      } : null
      monitoring = local.is_default ? {
        name = "Uptime Kuma"
        url  = "http://${local.advertise}:${var.uptime_kuma_port}"
      } : local.is_beszel ? {
        name = "Beszel"
        url  = "http://${local.advertise}:${var.beszel_port}"
      } : {
        name = "Netdata"
        url  = "http://${local.advertise}:${var.netdata_port}"
      }
      logs = {
        name = "Dozzle"
        url  = "http://${local.advertise}:${var.dozzle_port}"
      }
      whoami = local.use_dokploy ? {
        name = "Whoami"
        url  = "http://${local.advertise}:${var.whoami_port}"
      } : null
      dockge = local.is_minimal ? {
        name = "Dockge"
        url  = "http://${local.advertise}:${var.dockge_port}"
      } : null
      portainer = local.is_minimal ? {
        name = "Portainer"
        url  = "http://${local.advertise}:${var.portainer_port}"
      } : null
    }

    proxy = local.use_proxy ? {
      base_domain = var.domain
      scheme      = local.proxy_scheme
    } : null
  }
}

output "variant" {
  description = "Active service variant"
  value       = var.variant
}

output "compute_tier" {
  description = "Active compute tier"
  value       = var.compute_tier
}
