# Base Homelab - OpenTofu Configuration (Simple Mode)
# Generated by KombiStack Unifier
# StackKit: base-homelab v2.0.0
# 
# Variants:
#   - default: Dokploy + Uptime Kuma (recommended)
#   - beszel:  Dokploy + Beszel monitoring
#   - minimal: Dockge + Portainer + Netdata

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
  }
}

# =============================================================================
# VARIABLES
# =============================================================================

variable "domain" {
  description = "Primary domain for the homelab"
  type        = string
}

variable "acme_email" {
  description = "Email for ACME/Let's Encrypt certificates"
  type        = string
}

variable "variant" {
  description = "Service variant: default, beszel, or minimal"
  type        = string
  default     = "default"
  validation {
    condition     = contains(["default", "beszel", "minimal"], var.variant)
    error_message = "variant must be 'default', 'beszel', or 'minimal'"
  }
}

variable "compute_tier" {
  description = "Compute tier: high, standard, or low"
  type        = string
  default     = "standard"
  validation {
    condition     = contains(["high", "standard", "low"], var.compute_tier)
    error_message = "compute_tier must be 'high', 'standard', or 'low'"
  }
}

variable "traefik_dashboard_insecure" {
  description = "Enable insecure dashboard access (dev only)"
  type        = bool
  default     = false
}

variable "stacks_dir" {
  description = "Directory for Docker Compose stacks (minimal variant)"
  type        = string
  default     = "/opt/stacks"
}

# =============================================================================
# LOCALS
# =============================================================================

locals {
  # Service URLs
  traefik_url     = "traefik.${var.domain}"
  deploy_url      = "deploy.${var.domain}"
  status_url      = "status.${var.domain}"
  monitor_url     = "monitor.${var.domain}"
  logs_url        = "logs.${var.domain}"
  whoami_url      = "whoami.${var.domain}"
  dockge_url      = "dockge.${var.domain}"
  portainer_url   = "portainer.${var.domain}"

  # Variant flags
  is_default  = var.variant == "default"
  is_beszel   = var.variant == "beszel"
  is_minimal  = var.variant == "minimal"
  use_dokploy = local.is_default || local.is_beszel
  use_dockge  = local.is_minimal

  # Common labels
  common_labels = {
    "managed-by" = "kombistack"
    "stackkit"   = "base-homelab"
    "variant"    = var.variant
  }

  # Memory limits based on compute tier
  memory_limits = {
    high     = { dokploy = 2048, monitoring = 1024, logs = 512, test = 128 }
    standard = { dokploy = 1024, monitoring = 512,  logs = 256, test = 64 }
    low      = { dokploy = 512,  monitoring = 256,  logs = 128, test = 32 }
  }
  mem = local.memory_limits[var.compute_tier]
}

# =============================================================================
# PROVIDER
# =============================================================================

provider "docker" {
  host = "unix:///var/run/docker.sock"
}

# =============================================================================
# NETWORK
# =============================================================================

resource "docker_network" "traefik" {
  name   = "traefik"
  driver = "bridge"

  labels {
    label = "managed-by"
    value = "kombistack"
  }
}

# =============================================================================
# VOLUMES
# =============================================================================

resource "docker_volume" "traefik_certs" {
  name = "traefik-certs"
  labels { label = "managed-by"; value = "kombistack" }
}

resource "docker_volume" "traefik_config" {
  name = "traefik-config"
  labels { label = "managed-by"; value = "kombistack" }
}

# Dokploy volume (default/beszel variants)
resource "docker_volume" "dokploy_data" {
  count = local.use_dokploy ? 1 : 0
  name  = "dokploy-data"
  labels { label = "managed-by"; value = "kombistack" }
}

# Uptime Kuma volume (default variant)
resource "docker_volume" "uptime_kuma_data" {
  count = local.is_default ? 1 : 0
  name  = "uptime-kuma-data"
  labels { label = "managed-by"; value = "kombistack" }
}

# Beszel volume (beszel variant)
resource "docker_volume" "beszel_data" {
  count = local.is_beszel ? 1 : 0
  name  = "beszel-data"
  labels { label = "managed-by"; value = "kombistack" }
}

# Dockge volume (minimal variant)
resource "docker_volume" "dockge_data" {
  count = local.use_dockge ? 1 : 0
  name  = "dockge-data"
  labels { label = "managed-by"; value = "kombistack" }
}

# Portainer volume (minimal variant)
resource "docker_volume" "portainer_data" {
  count = local.is_minimal ? 1 : 0
  name  = "portainer-data"
  labels { label = "managed-by"; value = "kombistack" }
}

# Netdata volumes (minimal variant)
resource "docker_volume" "netdata_config" {
  count = local.is_minimal ? 1 : 0
  name  = "netdata-config"
  labels { label = "managed-by"; value = "kombistack" }
}

resource "docker_volume" "netdata_lib" {
  count = local.is_minimal ? 1 : 0
  name  = "netdata-lib"
  labels { label = "managed-by"; value = "kombistack" }
}

# =============================================================================
# TRAEFIK - Reverse Proxy (ALL VARIANTS)
# =============================================================================

resource "docker_image" "traefik" {
  name         = "traefik:v3.1"
  keep_locally = true
}

resource "docker_container" "traefik" {
  name  = "traefik"
  image = docker_image.traefik.image_id

  restart = "unless-stopped"

  ports {
    internal = 80
    external = 80
  }

  ports {
    internal = 443
    external = 443
  }

  ports {
    internal = 8080
    external = 8080
  }

  volumes {
    host_path      = "/var/run/docker.sock"
    container_path = "/var/run/docker.sock"
    read_only      = true
  }

  volumes {
    volume_name    = docker_volume.traefik_certs.name
    container_path = "/certs"
  }

  volumes {
    volume_name    = docker_volume.traefik_config.name
    container_path = "/etc/traefik"
  }

  networks_advanced {
    name = docker_network.traefik.name
  }

  command = [
    "--api.dashboard=true",
    "--api.insecure=${var.traefik_dashboard_insecure}",
    "--providers.docker=true",
    "--providers.docker.exposedbydefault=false",
    "--providers.docker.network=traefik",
    "--entrypoints.web.address=:80",
    "--entrypoints.web.http.redirections.entrypoint.to=websecure",
    "--entrypoints.web.http.redirections.entrypoint.scheme=https",
    "--entrypoints.websecure.address=:443",
    "--certificatesresolvers.letsencrypt.acme.email=${var.acme_email}",
    "--certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json",
    "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web",
    "--ping=true",
    "--log.level=INFO",
  ]

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                            = "true"
      "traefik.http.routers.traefik.entrypoints"  = "websecure"
      "traefik.http.routers.traefik.rule"         = "Host(`${local.traefik_url}`)"
      "traefik.http.routers.traefik.service"      = "api@internal"
      "traefik.http.routers.traefik.tls.certresolver" = "letsencrypt"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  healthcheck {
    test         = ["CMD", "traefik", "healthcheck", "--ping"]
    interval     = "10s"
    timeout      = "5s"
    retries      = 3
    start_period = "10s"
  }
}

# =============================================================================
# DOKPLOY - PaaS Platform (DEFAULT + BESZEL VARIANTS)
# =============================================================================

resource "docker_image" "dokploy" {
  count        = local.use_dokploy ? 1 : 0
  name         = "dokploy/dokploy:latest"
  keep_locally = true
}

resource "docker_container" "dokploy" {
  count = local.use_dokploy ? 1 : 0

  name  = "dokploy"
  image = docker_image.dokploy[0].image_id

  restart    = "unless-stopped"
  depends_on = [docker_container.traefik]

  volumes {
    host_path      = "/var/run/docker.sock"
    container_path = "/var/run/docker.sock"
  }

  volumes {
    volume_name    = docker_volume.dokploy_data[0].name
    container_path = "/app/data"
  }

  networks_advanced {
    name = docker_network.traefik.name
  }

  env = ["NODE_ENV=production"]

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                                          = "true"
      "traefik.http.routers.dokploy.entrypoints"                = "websecure"
      "traefik.http.routers.dokploy.rule"                       = "Host(`${local.deploy_url}`)"
      "traefik.http.routers.dokploy.tls.certresolver"           = "letsencrypt"
      "traefik.http.services.dokploy.loadbalancer.server.port"  = "3000"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  memory = local.mem.dokploy
}

# =============================================================================
# UPTIME KUMA - Monitoring (DEFAULT VARIANT)
# =============================================================================

resource "docker_image" "uptime_kuma" {
  count        = local.is_default ? 1 : 0
  name         = "louislam/uptime-kuma:1"
  keep_locally = true
}

resource "docker_container" "uptime_kuma" {
  count = local.is_default ? 1 : 0

  name  = "uptime-kuma"
  image = docker_image.uptime_kuma[0].image_id

  restart    = "unless-stopped"
  depends_on = [docker_container.traefik]

  volumes {
    volume_name    = docker_volume.uptime_kuma_data[0].name
    container_path = "/app/data"
  }

  networks_advanced {
    name = docker_network.traefik.name
  }

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                                             = "true"
      "traefik.http.routers.uptime-kuma.entrypoints"               = "websecure"
      "traefik.http.routers.uptime-kuma.rule"                      = "Host(`${local.status_url}`)"
      "traefik.http.routers.uptime-kuma.tls.certresolver"          = "letsencrypt"
      "traefik.http.services.uptime-kuma.loadbalancer.server.port" = "3001"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  memory = local.mem.monitoring
}

# =============================================================================
# BESZEL - Server Monitoring (BESZEL VARIANT)
# =============================================================================

resource "docker_image" "beszel" {
  count        = local.is_beszel ? 1 : 0
  name         = "henrygd/beszel:latest"
  keep_locally = true
}

resource "docker_container" "beszel" {
  count = local.is_beszel ? 1 : 0

  name  = "beszel"
  image = docker_image.beszel[0].image_id

  restart    = "unless-stopped"
  depends_on = [docker_container.traefik]

  volumes {
    volume_name    = docker_volume.beszel_data[0].name
    container_path = "/beszel_data"
  }

  networks_advanced {
    name = docker_network.traefik.name
  }

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                                        = "true"
      "traefik.http.routers.beszel.entrypoints"               = "websecure"
      "traefik.http.routers.beszel.rule"                      = "Host(`${local.monitor_url}`)"
      "traefik.http.routers.beszel.tls.certresolver"          = "letsencrypt"
      "traefik.http.services.beszel.loadbalancer.server.port" = "8090"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  memory = local.mem.monitoring
}

# =============================================================================
# DOZZLE - Log Viewer (ALL VARIANTS)
# =============================================================================

resource "docker_image" "dozzle" {
  name         = "amir20/dozzle:latest"
  keep_locally = true
}

resource "docker_container" "dozzle" {
  name  = "dozzle"
  image = docker_image.dozzle.image_id

  restart    = "unless-stopped"
  depends_on = [docker_container.traefik]

  volumes {
    host_path      = "/var/run/docker.sock"
    container_path = "/var/run/docker.sock"
    read_only      = true
  }

  networks_advanced {
    name = docker_network.traefik.name
  }

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                                        = "true"
      "traefik.http.routers.dozzle.entrypoints"               = "websecure"
      "traefik.http.routers.dozzle.rule"                      = "Host(`${local.logs_url}`)"
      "traefik.http.routers.dozzle.tls.certresolver"          = "letsencrypt"
      "traefik.http.services.dozzle.loadbalancer.server.port" = "8080"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  memory = local.mem.logs
}

# =============================================================================
# WHOAMI - Test Container (DEFAULT + BESZEL VARIANTS)
# =============================================================================

resource "docker_image" "whoami" {
  count        = local.use_dokploy ? 1 : 0
  name         = "traefik/whoami:latest"
  keep_locally = true
}

resource "docker_container" "whoami" {
  count = local.use_dokploy ? 1 : 0

  name  = "whoami"
  image = docker_image.whoami[0].image_id

  restart    = "unless-stopped"
  depends_on = [docker_container.traefik]

  networks_advanced {
    name = docker_network.traefik.name
  }

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                                        = "true"
      "traefik.http.routers.whoami.entrypoints"               = "websecure"
      "traefik.http.routers.whoami.rule"                      = "Host(`${local.whoami_url}`)"
      "traefik.http.routers.whoami.tls.certresolver"          = "letsencrypt"
      "traefik.http.services.whoami.loadbalancer.server.port" = "80"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  memory = local.mem.test
}

# =============================================================================
# DOCKGE - Compose Manager (MINIMAL VARIANT)
# =============================================================================

resource "docker_image" "dockge" {
  count        = local.use_dockge ? 1 : 0
  name         = "louislam/dockge:1"
  keep_locally = true
}

resource "docker_container" "dockge" {
  count = local.use_dockge ? 1 : 0

  name  = "dockge"
  image = docker_image.dockge[0].image_id

  restart    = "unless-stopped"
  depends_on = [docker_container.traefik]

  volumes {
    host_path      = "/var/run/docker.sock"
    container_path = "/var/run/docker.sock"
  }

  volumes {
    volume_name    = docker_volume.dockge_data[0].name
    container_path = "/app/data"
  }

  volumes {
    host_path      = var.stacks_dir
    container_path = "/opt/stacks"
  }

  networks_advanced {
    name = docker_network.traefik.name
  }

  env = ["DOCKGE_STACKS_DIR=/opt/stacks"]

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                                        = "true"
      "traefik.http.routers.dockge.entrypoints"               = "websecure"
      "traefik.http.routers.dockge.rule"                      = "Host(`${local.dockge_url}`)"
      "traefik.http.routers.dockge.tls.certresolver"          = "letsencrypt"
      "traefik.http.services.dockge.loadbalancer.server.port" = "5001"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  memory = local.mem.dokploy
}

# =============================================================================
# PORTAINER - Container Management (MINIMAL VARIANT)
# =============================================================================

resource "docker_image" "portainer" {
  count        = local.is_minimal ? 1 : 0
  name         = "portainer/portainer-ce:latest"
  keep_locally = true
}

resource "docker_container" "portainer" {
  count = local.is_minimal ? 1 : 0

  name  = "portainer"
  image = docker_image.portainer[0].image_id

  restart    = "unless-stopped"
  depends_on = [docker_container.traefik]

  volumes {
    host_path      = "/var/run/docker.sock"
    container_path = "/var/run/docker.sock"
  }

  volumes {
    volume_name    = docker_volume.portainer_data[0].name
    container_path = "/data"
  }

  networks_advanced {
    name = docker_network.traefik.name
  }

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                                           = "true"
      "traefik.http.routers.portainer.entrypoints"               = "websecure"
      "traefik.http.routers.portainer.rule"                      = "Host(`${local.portainer_url}`)"
      "traefik.http.routers.portainer.tls.certresolver"          = "letsencrypt"
      "traefik.http.services.portainer.loadbalancer.server.port" = "9000"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  memory = local.mem.dokploy
}

# =============================================================================
# NETDATA - System Monitoring (MINIMAL VARIANT)
# =============================================================================

resource "docker_image" "netdata" {
  count        = local.is_minimal ? 1 : 0
  name         = "netdata/netdata:stable"
  keep_locally = true
}

resource "docker_container" "netdata" {
  count = local.is_minimal ? 1 : 0

  name  = "netdata"
  image = docker_image.netdata[0].image_id

  restart    = "unless-stopped"
  depends_on = [docker_container.traefik]

  capabilities {
    add = ["SYS_PTRACE"]
  }

  security_opts = ["apparmor:unconfined"]

  volumes {
    host_path      = "/proc"
    container_path = "/host/proc"
    read_only      = true
  }

  volumes {
    host_path      = "/sys"
    container_path = "/host/sys"
    read_only      = true
  }

  volumes {
    host_path      = "/var/run/docker.sock"
    container_path = "/var/run/docker.sock"
    read_only      = true
  }

  volumes {
    volume_name    = docker_volume.netdata_config[0].name
    container_path = "/etc/netdata"
  }

  volumes {
    volume_name    = docker_volume.netdata_lib[0].name
    container_path = "/var/lib/netdata"
  }

  networks_advanced {
    name = docker_network.traefik.name
  }

  dynamic "labels" {
    for_each = merge(local.common_labels, {
      "traefik.enable"                                         = "true"
      "traefik.http.routers.netdata.entrypoints"               = "websecure"
      "traefik.http.routers.netdata.rule"                      = "Host(`${local.monitor_url}`)"
      "traefik.http.routers.netdata.tls.certresolver"          = "letsencrypt"
      "traefik.http.services.netdata.loadbalancer.server.port" = "19999"
    })
    content {
      label = labels.key
      value = labels.value
    }
  }

  memory = local.mem.monitoring
}

# =============================================================================
# OUTPUTS - Service URLs
# =============================================================================

output "service_urls" {
  description = "All deployed service URLs"
  value = {
    traefik = {
      name        = "Traefik Dashboard"
      url         = "https://${local.traefik_url}"
      description = "Reverse proxy dashboard"
    }
    
    # Default/Beszel variant services
    dokploy = local.use_dokploy ? {
      name        = "Dokploy"
      url         = "https://${local.deploy_url}"
      description = "PaaS deployment platform"
    } : null

    monitoring = local.is_default ? {
      name        = "Uptime Kuma"
      url         = "https://${local.status_url}"
      description = "Service status and uptime monitoring"
    } : local.is_beszel ? {
      name        = "Beszel"
      url         = "https://${local.monitor_url}"
      description = "Server metrics monitoring"
    } : {
      name        = "Netdata"
      url         = "https://${local.monitor_url}"
      description = "System performance monitoring"
    }

    logs = {
      name        = "Dozzle"
      url         = "https://${local.logs_url}"
      description = "Real-time container log viewer"
    }

    # Test service (default/beszel only)
    whoami = local.use_dokploy ? {
      name        = "Whoami"
      url         = "https://${local.whoami_url}"
      description = "Test service for proxy verification"
    } : null

    # Minimal variant services
    dockge = local.use_dockge ? {
      name        = "Dockge"
      url         = "https://${local.dockge_url}"
      description = "Docker Compose management"
    } : null

    portainer = local.is_minimal ? {
      name        = "Portainer"
      url         = "https://${local.portainer_url}"
      description = "Container management UI"
    } : null
  }
}

output "deployment_summary" {
  description = "Deployment summary in Markdown format"
  value = <<-EOT
# 🏠 Base Homelab - Deployment Complete

**Variant:** ${var.variant}
**Compute Tier:** ${var.compute_tier}
**Domain:** ${var.domain}

## 🔗 Service URLs

| Service | URL | Description |
|---------|-----|-------------|
| Traefik | https://${local.traefik_url} | Reverse proxy dashboard |
${local.use_dokploy ? "| Dokploy | https://${local.deploy_url} | PaaS deployment platform |\n" : ""}${local.is_default ? "| Uptime Kuma | https://${local.status_url} | Status monitoring |\n" : ""}${local.is_beszel ? "| Beszel | https://${local.monitor_url} | Server monitoring |\n" : ""}| Dozzle | https://${local.logs_url} | Container logs |
${local.use_dokploy ? "| Whoami | https://${local.whoami_url} | Test service |\n" : ""}${local.use_dockge ? "| Dockge | https://${local.dockge_url} | Compose manager |\n" : ""}${local.is_minimal ? "| Portainer | https://${local.portainer_url} | Container UI |\n| Netdata | https://${local.monitor_url} | System monitoring |\n" : ""}
## 📋 Next Steps

1. Access Traefik dashboard to verify routing
2. ${local.use_dokploy ? "Configure Dokploy and deploy your first application" : "Open Dockge/Portainer to manage containers"}
3. Set up monitoring alerts in ${local.is_default ? "Uptime Kuma" : local.is_beszel ? "Beszel" : "Netdata"}
4. Check logs in Dozzle for any issues

EOT
}

output "variant" {
  description = "Active service variant"
  value       = var.variant
}

output "compute_tier" {
  description = "Active compute tier"
  value       = var.compute_tier
}
