package architecturev2

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"sync"
	"time"

	"github.com/kombifyio/stackkits/internal/confinedfs"
	"github.com/kombifyio/stackkits/internal/generationartifact"
	"github.com/kombifyio/stackkits/internal/resolvedplan"
)

// applyAuthorizationPolicy is package-private until the provider-free executor
// registry owns its construction. Request callers must never select their own
// executor identity or producer trust roots.
type applyAuthorizationPolicy struct {
	Executor         generationartifact.ApplyExecutorIdentity
	TrustedProducers map[string]generationartifact.ApplyEvidenceProducerTrust
}

// applyAuthorizer upgrades exact held generation output and authenticated
// evidence into a one-shot execution capability. It deliberately does not own
// or invoke an executor.
type applyAuthorizer struct {
	service           *Service
	executor          generationartifact.ApplyExecutorIdentity
	trustedProducers  map[string]generationartifact.ApplyEvidenceProducerTrust
	evidenceCollector ProductApplyEvidenceCollector
}

// newApplyAuthorizer is intentionally unavailable to command/request callers.
// The later internal executor registry will be the only production owner.
func (s *Service) newApplyAuthorizer(policy applyAuthorizationPolicy) (*applyAuthorizer, error) {
	if s == nil || s.validator == nil || s.generation == nil {
		return nil, resolveError(ErrAuthorityLoad, "Architecture v2 Apply authority is not initialized", nil)
	}
	if err := generationartifact.ValidateApplyExecutorIdentity(policy.Executor); err != nil {
		return nil, resolveError(ErrApplyAuthorization, "Apply executor identity is invalid", err)
	}
	return &applyAuthorizer{
		service: s, executor: policy.Executor, trustedProducers: cloneApplyProducerTrust(policy.TrustedProducers),
		evidenceCollector: s.productApplyEvidenceCollector,
	}, nil
}

// applyAuthorizationInput contains request-specific bytes and already-held
// filesystem capabilities. The plan, executor identity, output root, and trust
// policy remain authorizer-owned and cannot be substituted here.
type applyAuthorizationInput struct {
	Context        context.Context
	Current        CurrentResolution
	Workspace      *confinedfs.Transaction
	OutputLock     *confinedfs.OutputLock
	Versions       generationartifact.ComponentVersions
	EvidenceBundle []byte
}

type applyAuthorizationStage uint8

const (
	applyAuthorizationIssued applyAuthorizationStage = iota + 1
	applyAuthorizationConsuming
	applyAuthorizationConsumed
	applyAuthorizationClosed
)

type applyAuthorizationState struct {
	mu        sync.Mutex
	stage     applyAuthorizationStage
	workspace *confinedfs.Transaction
	lockLease *confinedfs.OutputLockLease
}

// VerifiedApplyAuthorization is the non-forgeable, one-shot result of the
// complete held-workspace Apply gate. Copies share consumption and close state.
// No package outside architecturev2 can turn it into executor input.
type VerifiedApplyAuthorization struct {
	plan             generationartifact.VerifiedPlan
	owner            *generationCoordinator
	state            *applyAuthorizationState
	key              string
	epoch            uint64
	manifestHash     string
	receiptHash      string
	requirementsHash string
	bundleHash       string
	executor         generationartifact.ApplyExecutorIdentity
	expiresAt        time.Time
	authorized       bool
}

// Authorize verifies Apply readiness, held generated bytes and controls, and
// the exact authenticated external evidence set while retaining the same
// transaction and output-lock borrow for later one-shot consumption.
func (a *applyAuthorizer) authorize(input applyAuthorizationInput) (VerifiedApplyAuthorization, error) {
	if a == nil || a.service == nil || a.service.generation == nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "Apply authorizer is not initialized", nil)
	}
	current := input.Current
	coordinator := a.service.generation
	if !current.valid || current.owner == nil || current.owner != coordinator {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "authorization requires a current resolution issued by this Apply authority", nil)
	}
	if !coordinator.beginApplyAuthorization(current.key, current.epoch, current.plan.Binding()) {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "current resolution is stale, superseded, or already consumed", nil)
	}
	completed := false
	defer func() {
		if !completed {
			coordinator.finishApplyAuthorization(current.key, current.epoch, current.plan.Binding(), false)
		}
	}()
	if input.Workspace == nil || input.OutputLock == nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "held workspace transaction and output lock are required", nil)
	}
	lease, err := input.OutputLock.Borrow(input.Workspace, current.plan.OutputRoot())
	if err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "borrow exact held output lock", err)
	}
	leaseOwned := true
	defer func() {
		if leaseOwned {
			_ = lease.Close()
		}
	}()
	if err := current.plan.VerifyCompatibility(input.Versions); err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "current plan is incompatible with the participating components", err)
	}
	if err := current.plan.RequireReady(generationartifact.ExecutionPhaseApply); err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "current plan is not ready for Apply", err)
	}
	if err := RequireNoPendingOutputTransaction(input.Workspace, current.plan.OutputRoot()); err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "governed output has a pending transaction", err)
	}
	manifest, err := generationartifact.ReadManifestHeld(current.plan, input.Workspace, ".")
	if err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "read held generation manifest", err)
	}
	if err := generationartifact.VerifyManifestHeld(current.plan, input.Workspace, ".", manifest); err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "verify held generated output", err)
	}
	receipt, err := generationartifact.ReadReceiptHeld(current.plan, input.Workspace, ".")
	if err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "read held generation receipt", err)
	}
	if err := generationartifact.VerifyReceipt(current.plan, manifest, receipt); err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "verify held generation receipt", err)
	}
	evaluatedAt := time.Now().UTC()
	var collectionRequest ProductApplyEvidenceCollectionRequest
	if !nilProductApplyEvidenceCollector(a.evidenceCollector) {
		collectionRequest, err = newProductApplyEvidenceCollectionRequest(current.plan, manifest, a.executor, evaluatedAt)
		if err != nil {
			return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "build exact product Apply evidence request", err)
		}
	}
	evidenceBytes, err := productApplyEvidenceBytes(input.Context, a.evidenceCollector, input.EvidenceBundle, collectionRequest)
	if err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "collect exact product Apply evidence", err)
	}
	evidence, err := generationartifact.VerifyApplyEvidenceBundleAt(generationartifact.ApplyEvidenceVerificationInput{
		Plan: current.plan, Manifest: manifest, GenerationReceipt: receipt, Executor: a.executor,
		Bundle: evidenceBytes, TrustedProducers: a.trustedProducers,
	}, evaluatedAt)
	if err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "verify exact external Apply evidence", err)
	}
	authorization, err := newVerifiedApplyAuthorization(current, input.Workspace, lease, manifest, receipt, evidence, a.executor)
	if err != nil {
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "mint one-shot Apply authorization", err)
	}
	leaseOwned = false
	if !coordinator.finishApplyAuthorization(current.key, current.epoch, current.plan.Binding(), true) {
		_ = authorization.Close()
		return VerifiedApplyAuthorization{}, resolveError(ErrApplyAuthorization, "current resolution was superseded while Apply authorization was evaluated", nil)
	}
	completed = true
	return authorization, nil
}

func newVerifiedApplyAuthorization(current CurrentResolution, workspace *confinedfs.Transaction, lease *confinedfs.OutputLockLease, manifest generationartifact.ArtifactManifest, receipt generationartifact.GenerationReceipt, evidence generationartifact.VerifiedApplyEvidenceBundle, executor generationartifact.ApplyExecutorIdentity) (VerifiedApplyAuthorization, error) {
	manifestHash, err := manifest.Hash()
	if err != nil {
		return VerifiedApplyAuthorization{}, err
	}
	receiptHash, err := canonicalGenerationReceiptHash(receipt)
	if err != nil {
		return VerifiedApplyAuthorization{}, err
	}
	request, err := current.plan.ApplyEvidenceRequest()
	if err != nil {
		return VerifiedApplyAuthorization{}, err
	}
	if !current.valid || current.owner == nil || strings.TrimSpace(current.key) == "" || current.epoch == 0 || workspace == nil || lease == nil ||
		evidence.BundleHash() == "" || evidence.RequirementsHash() != request.RequirementsHash || evidence.ExpiresAt().IsZero() ||
		!evidence.ExpiresAt().After(evidence.EvaluatedAt()) {
		return VerifiedApplyAuthorization{}, applyAuthorizationArtifactError(generationartifact.ErrInvalidContract, "apply.authorization", "complete verified plan, evidence, coordinator, workspace, and lock bindings are required", nil)
	}
	if err := lease.Verify(workspace, current.plan.OutputRoot()); err != nil {
		return VerifiedApplyAuthorization{}, err
	}
	return VerifiedApplyAuthorization{
		plan: current.plan, owner: current.owner,
		state: &applyAuthorizationState{stage: applyAuthorizationIssued, workspace: workspace, lockLease: lease},
		key:   current.key, epoch: current.epoch, manifestHash: manifestHash, receiptHash: receiptHash,
		requirementsHash: request.RequirementsHash, bundleHash: evidence.BundleHash(), executor: executor,
		expiresAt: evidence.ExpiresAt(), authorized: true,
	}, nil
}

// applyExecutionGrant is intentionally package-private. The later executor
// registry may consume it, but callers cannot unwrap a VerifiedPlan or held
// filesystem capability from VerifiedApplyAuthorization.
type applyExecutionGrant struct {
	plan             generationartifact.VerifiedPlan
	artifacts        []applyArtifactSnapshot
	manifestHash     string
	receiptHash      string
	requirementsHash string
	bundleHash       string
	executor         generationartifact.ApplyExecutorIdentity
	evaluatedAt      time.Time
	expiresAt        time.Time
	release          func()
}

// applyArtifactSnapshot is the immutable executor input captured from one
// stable held-file read after closed-tree verification. A later executor never
// receives the workspace capability and therefore cannot reopen changed bytes.
type applyArtifactSnapshot struct {
	ID                   string   `json:"id"`
	Path                 string   `json:"path"`
	Kind                 string   `json:"kind"`
	Format               string   `json:"format"`
	Mode                 string   `json:"mode"`
	ExecutionClass       string   `json:"execution_class"`
	OwnerKind            string   `json:"owner_kind"`
	OwnerRef             string   `json:"owner_ref"`
	OwnerContractHash    string   `json:"owner_contract_hash"`
	ProviderRef          string   `json:"provider_ref"`
	ProviderContractHash string   `json:"provider_contract_hash"`
	ModuleRef            string   `json:"module_ref"`
	ModuleContractHash   string   `json:"module_contract_hash"`
	UnitRef              string   `json:"unit_ref"`
	UnitContractHash     string   `json:"unit_contract_hash"`
	InstanceRef          string   `json:"instance_ref"`
	OutputRef            string   `json:"output_ref"`
	SiteRefs             []string `json:"site_refs"`
	NodeRefs             []string `json:"node_refs"`
	SHA256               string   `json:"sha256"`
	Content              []byte   `json:"content"`
}

func (a VerifiedApplyAuthorization) consume() (applyExecutionGrant, error) {
	return a.consumeWithClock(func() time.Time { return time.Now().UTC() })
}

func (a VerifiedApplyAuthorization) consumeAt(at time.Time) (applyExecutionGrant, error) {
	return a.consumeWithClock(func() time.Time { return at })
}

func (a VerifiedApplyAuthorization) consumeWithClock(now func() time.Time) (applyExecutionGrant, error) {
	if !a.authorized || a.owner == nil || a.state == nil || now == nil {
		return applyExecutionGrant{}, applyAuthorizationArtifactError(generationartifact.ErrInvalidContract, "apply.authorization", "valid one-shot Apply authorization is required", nil)
	}
	a.state.mu.Lock()
	if a.state.stage != applyAuthorizationIssued || a.state.workspace == nil || a.state.lockLease == nil {
		a.state.mu.Unlock()
		return applyExecutionGrant{}, applyAuthorizationArtifactError(generationartifact.ErrInvalidContract, "apply.authorization", "authorization is closed, consuming, or already consumed", nil)
	}
	var releaseCurrent func()
	closeInvalid := func(code generationartifact.ErrorCode, message string, cause error) (applyExecutionGrant, error) {
		if releaseCurrent != nil {
			releaseCurrent()
			releaseCurrent = nil
		}
		a.state.stage = applyAuthorizationClosed
		_ = a.state.lockLease.Close()
		a.state.lockLease = nil
		a.state.workspace = nil
		a.owner.revokeGenerationAuthorization(a.key, a.epoch)
		a.state.mu.Unlock()
		return applyExecutionGrant{}, applyAuthorizationArtifactError(code, "apply.authorization", message, cause)
	}
	if err := a.state.lockLease.Verify(a.state.workspace, a.plan.OutputRoot()); err != nil {
		return closeInvalid(generationartifact.ErrBindingMismatch, "held workspace or output lock no longer matches", err)
	}
	var ok bool
	releaseCurrent, ok = a.owner.acquireApplyAuthorization(a.key, a.epoch)
	if !ok {
		return closeInvalid(generationartifact.ErrBindingMismatch, "authorization was superseded or revoked", nil)
	}
	if err := RequireNoPendingOutputTransaction(a.state.workspace, a.plan.OutputRoot()); err != nil {
		return closeInvalid(generationartifact.ErrBindingMismatch, "governed output gained a pending transaction", err)
	}
	manifest, err := generationartifact.ReadManifestHeld(a.plan, a.state.workspace, ".")
	if err != nil {
		return closeInvalid(generationartifact.ErrArtifactChanged, "held generation manifest changed before consumption", err)
	}
	manifestHash, err := manifest.Hash()
	if err != nil || manifestHash != a.manifestHash {
		return closeInvalid(generationartifact.ErrArtifactChanged, "held generation manifest identity changed before consumption", err)
	}
	if err := generationartifact.VerifyManifestHeld(a.plan, a.state.workspace, ".", manifest); err != nil {
		return closeInvalid(generationartifact.ErrArtifactChanged, "held generated output changed before consumption", err)
	}
	receipt, err := generationartifact.ReadReceiptHeld(a.plan, a.state.workspace, ".")
	if err != nil {
		return closeInvalid(generationartifact.ErrArtifactChanged, "held generation receipt changed before consumption", err)
	}
	receiptHash, err := canonicalGenerationReceiptHash(receipt)
	if err != nil || receiptHash != a.receiptHash {
		return closeInvalid(generationartifact.ErrArtifactChanged, "held generation receipt identity changed before consumption", err)
	}
	if err := generationartifact.VerifyReceipt(a.plan, manifest, receipt); err != nil {
		return closeInvalid(generationartifact.ErrArtifactChanged, "held generation receipt no longer binds the output", err)
	}
	artifacts, err := snapshotHeldApplyArtifacts(a.state.workspace, manifest, a.plan.ApplyRequirements())
	if err != nil {
		return closeInvalid(generationartifact.ErrArtifactChanged, "capture immutable executor inputs from held generated output", err)
	}
	at := now()
	if at.IsZero() || at.Location() != time.UTC || !at.Before(a.expiresAt) {
		return closeInvalid(generationartifact.ErrEvidenceFreshness, "verified Apply evidence expired before consumption", nil)
	}
	resolved, err := resolvedplan.DecodeCanonicalPlan(a.plan.Canonical())
	if err != nil {
		return closeInvalid(generationartifact.ErrInvalidPlan, "verified plan could not be decoded at authorization consumption", err)
	}
	if err := resolvedplan.ValidateHostConformanceReceiptsForApply(resolved, at); err != nil {
		return closeInvalid(generationartifact.ErrEvidenceFreshness, "external Apply authority is not fresh at authorization consumption", err)
	}
	a.state.stage = applyAuthorizationConsuming
	var once sync.Once
	release := func() {
		once.Do(func() {
			a.state.stage = applyAuthorizationConsumed
			_ = a.state.lockLease.Close()
			a.state.lockLease = nil
			a.state.workspace = nil
			releaseCurrent()
			a.state.mu.Unlock()
		})
	}
	return applyExecutionGrant{
		plan: a.plan, artifacts: artifacts, manifestHash: a.manifestHash, receiptHash: a.receiptHash,
		requirementsHash: a.requirementsHash, bundleHash: a.bundleHash, executor: a.executor, release: release,
		evaluatedAt: at, expiresAt: a.expiresAt,
	}, nil
}

func snapshotHeldApplyArtifacts(workspace *confinedfs.Transaction, manifest generationartifact.ArtifactManifest, requirements generationartifact.ApplyRequirements) ([]applyArtifactSnapshot, error) {
	if workspace == nil {
		return nil, applyAuthorizationArtifactError(generationartifact.ErrInvalidContract, "apply.authorization.artifacts", "held workspace transaction is required", nil)
	}
	result := make([]applyArtifactSnapshot, 0, len(manifest.Artifacts))
	requirementsByID := make(map[string]generationartifact.ApplyArtifactRequirement, len(requirements.Artifacts))
	for _, requirement := range requirements.Artifacts {
		if _, duplicate := requirementsByID[requirement.ID]; duplicate {
			return nil, applyAuthorizationArtifactError(generationartifact.ErrInvalidContract, "apply.authorization.artifacts", "duplicate plan-owned artifact requirement", nil)
		}
		requirementsByID[requirement.ID] = requirement
	}
	for _, artifact := range manifest.Artifacts {
		requirement, exists := requirementsByID[artifact.ID]
		if !exists || requirement.Kind != artifact.Kind || requirement.Format != artifact.Format || requirement.Mode != artifact.Mode {
			return nil, applyAuthorizationArtifactError(generationartifact.ErrBindingMismatch, artifact.Path, "manifest artifact has no exact plan-owned Apply requirement", nil)
		}
		content, _, err := workspace.ReadStable(artifact.Path)
		if err != nil {
			return nil, err
		}
		digest := sha256.Sum256(content)
		actual := "sha256:" + hex.EncodeToString(digest[:])
		if actual != artifact.SHA256 {
			return nil, applyAuthorizationArtifactError(generationartifact.ErrArtifactChanged, artifact.Path, "artifact changed while immutable executor input was captured", nil)
		}
		result = append(result, applyArtifactSnapshot{
			ID: artifact.ID, Path: artifact.Path, Kind: artifact.Kind, Format: artifact.Format, Mode: artifact.Mode,
			ExecutionClass: requirement.ExecutionClass,
			OwnerKind:      requirement.OwnerKind, OwnerRef: requirement.OwnerRef, OwnerContractHash: requirement.OwnerContractHash, ProviderRef: requirement.ProviderRef,
			ProviderContractHash: requirement.ProviderContractHash, ModuleRef: requirement.ModuleRef, ModuleContractHash: requirement.ModuleContractHash,
			UnitRef: requirement.UnitRef, UnitContractHash: requirement.UnitContractHash, InstanceRef: requirement.InstanceRef, OutputRef: requirement.OutputRef,
			SiteRefs: append([]string(nil), requirement.SiteRefs...), NodeRefs: append([]string(nil), requirement.NodeRefs...),
			SHA256: artifact.SHA256, Content: append([]byte(nil), content...),
		})
		delete(requirementsByID, artifact.ID)
	}
	if len(requirementsByID) != 0 {
		return nil, applyAuthorizationArtifactError(generationartifact.ErrEvidenceSetMismatch, "apply.authorization.artifacts", "manifest is missing plan-owned Apply artifacts", nil)
	}
	return result, nil
}

// Close invalidates an unconsumed authorization or waits for the active
// package-owned consumer. It is idempotent across value copies.
func (a VerifiedApplyAuthorization) Close() error {
	if a.state == nil {
		return nil
	}
	a.state.mu.Lock()
	defer a.state.mu.Unlock()
	if a.state.stage == applyAuthorizationClosed {
		return nil
	}
	a.state.stage = applyAuthorizationClosed
	if a.state.lockLease != nil {
		if err := a.state.lockLease.Close(); err != nil {
			return applyAuthorizationArtifactError(generationartifact.ErrIO, "apply.authorization.outputLock", "close held output-lock lease", err)
		}
		a.state.lockLease = nil
	}
	a.state.workspace = nil
	if a.owner != nil {
		a.owner.revokeGenerationAuthorization(a.key, a.epoch)
	}
	return nil
}

func cloneApplyProducerTrust(input map[string]generationartifact.ApplyEvidenceProducerTrust) map[string]generationartifact.ApplyEvidenceProducerTrust {
	if len(input) == 0 {
		return nil
	}
	result := make(map[string]generationartifact.ApplyEvidenceProducerTrust, len(input))
	for key, trust := range input {
		trust.PublicKey = append([]byte(nil), trust.PublicKey...)
		trust.RequirementKinds = append([]string(nil), trust.RequirementKinds...)
		trust.ReceiptIDs = append([]string(nil), trust.ReceiptIDs...)
		result[key] = trust
	}
	return result
}

func canonicalGenerationReceiptHash(receipt generationartifact.GenerationReceipt) (string, error) {
	canonical, err := receipt.MarshalCanonical()
	if err != nil {
		return "", err
	}
	digest := sha256.Sum256(canonical)
	return "sha256:" + hex.EncodeToString(digest[:]), nil
}

func applyAuthorizationArtifactError(code generationartifact.ErrorCode, location, message string, err error) error {
	return &generationartifact.Error{Code: code, Path: location, Message: message, Err: err}
}

func (c *generationCoordinator) beginApplyAuthorization(key string, epoch uint64, binding generationartifact.PlanBinding) bool {
	slot := c.existingSlot(key)
	if slot == nil {
		return false
	}
	slot.mu.Lock()
	defer slot.mu.Unlock()
	state := slot.state
	if !slot.occupied || state.epoch != epoch || state.stage != generationStageIssued || state.binding != binding {
		return false
	}
	state.stage = generationStageApplyAuthorizing
	slot.state = state
	return true
}

func (c *generationCoordinator) finishApplyAuthorization(key string, epoch uint64, binding generationartifact.PlanBinding, authorized bool) bool {
	slot := c.existingSlot(key)
	if slot == nil {
		return false
	}
	slot.mu.Lock()
	defer slot.mu.Unlock()
	state := slot.state
	if !slot.occupied || state.epoch != epoch || state.stage != generationStageApplyAuthorizing || state.binding != binding {
		return false
	}
	if !authorized {
		slot.occupied = false
		slot.state = generationResolutionState{}
		return true
	}
	state.stage = generationStageApplyAuthorized
	slot.state = state
	return true
}

func (c *generationCoordinator) acquireApplyAuthorization(key string, epoch uint64) (func(), bool) {
	slot := c.existingSlot(key)
	if slot == nil {
		return nil, false
	}
	slot.mu.RLock()
	state := slot.state
	if !slot.occupied || state.epoch != epoch || state.stage != generationStageApplyAuthorized {
		slot.mu.RUnlock()
		return nil, false
	}
	return slot.mu.RUnlock, true
}
