package architecturev2

import (
	"bytes"
	"context"
	"errors"
	"time"

	"github.com/kombifyio/stackkits/internal/confinedfs"
	"github.com/kombifyio/stackkits/internal/generationartifact"
	"github.com/kombifyio/stackkits/internal/resolvedplan"
)

// ProductApplyReconcileInput identifies one service-owned recovery operation
// and supplies only the currently held filesystem capabilities. The caller
// cannot provide request bytes, evidence, an executor, or recovery authority.
type ProductApplyReconcileInput struct {
	Current       CurrentResolution
	Workspace     *confinedfs.Transaction
	OutputLock    *confinedfs.OutputLock
	Versions      generationartifact.ComponentVersions
	RequestDigest string
}

// ReconcileProductApply resumes one exact custody-bound Product Apply after a
// process restart. It revalidates the current plan and every generated byte
// under the held output lock before the service-owned registry may continue.
func (s *Service) ReconcileProductApply(ctx context.Context, input ProductApplyReconcileInput) (VerifiedApplyResult, error) {
	return s.reconcileProductApplyWithClock(ctx, input, func() time.Time { return time.Now().UTC() })
}

func (s *Service) reconcileProductApplyAt(ctx context.Context, input ProductApplyReconcileInput, at time.Time) (result VerifiedApplyResult, returnErr error) {
	return s.reconcileProductApplyWithClock(ctx, input, func() time.Time { return at })
}

func (s *Service) reconcileProductApplyWithClock(ctx context.Context, input ProductApplyReconcileInput, clock func() time.Time) (result VerifiedApplyResult, returnErr error) {
	if ctx == nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply reconcile context is required", nil)
	}
	if err := ctx.Err(); err != nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply reconcile context is already cancelled", err)
	}
	current := input.Current
	if s == nil || s.generation == nil || !current.valid || current.owner != s.generation {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply reconcile requires a current resolution issued by this product service", nil)
	}
	if s.productRuntimeOwners == nil || nilProductRuntimeOwnerValue(s.productRuntimeOwners.recovery) {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply reconcile requires service-owned recovery custody", nil)
	}
	if !validProductApplyDigest(input.RequestDigest) {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply reconcile requires a canonical request digest", nil)
	}
	if clock == nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply reconcile requires a clock", nil)
	}
	if !s.generation.beginApplyAuthorization(current.key, current.epoch, current.plan.Binding()) {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "current resolution is stale, superseded, or already consumed", nil)
	}
	coordinatorFinished := false
	defer func() {
		if !coordinatorFinished {
			s.generation.finishApplyAuthorization(current.key, current.epoch, current.plan.Binding(), false)
		}
	}()

	if input.Workspace == nil || input.OutputLock == nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "held workspace transaction and output lock are required", nil)
	}
	lease, err := input.OutputLock.Borrow(input.Workspace, current.plan.OutputRoot())
	if err != nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "borrow exact held output lock for Product Apply reconcile", err)
	}
	defer func() { returnErr = errors.Join(returnErr, lease.Close()) }()

	if err := current.plan.VerifyCompatibility(input.Versions); err != nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "current plan is incompatible with the participating components", err)
	}
	if err := current.plan.RequireReady(generationartifact.ExecutionPhaseApply); err != nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "current plan is not ready for Product Apply reconcile", err)
	}
	if input.Versions.Runtime != s.productRuntimeOwners.Identity().Version {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "runtime version does not match the service-owned recovery executor", nil)
	}

	capsule, err := s.loadProductApplyRecoveryCapsule(ctx, input.RequestDigest)
	if err != nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "load exact Product Apply recovery authority", err)
	}
	if err := validateProductApplyRecoveryPlan(current.plan, s.productRuntimeOwners, capsule); err != nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply recovery authority does not match the current plan", err)
	}
	if err := verifyProductApplyRecoveryWorkspace(current.plan, input.Workspace, capsule); err != nil {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply recovery workspace revalidation failed", err)
	}
	at := clock()
	if at.IsZero() || at.Location() != time.UTC {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply reconcile requires an exact UTC instant", nil)
	}
	validUntil, err := time.Parse(time.RFC3339Nano, capsule.ValidUntil)
	if err != nil || !at.Before(validUntil) {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "Product Apply recovery authority expired before execution", applyExecutorError(generationartifact.ErrEvidenceFreshness, "apply.reconcile.validUntil", "Product Apply recovery authority is expired", err))
	}

	if !s.generation.finishApplyAuthorization(current.key, current.epoch, current.plan.Binding(), true) {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "current resolution was superseded while Product Apply recovery was evaluated", nil)
	}
	coordinatorFinished = true
	releaseCurrent, ok := s.generation.acquireApplyAuthorization(current.key, current.epoch)
	if !ok {
		return VerifiedApplyResult{}, resolveError(ErrApplyAuthorization, "current resolution was superseded before Product Apply recovery execution", nil)
	}
	defer releaseCurrent()

	sharedResult, err := s.productRuntimeOwners.reconcileProductApply(ctx, input.RequestDigest, at)
	if err != nil {
		cause := applyExecutorError(generationartifact.ErrExecutorFailed, "apply.executor.reconcile", "Product Apply recovery execution failed", err)
		if reconcile := newProductApplyReconcileRequiredError(cause, input.RequestDigest); reconcile != nil {
			return VerifiedApplyResult{}, reconcile
		}
		return VerifiedApplyResult{}, cause
	}
	if err := ctx.Err(); err != nil {
		return VerifiedApplyResult{}, applyExecutorError(generationartifact.ErrExecutorFailed, "apply.executor.context", "execution context was cancelled during Product Apply recovery", err)
	}
	return verifyApplyRuntimeExecutionResult(capsule.Request, stackKitsExecutionResult(sharedResult))
}

func (s *Service) loadProductApplyRecoveryCapsule(ctx context.Context, requestDigest string) (productApplyRecoveryCapsule, error) {
	canonical, err := safeLoadProductApplyRecovery(s.productRuntimeOwners.recovery, ctx, requestDigest)
	if err != nil {
		return productApplyRecoveryCapsule{}, err
	}
	return parseProductApplyRecoveryCapsule(canonical)
}

func validateProductApplyRecoveryPlan(plan generationartifact.VerifiedPlan, owners *ProductRuntimeOwnerRegistry, capsule productApplyRecoveryCapsule) error {
	if len(capsule.Shared.AccessBindings) != 0 || len(capsule.Request.Requirements.AccessBindings) != 0 {
		return applyExecutorError(generationartifact.ErrEvidenceFreshness, "apply.reconcile.accessBindings", "access-bound Product Apply recovery requires a versioned fresh-instant continuation contract", nil)
	}
	if owners == nil || capsule.Shared.Executor != owners.Identity() ||
		capsule.Request.Executor.ID != owners.Identity().ID || capsule.Request.Executor.Version != owners.Identity().Version || capsule.Request.Executor.Digest != owners.Identity().Digest {
		return applyExecutorError(generationartifact.ErrBindingMismatch, "apply.reconcile.executor", "recovery authority does not bind the service-owned executor", nil)
	}
	requirementsEqual, err := canonicalProductApplyRecoveryEqual(capsule.Request.Requirements, plan.ApplyRequirements())
	if err != nil {
		return applyExecutorError(generationartifact.ErrInvalidContract, "apply.reconcile.plan", "canonicalize recovery requirements", err)
	}
	if capsule.Request.Binding != plan.Binding() || !requirementsEqual {
		return applyExecutorError(generationartifact.ErrBindingMismatch, "apply.reconcile.plan", "recovery authority does not bind the exact current plan and requirements", nil)
	}
	evidenceRequest, err := plan.ApplyEvidenceRequest()
	if err != nil {
		return err
	}
	if capsule.Request.RequirementsHash != evidenceRequest.RequirementsHash {
		return applyExecutorError(generationartifact.ErrBindingMismatch, "apply.reconcile.requirementsHash", "recovery authority requirements hash does not match the current plan", nil)
	}
	equalRoot, err := confinedfs.OutputLockRootsEqual(capsule.OutputRoot, plan.OutputRoot())
	if err != nil || !equalRoot {
		return applyExecutorError(generationartifact.ErrBindingMismatch, "apply.reconcile.outputRoot", "recovery authority does not bind the current output root", err)
	}
	return nil
}

func verifyProductApplyRecoveryWorkspace(plan generationartifact.VerifiedPlan, workspace *confinedfs.Transaction, capsule productApplyRecoveryCapsule) error {
	if err := RequireNoPendingOutputTransaction(workspace, plan.OutputRoot()); err != nil {
		return applyExecutorError(generationartifact.ErrBindingMismatch, "apply.reconcile.output", "governed output has a pending transaction", err)
	}
	manifest, err := generationartifact.ReadManifestHeld(plan, workspace, ".")
	if err != nil {
		return err
	}
	manifestHash, err := manifest.Hash()
	if err != nil || manifestHash != capsule.Request.ManifestHash {
		return applyExecutorError(generationartifact.ErrArtifactChanged, "apply.reconcile.manifest", "held generation manifest identity changed", err)
	}
	if err := generationartifact.VerifyManifestHeld(plan, workspace, ".", manifest); err != nil {
		return applyExecutorError(generationartifact.ErrArtifactChanged, "apply.reconcile.output", "held generated output changed", err)
	}
	receipt, err := generationartifact.ReadReceiptHeld(plan, workspace, ".")
	if err != nil {
		return err
	}
	receiptHash, err := canonicalGenerationReceiptHash(receipt)
	if err != nil || receiptHash != capsule.Request.GenerationReceiptHash {
		return applyExecutorError(generationartifact.ErrArtifactChanged, "apply.reconcile.receipt", "held generation receipt identity changed", err)
	}
	if err := generationartifact.VerifyReceipt(plan, manifest, receipt); err != nil {
		return applyExecutorError(generationartifact.ErrArtifactChanged, "apply.reconcile.receipt", "held generation receipt no longer binds the output", err)
	}
	artifacts, err := snapshotHeldApplyArtifacts(workspace, manifest, plan.ApplyRequirements())
	if err != nil {
		return err
	}
	artifactsEqual, err := canonicalProductApplyRecoveryEqual(
		map[string]any{"artifacts": artifacts},
		map[string]any{"artifacts": capsule.Request.Artifacts},
	)
	if err != nil {
		return applyExecutorError(generationartifact.ErrInvalidContract, "apply.reconcile.artifacts", "canonicalize recovery artifact snapshots", err)
	}
	if !artifactsEqual {
		return applyExecutorError(generationartifact.ErrArtifactChanged, "apply.reconcile.artifacts", "held artifact snapshots differ from the recovery authority", nil)
	}
	artifactSetHash, err := hashApplyArtifactSet(artifacts)
	if err != nil || artifactSetHash != capsule.Request.ArtifactSetHash {
		return applyExecutorError(generationartifact.ErrArtifactChanged, "apply.reconcile.artifactSetHash", "held artifact-set identity changed", err)
	}
	return nil
}

func canonicalProductApplyRecoveryEqual(first, second any) (bool, error) {
	firstCanonical, err := resolvedplan.CanonicalJSON(first)
	if err != nil {
		return false, err
	}
	secondCanonical, err := resolvedplan.CanonicalJSON(second)
	if err != nil {
		return false, err
	}
	return bytes.Equal(firstCanonical, secondCanonical), nil
}
