package localevidence

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"strings"
)

// lanDNSRecordsPath is the resolver zone file the Basement core mounts read-only
// into the lan-dns container.
const lanDNSRecordsPath = "lan-dns/a-records.conf"

// lanDNSDiscoveryTarget is a TEST-NET-1 address (RFC 5737). Dialling it on UDP
// creates no traffic — the kernel only selects the route — which is what makes
// this a local fact rather than a network call. Its single purpose is to learn
// which of the host's addresses the site is reachable on.
const lanDNSDiscoveryTarget = "192.0.2.1:9"

// ErrLANAddressUndiscoverable reports that the host has no usable site address.
// The resolver zone is not written from a guess: a wrong record would send every
// LAN client to the wrong host, which is worse than an install that stops and
// says so.
var ErrLANAddressUndiscoverable = errors.New("localevidence: no site-reachable host address for the LAN resolver")

// discoverSiteAddress returns the host address a device on the site network
// would reach this node at. It is an apply-time fact: no plan carries it,
// because generation happens off the target.
func discoverSiteAddress() (netip.Addr, error) {
	conn, err := net.Dial("udp", lanDNSDiscoveryTarget)
	if err != nil {
		return netip.Addr{}, fmt.Errorf("%w: %v", ErrLANAddressUndiscoverable, err)
	}
	defer func() { _ = conn.Close() }()

	local, ok := conn.LocalAddr().(*net.UDPAddr)
	if !ok || local == nil {
		return netip.Addr{}, ErrLANAddressUndiscoverable
	}
	address, ok := netip.AddrFromSlice(local.IP)
	if !ok {
		return netip.Addr{}, ErrLANAddressUndiscoverable
	}
	address = address.Unmap()
	// Loopback would make the zone answer correctly on the node and wrongly on
	// every other device, which is exactly the failure this resolver exists to
	// remove. Unspecified and multicast are never a host's own address.
	if !address.IsValid() || address.IsLoopback() || address.IsUnspecified() || address.IsMulticast() {
		return netip.Addr{}, ErrLANAddressUndiscoverable
	}
	return address, nil
}

// buildLANDNSRecords renders the Unbound zone that makes the site's own names
// answer on the LAN. The zone is a redirect, so every name under the domain
// resolves to the node running the router rather than requiring one record per
// service; services are added and removed by the router, not by DNS.
func buildLANDNSRecords(domain string, address netip.Addr) ([]byte, error) {
	if !validBasementRuntimeDomain(domain) {
		return nil, fmt.Errorf("localevidence: invalid Basement runtime domain %q for the LAN resolver", domain)
	}
	if !address.IsValid() || address.IsLoopback() || address.IsUnspecified() {
		return nil, ErrLANAddressUndiscoverable
	}
	recordType := "A"
	if address.Is6() {
		recordType = "AAAA"
	}
	var zone strings.Builder
	zone.WriteString("# Generated by StackKits Basement runtime custody. Do not edit.\n")
	zone.WriteString("server:\n")
	fmt.Fprintf(&zone, "  local-zone: %q redirect\n", domain+".")
	fmt.Fprintf(&zone, "  local-data: \"%s. IN %s %s\"\n", domain, recordType, address.String())
	return []byte(zone.String()), nil
}

// BasementLANDNSResolverAddress returns the exact address written into the
// owner-signed Unbound custody. Access summaries use this value so the owner
// does not have to discover or guess which node address to configure in DHCP.
func BasementLANDNSResolverAddress(workspaceRoot string) (string, error) {
	raw, custody, err := readBasementRuntimeFile(workspaceRoot, lanDNSRecordsPath)
	if err != nil {
		return "", err
	}
	address, err := parseLANDNSRecords(custody.Domain, raw)
	if err != nil {
		return "", err
	}
	return address.String(), nil
}

func parseLANDNSRecords(domain string, raw []byte) (netip.Addr, error) {
	lines := strings.Split(strings.TrimSuffix(string(raw), "\n"), "\n")
	if len(lines) != 4 {
		return netip.Addr{}, errors.New("localevidence: verified LAN DNS runtime input is malformed")
	}
	record := strings.TrimPrefix(strings.TrimSuffix(lines[3], `"`), `  local-data: "`)
	fields := strings.Fields(record)
	if len(fields) != 4 || fields[0] != domain+"." || fields[1] != "IN" {
		return netip.Addr{}, errors.New("localevidence: verified LAN DNS runtime record is malformed")
	}
	address, err := netip.ParseAddr(fields[3])
	if err != nil || (fields[2] == "A") != address.Is4() || (fields[2] == "AAAA") != address.Is6() {
		return netip.Addr{}, errors.New("localevidence: verified LAN DNS runtime address is malformed")
	}
	expected, err := buildLANDNSRecords(domain, address)
	if err != nil || !bytes.Equal(raw, expected) {
		return netip.Addr{}, errors.New("localevidence: verified LAN DNS runtime input does not match its canonical zone")
	}
	return address, nil
}
