// Package anythingllm — AnythingLLM module (scaffolded, draft).
//
// AnythingLLM chat alternative for owner-controlled private AI: workspaces with built-in RAG (LanceDB) and agents over the local Ollama. Models require an explicit owner download.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package anythingllm

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "anythingllm"
		displayName: "AnythingLLM"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "AnythingLLM chat alternative for owner-controlled private AI: workspaces with built-in RAG (LanceDB) and agents over the local Ollama. Models require an explicit owner download."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "1g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: anythingllm: foundation.#ServiceDefinition & {
		name:     "anythingllm"
		type:     "application"
		image:    "docker.io/mintplexlabs/anythingllm"
		tag:      "1.16.2@sha256:480b0f105efd6a4c8a4cde82713fe81348d75c979a24a38e9ed8e236bed0fd17"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`ai.{{.domain}}`)"
				port:    3001
			}
			networks: ["private-ai-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "self-auth"
		}

		upstream: {
			github: repo: "Mintplex-Labs/anything-llm"
			registry: image: "docker.io/mintplexlabs/anythingllm"
			track: "minor"
		}

		volumes: [
			{
				source: "anythingllm-storage"
				target: "/app/server/storage"
				type:   "volume"
				backup: true
			},
		]

		environment: {
			DISABLE_TELEMETRY:   "true"
			EMBEDDING_BASE_PATH: "http://ollama:11434"
			EMBEDDING_ENGINE:    "ollama"
			LLM_PROVIDER:        "ollama"
			OLLAMA_BASE_PATH:    "http://ollama:11434"
			SERVER_PORT:         "3001"
			STORAGE_DIR:         "/app/server/storage"
			VECTOR_DB:           "lancedb"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/api/ping"
				port:   3001
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "512m"
			memoryMax: "2g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "AnythingLLM dashboard"
	}
}
