// Package passbolt — Passbolt CE module (scaffolded, draft).
//
// Passbolt Community Edition: team password manager with end-to-end encryption and browser extensions, backed by MariaDB.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package passbolt

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "passbolt"
		displayName: "Passbolt CE"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Passbolt Community Edition: team password manager with end-to-end encryption and browser extensions, backed by MariaDB."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "512m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: {
		passbolt: foundation.#ServiceDefinition & {
			name:     "passbolt"
			type:     "application"
			image:    "docker.io/passbolt/passbolt"
			tag:      "5.16.0-1-ce"
			required: false
			status:   "implemented"

			network: {
				traefik: {
					enabled: true
					rule:    "Host(`vault.{{.domain}}`)"
					port:    80
				}
				networks: ["vault-internal"]
			}

			accessPolicy: {
				outerAuth:      "tinyauth-pocketid"
				appAuth:        "self-auth"
				ownerBootstrap: "Passbolt CE has no SSO (SSO is a Passbolt Pro feature): TinyAuth forward-auth (Pocket ID) guards the web app; Passbolt accounts keep their own keys."
			}

			upstream: {
				github: repo: "passbolt/passbolt_api"
				registry: image: "passbolt/passbolt"
				track: "minor"
			}

			volumes: [
				{
					source: "passbolt-gpg"
					target: "/etc/passbolt/gpg"
					type:   "volume"
					backup: true
				},
				{
					source: "passbolt-jwt"
					target: "/etc/passbolt/jwt"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/healthcheck/status.json"
					port:   80
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Passbolt CE dashboard"
		}
		mariadb: foundation.#ServiceDefinition & {
			name:     "mariadb"
			type:     "database"
			image:    "docker.io/library/mariadb"
			tag:      "11.8.3"
			required: false
			status:   "implemented"

			network: networks: ["vault-internal"]

			upstream: {
				github: repo: "MariaDB/server"
				registry: image: "mariadb"
				track: "minor"
			}

			volumes: [
				{
					source: "passbolt-db"
					target: "/var/lib/mysql"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled:  true
				command:  "healthcheck.sh --connect --innodb_initialized"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Passbolt CE database (internal)"
		}
	}
}
