// Package tika — Apache Tika module (scaffolded, draft).
//
// Apache Tika server (minimal image, no OCR) that extracts document text for Open WebUI; no route.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package tika

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "tika"
		displayName: "Apache Tika"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Apache Tika server (minimal image, no OCR) that extracts document text for Open WebUI; no route."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: false
		minMemory:         "512m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: tika: foundation.#ServiceDefinition & {
		name:     "tika"
		type:     "application"
		image:    "docker.io/apache/tika"
		tag:      "4.0.0-1@sha256:a8b442501f601fb15015de974f9afe13dd242b0f14e49a2b144fadcb214a555b"
		required: false
		status:   "implemented"

		network: networks: ["private-ai-internal"]

		upstream: {
			github: repo: "apache/tika-docker"
			registry: image: "docker.io/apache/tika"
			track: "minor"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/tika"
				port:   9998
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "512m"
			memoryMax: "2g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Apache Tika application (internal)"
	}
}
