// Package pterodactyl — Pterodactyl module (scaffolded, draft).
//
// Pterodactyl Panel and Wings upstream catalog. The native-v2 game workload owns executable configuration, owner bootstrap and the governed Wings lifecycle-owner approval (ADR-0043).
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package pterodactyl

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "pterodactyl"
		displayName: "Pterodactyl"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Pterodactyl Panel and Wings upstream catalog. The native-v2 game workload owns executable configuration, owner bootstrap and the governed Wings lifecycle-owner approval (ADR-0043)."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "1280m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: {
		panel: foundation.#ServiceDefinition & {
			name:     "panel"
			type:     "application"
			image:    "ghcr.io/pterodactyl/panel"
			tag:      "v1.15.1@sha256:bbf51a5501ff1492946816490d5275250570d3358124bad12c6b75f0077facf2"
			required: false
			status:   "implemented"

			network: {
				traefik: {
					enabled: true
					rule:    "Host(`game.{{.domain}}`)"
					port:    80
				}
				networks: ["game-internal"]
			}

			accessPolicy: {
				outerAuth: "self"
				appAuth:   "self-auth"
			}

			upstream: {
				github: repo: "pterodactyl/panel"
				registry: image: "ghcr.io/pterodactyl/panel"
				track: "minor"
			}

			volumes: [
				{
					source: "panel-var"
					target: "/app/var"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/auth/login"
					port:   80
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "384m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Pterodactyl dashboard"
		}
		"panel-database": foundation.#ServiceDefinition & {
			name:     "panel-database"
			type:     "database"
			image:    "docker.io/library/mariadb"
			tag:      "11.8@sha256:de4cf325ed1fc8a22460b4f285de7b9e06d89edbd593505e678ec480f86e501b"
			required: false
			status:   "implemented"

			network: networks: ["game-internal"]

			upstream: {
				github: repo: "MariaDB/mariadb-docker"
				registry: image: "docker.io/library/mariadb"
				track: "minor"
			}

			volumes: [
				{
					source: "panel-database-data"
					target: "/var/lib/mysql"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled:  true
				command:  "healthcheck.sh --connect --innodb_initialized"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "768m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Pterodactyl database (internal)"
		}
		"panel-cache": foundation.#ServiceDefinition & {
			name:     "panel-cache"
			type:     "cache"
			image:    "docker.io/valkey/valkey"
			tag:      "8.1-alpine@sha256:32627109abf6f741121096b45c732f758876803efd7b2e1018ebc0350d117119"
			required: false
			status:   "implemented"

			network: networks: ["game-internal"]

			upstream: {
				github: repo: "valkey-io/valkey"
				registry: image: "docker.io/valkey/valkey"
				track: "minor"
			}

			volumes: [
				{
					source: "panel-cache-data"
					target: "/data"
					type:   "volume"
					backup: false
				},
			]

			healthCheck: {
				enabled:  true
				command:  "valkey-cli ping"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "64m"
				memoryMax: "256m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Pterodactyl cache (internal)"
		}
		wings: foundation.#ServiceDefinition & {
			name:     "wings"
			type:     "application"
			image:    "ghcr.io/pterodactyl/wings"
			tag:      "v1.13.3@sha256:c89b9b9a48a992d8cfd488837bfd76426c2af07579699b4fe41f9e910701405c"
			required: false
			status:   "implemented"

			network: networks: ["game-internal"]

			upstream: {
				github: repo: "pterodactyl/wings"
				registry: image: "ghcr.io/pterodactyl/wings"
				track: "minor"
			}

			volumes: [
				{
					source: "wings-data"
					target: "/stackkit/game-data"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/api/system"
					port:   8080
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Pterodactyl application (internal)"
		}
	}
}
