// Package openhands — OpenHands module (scaffolded, draft).
//
// OpenHands Agent Canvas task and coding agent in one gVisor-isolated container with its own workspace; no host Docker socket, the node's Ollama as model endpoint, private route behind the kit login.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package openhands

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "openhands"
		displayName: "OpenHands"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "OpenHands Agent Canvas task and coding agent in one gVisor-isolated container with its own workspace; no host Docker socket, the node's Ollama as model endpoint, private route behind the kit login."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "1g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: openhands: foundation.#ServiceDefinition & {
		name:     "openhands"
		type:     "application"
		image:    "ghcr.io/openhands/agent-canvas"
		tag:      "1.24.0@sha256:ad0829a7082a71ddfd2d16c1fae5a2172e4ca5a34eba7f03b69bd5b9b1bc54d7"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`ai-harness.{{.domain}}`)"
				port:    8000
			}
			networks: ["private-ai-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "none"
			reason:    "OpenHands signs its own browser session in with the container's session key, so only the gateway login protects the private route."
		}

		upstream: {
			github: repo: "OpenHands/OpenHands"
			registry: image: "ghcr.io/openhands/agent-canvas"
			track: "minor"
		}

		environment: {
			DO_NOT_TRACK:      "1"
			VITE_DO_NOT_TRACK: "1"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/alive"
				port:   8000
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "1g"
			memoryMax: "6g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "OpenHands dashboard"
	}
}
