// Package paperless_ngx — Paperless-ngx module (scaffolded, draft).
//
// Paperless-ngx upstream application and dependency catalog. The native-v2 documents workload owns executable configuration and owner bootstrap.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package paperless_ngx

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "paperless-ngx"
		displayName: "Paperless-ngx"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Paperless-ngx upstream application and dependency catalog. The native-v2 documents workload owns executable configuration and owner bootstrap."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "1280m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: {
		paperless: foundation.#ServiceDefinition & {
			name:     "paperless"
			type:     "application"
			image:    "ghcr.io/paperless-ngx/paperless-ngx"
			tag:      "3.1.3@sha256:aa810a36942c63d4ee70d00eda7236cd3d6acfb7eb3f7987fb568ed14df8817a"
			required: false
			status:   "implemented"

			network: {
				traefik: {
					enabled: true
					rule:    "Host(`documents.{{.domain}}`)"
					port:    8000
				}
				networks: ["paperless-internal"]
			}

			accessPolicy: {
				outerAuth: "self"
				appAuth:   "self-auth"
			}

			upstream: {
				github: repo: "paperless-ngx/paperless-ngx"
				registry: image: "ghcr.io/paperless-ngx/paperless-ngx"
				track: "minor"
			}

			volumes: [
				{
					source: "paperless-data"
					target: "/usr/src/paperless/data"
					type:   "volume"
					backup: true
				},
				{
					source: "paperless-media"
					target: "/usr/src/paperless/media"
					type:   "volume"
					backup: true
				},
				{
					source: "paperless-consume"
					target: "/usr/src/paperless/consume"
					type:   "volume"
					backup: true
				},
				{
					source: "paperless-export"
					target: "/usr/src/paperless/export"
					type:   "volume"
					backup: false
				},
			]

			environment: {
				PAPERLESS_ADMIN_USER: "owner"
				PAPERLESS_DBENGINE:   "postgresql"
				PAPERLESS_DBHOST:     "paperless-postgres"
				PAPERLESS_DBNAME:     "paperless"
				PAPERLESS_DBUSER:     "paperless"
				PAPERLESS_REDIS:      "redis://paperless-valkey:6379"
			}

			healthCheck: {
				enabled: true
				http: {
					path:   "/"
					port:   8000
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "768m"
				memoryMax: "2g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Paperless-ngx dashboard"
		}
		"paperless-postgres": foundation.#ServiceDefinition & {
			name:     "paperless-postgres"
			type:     "database"
			image:    "docker.io/library/postgres"
			tag:      "18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280"
			required: false
			status:   "implemented"

			network: networks: ["paperless-internal"]

			upstream: {
				registry: image: "docker.io/library/postgres"
				track: "minor"
			}

			volumes: [
				{
					source: "paperless-postgres-data"
					target: "/var/lib/postgresql"
					type:   "volume"
					backup: true
				},
			]

			environment: {
				POSTGRES_DB:   "paperless"
				POSTGRES_USER: "paperless"
			}

			healthCheck: {
				enabled:  true
				command:  "pg_isready -U paperless -d paperless"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "384m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Paperless-ngx database (internal)"
		}
		"paperless-valkey": foundation.#ServiceDefinition & {
			name:     "paperless-valkey"
			type:     "cache"
			image:    "docker.io/valkey/valkey"
			tag:      "9-alpine@sha256:a0dbf4c1d5708782907c10e2c72deff317518518b5288a58416981d9db95d30b"
			required: false
			status:   "implemented"

			network: networks: ["paperless-internal"]

			upstream: {
				github: repo: "valkey-io/valkey"
				registry: image: "docker.io/valkey/valkey"
				track: "minor"
			}

			volumes: [
				{
					source: "paperless-valkey-data"
					target: "/data"
					type:   "volume"
					backup: false
				},
			]

			healthCheck: {
				enabled:  true
				command:  "valkey-cli ping"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Paperless-ngx cache (internal)"
		}
	}
}
