// Package paperclip — Paperclip module (scaffolded, draft).
//
// Paperclip agent control plane (org chart of agents, budgets, approvals, tasks) with its own PostgreSQL in one gVisor-isolated bundle; no host Docker socket, no egress, no provider key, private route behind the kit login and Paperclip's own login.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package paperclip

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "paperclip"
		displayName: "Paperclip"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Paperclip agent control plane (org chart of agents, budgets, approvals, tasks) with its own PostgreSQL in one gVisor-isolated bundle; no host Docker socket, no egress, no provider key, private route behind the kit login and Paperclip's own login."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "512m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: paperclip: foundation.#ServiceDefinition & {
		name:     "paperclip"
		type:     "application"
		image:    "ghcr.io/paperclipai/paperclip"
		tag:      "2026.916.1@sha256:a02ac35ac41df911af477422ea0e781cf41d2b2c600c66f0a5ac9d8c63f52c2c"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`ai-control-plane.{{.domain}}`)"
				port:    3100
			}
			networks: ["private-ai-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "self-auth"
			reason:    "Paperclip runs in authenticated mode (Better Auth); the first sign-up behind the gateway login becomes the instance admin."
		}

		upstream: {
			github: repo: "paperclipai/paperclip"
			registry: image: "ghcr.io/paperclipai/paperclip"
			track: "minor"
		}

		environment: {
			HOST:                          "0.0.0.0"
			PAPERCLIP_DEPLOYMENT_EXPOSURE: "private"
			PAPERCLIP_DEPLOYMENT_MODE:     "authenticated"
			PAPERCLIP_HOME:                "/paperclip"
			PORT:                          "3100"
			SERVE_UI:                      "true"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/api/health"
				port:   3100
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "512m"
			memoryMax: "4g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Paperclip dashboard"
	}
}
