// Package pelican — Pelican Panel module (scaffolded, draft).
//
// Pelican game server panel, the actively developed successor fork of Pterodactyl; runs game servers through Wings. Upstream is still in beta.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package pelican

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "pelican"
		displayName: "Pelican Panel"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Pelican game server panel, the actively developed successor fork of Pterodactyl; runs game servers through Wings. Upstream is still in beta."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "512m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: panel: foundation.#ServiceDefinition & {
		name:     "panel"
		type:     "application"
		image:    "ghcr.io/pelican/panel"
		tag:      "v1.0.0-beta38"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`game.{{.domain}}`)"
				port:    80
			}
			networks: ["game-internal"]
		}

		accessPolicy: {
			outerAuth:      "self"
			appAuth:        "oidc-sso"
			ownerBootstrap: "Pelican signs in through the first-party generic-oidc-providers plugin: register Pelican as an OIDC client in Pocket ID with issuer https://id.{{.domain}}."
		}

		upstream: {
			github: repo: "pelican-dev/panel"
			registry: image: "ghcr.io/pelican/panel"
			track: "minor"
		}

		volumes: [
			{
				source: "pelican-data"
				target: "/pelican-data"
				type:   "volume"
				backup: true
			},
			{
				source: "pelican-logs"
				target: "/var/www/html/storage/logs"
				type:   "volume"
				backup: false
			},
		]

		healthCheck: {
			enabled: true
			http: {
				path:   "/up"
				port:   80
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "256m"
			memoryMax: "1g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Pelican Panel dashboard"
	}
}
