// Package pelican — Pelican Panel module (scaffolded, draft).
//
// Pelican Panel and Wings upstream catalog (upstream beta), a Game platform alternative. The native-v2 game workload owns executable configuration, owner bootstrap and the governed Wings lifecycle-owner approval (ADR-0043, ADR-0048).
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package pelican

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "pelican"
		displayName: "Pelican Panel"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Pelican Panel and Wings upstream catalog (upstream beta), a Game platform alternative. The native-v2 game workload owns executable configuration, owner bootstrap and the governed Wings lifecycle-owner approval (ADR-0043, ADR-0048)."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "768m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: {
		panel: foundation.#ServiceDefinition & {
			name:     "panel"
			type:     "application"
			image:    "ghcr.io/pelican/panel"
			tag:      "v1.0.0-beta38@sha256:46f356f3fda423b1d43f0dc3c71efc056cd8b9bec365d1d7817306a17ee5694a"
			required: false
			status:   "implemented"

			network: {
				traefik: {
					enabled: true
					rule:    "Host(`game.{{.domain}}`)"
					port:    80
				}
				networks: ["game-internal"]
			}

			accessPolicy: {
				outerAuth: "self"
				appAuth:   "self-auth"
			}

			upstream: {
				github: repo: "pelican-dev/panel"
				registry: image: "ghcr.io/pelican/panel"
				track: "minor"
			}

			volumes: [
				{
					source: "pelican-data"
					target: "/pelican-data"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/up"
					port:   80
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Pelican Panel dashboard"
		}
		wings: foundation.#ServiceDefinition & {
			name:     "wings"
			type:     "application"
			image:    "ghcr.io/pelican/wings"
			tag:      "v1.0.0-beta29@sha256:39837cfc49b0513313e57dc4b977a769cb784cf81af3f25a5ea46d869b4b0846"
			required: false
			status:   "implemented"

			network: networks: ["game-internal"]

			upstream: {
				github: repo: "pelican-dev/wings"
				registry: image: "ghcr.io/pelican/wings"
				track: "minor"
			}

			volumes: [
				{
					source: "wings-data"
					target: "/stackkit/game-data"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/api/system"
					port:   8080
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Pelican Panel application (internal)"
		}
	}
}
