// Package ente_photos — Ente Photos module (scaffolded, draft).
//
// End-to-end encrypted photo library: Ente museum API server, Ente web apps and PostgreSQL. Needs an S3-compatible bucket for photo objects.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package ente_photos

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "ente-photos"
		displayName: "Ente Photos"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "End-to-end encrypted photo library: Ente museum API server, Ente web apps and PostgreSQL. Needs an S3-compatible bucket for photo objects."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "1g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: {
		museum: foundation.#ServiceDefinition & {
			name:     "museum"
			type:     "application"
			image:    "ghcr.io/ente/server"
			tag:      "163f45c26f130090abed03649530f53d2d976565"
			required: false
			status:   "implemented"

			network: {
				traefik: {
					enabled: true
					rule:    "Host(`photos-api.{{.domain}}`)"
					port:    8080
				}
				networks: ["ente-internal"]
			}

			accessPolicy: {
				outerAuth:      "tinyauth-pocketid"
				appAuth:        "self-auth"
				ownerBootstrap: "Ente has no OIDC or proxy-header login: TinyAuth forward-auth (Pocket ID) guards the web app and API; Ente accounts stay app-local because they hold the end-to-end encryption keys."
			}

			upstream: {
				github: repo: "ente-io/ente"
				registry: image: "ghcr.io/ente/server"
				track: "minor"
			}

			volumes: [
				{
					source: "ente-museum-data"
					target: "/data"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/ping"
					port:   8080
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Ente Photos dashboard"
		}
		web: foundation.#ServiceDefinition & {
			name:     "web"
			type:     "application"
			image:    "ghcr.io/ente/web"
			tag:      "1a623f325ad9b6ba68e23c1298eb6cf4486f27c8"
			required: false
			status:   "implemented"

			network: {
				traefik: {
					enabled: true
					rule:    "Host(`photos.{{.domain}}`)"
					port:    3000
				}
				networks: ["ente-internal"]
			}

			accessPolicy: {
				outerAuth:      "tinyauth-pocketid"
				appAuth:        "self-auth"
				ownerBootstrap: "Ente web app behind TinyAuth forward-auth (Pocket ID); Ente accounts stay app-local."
			}

			upstream: {
				github: repo: "ente-io/ente"
				registry: image: "ghcr.io/ente/web"
				track: "minor"
			}

			healthCheck: {
				enabled: true
				http: {
					path:   "/"
					port:   3000
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Ente Photos dashboard"
		}
		postgres: foundation.#ServiceDefinition & {
			name:     "postgres"
			type:     "database"
			image:    "docker.io/library/postgres"
			tag:      "17.6-alpine"
			required: false
			status:   "implemented"

			network: networks: ["ente-internal"]

			upstream: {
				github: repo: "postgres/postgres"
				registry: image: "postgres"
				track: "minor"
			}

			volumes: [
				{
					source: "ente-postgres"
					target: "/var/lib/postgresql/data"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled:  true
				command:  "pg_isready -U pguser -d ente_db"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Ente Photos database (internal)"
		}
	}
}
