// Package mailcow — mailcow module (scaffolded, draft).
//
// mailcow: dockerized complete mail suite (Postfix, Dovecot, Rspamd, SOGo webmail/groupware) for your own domain. Core mail path services only; mailcow's own installer owns the full stack.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package mailcow

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "mailcow"
		displayName: "mailcow"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "mailcow: dockerized complete mail suite (Postfix, Dovecot, Rspamd, SOGo webmail/groupware) for your own domain. Core mail path services only; mailcow's own installer owns the full stack."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "6g"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: {
		"nginx-mailcow": foundation.#ServiceDefinition & {
			name:     "nginx-mailcow"
			type:     "application"
			image:    "ghcr.io/mailcow/nginx"
			tag:      "1.30.4-1"
			required: false
			status:   "implemented"

			network: {
				traefik: {
					enabled: true
					rule:    "Host(`mail.{{.domain}}`)"
					port:    8080
				}
				networks: ["mailcow-internal"]
			}

			accessPolicy: {
				outerAuth:      "self"
				appAuth:        "oidc-sso"
				ownerBootstrap: "mailcow signs in mailboxes through its Generic-OIDC identity provider: register mailcow as an OIDC client in Pocket ID (issuer https://id.{{.domain}}) under System > Configuration > Access > Identity Provider."
			}

			upstream: {
				github: repo: "mailcow/mailcow-dockerized"
				registry: image: "ghcr.io/mailcow/nginx"
				track: "minor"
			}

			healthCheck: {
				enabled: true
				http: {
					path:   "/"
					port:   8080
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "64m"
				memoryMax: "256m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "mailcow dashboard"
		}
		"postfix-mailcow": foundation.#ServiceDefinition & {
			name:     "postfix-mailcow"
			type:     "application"
			image:    "ghcr.io/mailcow/postfix"
			tag:      "3.10.12-1"
			required: false
			status:   "implemented"

			network: networks: ["mailcow-internal"]

			upstream: {
				github: repo: "mailcow/mailcow-dockerized"
				registry: image: "ghcr.io/mailcow/postfix"
				track: "minor"
			}

			volumes: [
				{
					source: "mailcow-postfix"
					target: "/var/spool/postfix"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled:  true
				command:  "postfix status"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "mailcow application (internal)"
		}
		"dovecot-mailcow": foundation.#ServiceDefinition & {
			name:     "dovecot-mailcow"
			type:     "application"
			image:    "ghcr.io/mailcow/dovecot"
			tag:      "2.3.21.1-2"
			required: false
			status:   "implemented"

			network: networks: ["mailcow-internal"]

			upstream: {
				github: repo: "mailcow/mailcow-dockerized"
				registry: image: "ghcr.io/mailcow/dovecot"
				track: "minor"
			}

			volumes: [
				{
					source: "mailcow-vmail"
					target: "/var/vmail"
					type:   "volume"
					backup: true
				},
				{
					source: "mailcow-vmail-index"
					target: "/var/vmail_index"
					type:   "volume"
					backup: false
				},
			]

			healthCheck: {
				enabled:  true
				command:  "doveadm service status"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "mailcow application (internal)"
		}
		"rspamd-mailcow": foundation.#ServiceDefinition & {
			name:     "rspamd-mailcow"
			type:     "application"
			image:    "ghcr.io/mailcow/rspamd"
			tag:      "4.1.4-1"
			required: false
			status:   "implemented"

			network: networks: ["mailcow-internal"]

			upstream: {
				github: repo: "mailcow/mailcow-dockerized"
				registry: image: "ghcr.io/mailcow/rspamd"
				track: "minor"
			}

			volumes: [
				{
					source: "mailcow-rspamd"
					target: "/var/lib/rspamd"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/ping"
					port:   11334
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "mailcow application (internal)"
		}
		"sogo-mailcow": foundation.#ServiceDefinition & {
			name:     "sogo-mailcow"
			type:     "application"
			image:    "ghcr.io/mailcow/sogo"
			tag:      "5.12.11-1"
			required: false
			status:   "implemented"

			network: networks: ["mailcow-internal"]

			upstream: {
				github: repo: "mailcow/mailcow-dockerized"
				registry: image: "ghcr.io/mailcow/sogo"
				track: "minor"
			}

			healthCheck: {
				enabled: true
				http: {
					path:   "/SOGo"
					port:   20000
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "mailcow application (internal)"
		}
		"php-fpm-mailcow": foundation.#ServiceDefinition & {
			name:     "php-fpm-mailcow"
			type:     "application"
			image:    "ghcr.io/mailcow/phpfpm"
			tag:      "8.2.29-3"
			required: false
			status:   "implemented"

			network: networks: ["mailcow-internal"]

			upstream: {
				github: repo: "mailcow/mailcow-dockerized"
				registry: image: "ghcr.io/mailcow/phpfpm"
				track: "minor"
			}

			healthCheck: {
				enabled:  true
				command:  "php-fpm -t"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "mailcow application (internal)"
		}
		"mysql-mailcow": foundation.#ServiceDefinition & {
			name:     "mysql-mailcow"
			type:     "database"
			image:    "docker.io/library/mariadb"
			tag:      "10.11"
			required: false
			status:   "implemented"

			network: networks: ["mailcow-internal"]

			upstream: {
				github: repo: "MariaDB/server"
				registry: image: "mariadb"
				track: "minor"
			}

			volumes: [
				{
					source: "mailcow-mysql"
					target: "/var/lib/mysql"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled:  true
				command:  "healthcheck.sh --connect --innodb_initialized"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "256m"
				memoryMax: "1g"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "mailcow database (internal)"
		}
		"redis-mailcow": foundation.#ServiceDefinition & {
			name:     "redis-mailcow"
			type:     "database"
			image:    "docker.io/library/redis"
			tag:      "7.4.11-alpine"
			required: false
			status:   "implemented"

			network: networks: ["mailcow-internal"]

			upstream: {
				github: repo: "redis/redis"
				registry: image: "redis"
				track: "minor"
			}

			volumes: [
				{
					source: "mailcow-redis"
					target: "/data"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled:  true
				command:  "redis-cli ping"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "64m"
				memoryMax: "256m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "mailcow database (internal)"
		}
	}
}
