// Code generated by stackactiongen; DO NOT EDIT.
// Source: base/stack_action.cue
// Contract SHA-256: c7e4042ee1032a8febf9e2f7287fd1f7373e4d6c9bdba8300af78523317ee5a1

package stackaction

import (
	"strings"
	"time"
)

const (
	// WireVersion identifies the generated StackAction wire contract.
	WireVersion = "stackkit.stack-action/v1"
	// TargetStackKits identifies StackKits as the action target.
	TargetStackKits = "stackkits"
	// PathPrefix is the canonical internal StackAction transport prefix.
	PathPrefix = "/api/v1/internal/stack-actions"
	// ObservationVersionV1 identifies the generated observation envelope.
	ObservationVersionV1 = "stackkit.runtime-observation/v1"
	// PathStackKitRollout is the canonical path for the "stackkit_rollout" action.
	PathStackKitRollout = PathPrefix + "/stackkit-rollout"
	// PathStackKitVerify is the canonical path for the "verify_rollout" action.
	PathStackKitVerify = PathPrefix + "/stackkit-verify"
	// PathRestoreDrill is the canonical path for the "restore_drill" action.
	PathRestoreDrill = PathPrefix + "/restore-drill"
	// PathBackupRun is the canonical path for the "backup_run" action.
	PathBackupRun = PathPrefix + "/backup-run"
	// PathBackupStatus is the canonical path for the "backup_status" action.
	PathBackupStatus = PathPrefix + "/backup-status"
	// PathBackupRestore is the canonical path for the "backup_restore" action.
	PathBackupRestore = PathPrefix + "/backup-restore"
	// PathBackupWipe is the canonical path for the "backup_wipe" action.
	PathBackupWipe = PathPrefix + "/backup-wipe"
)

// Action is a closed StackAction wire vocabulary.
type Action string

const (
	// ActionStackKitRollout represents the "stackkit_rollout" wire value.
	ActionStackKitRollout Action = "stackkit_rollout"
	// ActionVerifyRollout represents the "verify_rollout" wire value.
	ActionVerifyRollout Action = "verify_rollout"
	// ActionRestoreDrill represents the "restore_drill" wire value.
	ActionRestoreDrill Action = "restore_drill"
	// ActionBackupRun represents the "backup_run" wire value.
	ActionBackupRun Action = "backup_run"
	// ActionBackupStatus represents the "backup_status" wire value.
	ActionBackupStatus Action = "backup_status"
	// ActionBackupRestore represents the "backup_restore" wire value.
	ActionBackupRestore Action = "backup_restore"
	// ActionBackupWipe represents the "backup_wipe" wire value.
	ActionBackupWipe Action = "backup_wipe"
)

// Mode is a closed StackAction wire vocabulary.
type Mode string

const (
	// ModeDryRun represents the "dry-run" wire value.
	ModeDryRun Mode = "dry-run"
	// ModeApply represents the "apply" wire value.
	ModeApply Mode = "apply"
)

// Status is a closed StackAction wire vocabulary.
type Status string

const (
	// StatusAccepted represents the "accepted" wire value.
	StatusAccepted Status = "accepted"
	// StatusReady represents the "ready" wire value.
	StatusReady Status = "ready"
	// StatusApplied represents the "applied" wire value.
	StatusApplied Status = "applied"
	// StatusVerified represents the "verified" wire value.
	StatusVerified Status = "verified"
	// StatusSkipped represents the "skipped" wire value.
	StatusSkipped Status = "skipped"
	// StatusFailed represents the "failed" wire value.
	StatusFailed Status = "failed"
)

// CheckStatus is a closed StackAction wire vocabulary.
type CheckStatus string

const (
	// CheckStatusOK represents the "ok" wire value.
	CheckStatusOK CheckStatus = "ok"
	// CheckStatusWarning represents the "warning" wire value.
	CheckStatusWarning CheckStatus = "warning"
	// CheckStatusMissing represents the "missing" wire value.
	CheckStatusMissing CheckStatus = "missing"
	// CheckStatusReference represents the "reference" wire value.
	CheckStatusReference CheckStatus = "reference"
	// CheckStatusSkipped represents the "skipped" wire value.
	CheckStatusSkipped CheckStatus = "skipped"
	// CheckStatusFailed represents the "failed" wire value.
	CheckStatusFailed CheckStatus = "failed"
)

// ServiceHealthStatus is a closed StackAction wire vocabulary.
type ServiceHealthStatus string

const (
	// ServiceHealthStarting represents the "starting" wire value.
	ServiceHealthStarting ServiceHealthStatus = "starting"
	// ServiceHealthHealthy represents the "healthy" wire value.
	ServiceHealthHealthy ServiceHealthStatus = "healthy"
	// ServiceHealthUnhealthy represents the "unhealthy" wire value.
	ServiceHealthUnhealthy ServiceHealthStatus = "unhealthy"
	// ServiceHealthUnknown represents the "unknown" wire value.
	ServiceHealthUnknown ServiceHealthStatus = "unknown"
)

// SupplementalNodeRole is a closed StackAction wire vocabulary.
type SupplementalNodeRole string

const (
	// SupplementalNodeRoleWorker represents the "worker" wire value.
	SupplementalNodeRoleWorker SupplementalNodeRole = "worker"
	// SupplementalNodeRoleStorage represents the "storage" wire value.
	SupplementalNodeRoleStorage SupplementalNodeRole = "storage"
)

// PlatformManagement is a closed StackAction wire vocabulary.
type PlatformManagement string

const (
	// PlatformManagementManaged represents the "managed" wire value.
	PlatformManagementManaged PlatformManagement = "managed"
	// PlatformManagementHandoff represents the "handoff" wire value.
	PlatformManagementHandoff PlatformManagement = "handoff"
	// PlatformManagementUnmanaged represents the "unmanaged" wire value.
	PlatformManagementUnmanaged PlatformManagement = "unmanaged"
	// PlatformManagementFallback represents the "fallback" wire value.
	PlatformManagementFallback PlatformManagement = "fallback"
)

// SetupPolicy is a closed StackAction wire vocabulary.
type SetupPolicy string

const (
	// SetupPolicyManual represents the "manual" wire value.
	SetupPolicyManual SetupPolicy = "manual"
	// SetupPolicyOnDemand represents the "on_demand" wire value.
	SetupPolicyOnDemand SetupPolicy = "on_demand"
	// SetupPolicyAutomatic represents the "automatic" wire value.
	SetupPolicyAutomatic SetupPolicy = "automatic"
)

// ContainerHealth is a closed StackAction wire vocabulary.
type ContainerHealth string

const (
	// ContainerHealthHealthy represents the "healthy" wire value.
	ContainerHealthHealthy ContainerHealth = "healthy"
	// ContainerHealthUnhealthy represents the "unhealthy" wire value.
	ContainerHealthUnhealthy ContainerHealth = "unhealthy"
	// ContainerHealthStarting represents the "starting" wire value.
	ContainerHealthStarting ContainerHealth = "starting"
	// ContainerHealthNone represents the "none" wire value.
	ContainerHealthNone ContainerHealth = "none"
	// ContainerHealthUnknown represents the "unknown" wire value.
	ContainerHealthUnknown ContainerHealth = "unknown"
)

// ScopedReference is opaque versioned reference whose scope and expiry are revalidated by internal custody.
type ScopedReference struct {
	// Ref maps the "ref" wire field.
	Ref string `json:"ref"`
	// Version maps the "version" wire field.
	Version string `json:"version"`
	// Scopes maps the "scopes" wire field.
	Scopes []string `json:"scopes"`
	// ExpiresAt maps the "expires_at" wire field.
	ExpiresAt time.Time `json:"expires_at"`
}

// TechStackEnrollment is generation-bound managed runtime enrollment and callback channels.
type TechStackEnrollment struct {
	// TenantID maps the "tenant_id" wire field.
	TenantID string `json:"tenant_id,omitempty"`
	// OwnerID maps the "owner_id" wire field.
	OwnerID string `json:"owner_id,omitempty"`
	// StackID maps the "stack_id" wire field.
	StackID string `json:"stack_id,omitempty"`
	// LeaseID maps the "lease_id" wire field.
	LeaseID string `json:"lease_id"`
	// ServerURL maps the "server_url" wire field.
	ServerURL string `json:"server_url"`
	// ServerID maps the "server_id" wire field.
	ServerID string `json:"server_id"`
	// RuntimeAgentID maps the "runtime_agent_id" wire field.
	RuntimeAgentID string `json:"runtime_agent_id"`
	// EnrollmentAccessRef maps the "enrollment_access_ref" wire field.
	EnrollmentAccessRef *ScopedReference `json:"enrollment_access_ref"`
	// HeartbeatURL maps the "heartbeat_url" wire field.
	HeartbeatURL string `json:"heartbeat_url,omitempty"`
	// InventoryURL maps the "inventory_url" wire field.
	InventoryURL string `json:"inventory_url,omitempty"`
	// ControlURLs maps the "control_urls" wire field.
	ControlURLs []string `json:"control_urls,omitempty"`
}

// RuntimeTarget is primary runtime host with an opaque access-profile reference.
type RuntimeTarget struct {
	// Host maps the "host" wire field.
	Host string `json:"host,omitempty"`
	// PublicIP maps the "public_ip" wire field.
	PublicIP string `json:"public_ip,omitempty"`
	// PrivateIP maps the "private_ip" wire field.
	PrivateIP string `json:"private_ip,omitempty"`
	// User maps the "user" wire field.
	User string `json:"user,omitempty"`
	// Port maps the "port" wire field.
	Port int `json:"port,omitempty"`
	// DockerHost maps the "docker_host" wire field.
	DockerHost string `json:"docker_host,omitempty"`
	// AccessProfileRef maps the "access_profile_ref" wire field.
	AccessProfileRef *ScopedReference `json:"access_profile_ref"`
}

// NodePlatformTarget is observed platform placement identity; values are never synthesized.
type NodePlatformTarget struct {
	// ServerID maps the "server_id" wire field.
	ServerID string `json:"server_id,omitempty"`
	// DestinationUUID maps the "destination_uuid" wire field.
	DestinationUUID string `json:"destination_uuid,omitempty"`
	// EnvironmentID maps the "environment_id" wire field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// ProjectUUID maps the "project_uuid" wire field.
	ProjectUUID string `json:"project_uuid,omitempty"`
	// EnvironmentUUID maps the "environment_uuid" wire field.
	EnvironmentUUID string `json:"environment_uuid,omitempty"`
}

// SSHBootstrap is supplemental-node SSH endpoint with an opaque access-profile reference.
type SSHBootstrap struct {
	// Host maps the "host" wire field.
	Host string `json:"host"`
	// User maps the "user" wire field.
	User string `json:"user,omitempty"`
	// Port maps the "port" wire field.
	Port int `json:"port,omitempty"`
	// AccessProfileRef maps the "access_profile_ref" wire field.
	AccessProfileRef *ScopedReference `json:"access_profile_ref"`
	// ProxyJump maps the "proxy_jump" wire field.
	ProxyJump string `json:"proxy_jump,omitempty"`
}

// NodeBootstrap is platform-specific supplemental-node bootstrap.
type NodeBootstrap struct {
	// KomodoCoreAddress maps the "komodo_core_address" wire field.
	KomodoCoreAddress string `json:"komodo_core_address"`
	// OnboardingRef maps the "onboarding_ref" wire field.
	OnboardingRef *ScopedReference `json:"onboarding_ref"`
	// SSH maps the "ssh" wire field.
	SSH *SSHBootstrap `json:"ssh"`
}

// PlatformNode is supplemental worker or storage node.
type PlatformNode struct {
	// Name maps the "name" wire field.
	Name string `json:"name"`
	// Role maps the "role" wire field.
	Role string `json:"role,omitempty"`
	// IP maps the "ip" wire field.
	IP string `json:"ip,omitempty"`
	// Host maps the "host" wire field.
	Host string `json:"host,omitempty"`
	// Services maps the "services" wire field.
	Services []string `json:"services,omitempty"`
	// Platform maps the "platform" wire field.
	Platform NodePlatformTarget `json:"platform,omitempty"`
	// Bootstrap maps the "bootstrap" wire field.
	Bootstrap *NodeBootstrap `json:"bootstrap,omitempty"`
}

// BackupRepoTarget is backup repository target with an opaque credential reference.
type BackupRepoTarget struct {
	// Type maps the "type" wire field.
	Type string `json:"type,omitempty"`
	// Endpoint maps the "endpoint" wire field.
	Endpoint string `json:"endpoint,omitempty"`
	// Bucket maps the "bucket" wire field.
	Bucket string `json:"bucket,omitempty"`
	// Region maps the "region" wire field.
	Region string `json:"region,omitempty"`
	// Prefix maps the "prefix" wire field.
	Prefix string `json:"prefix,omitempty"`
	// CredentialRef maps the "credential_ref" wire field.
	CredentialRef *ScopedReference `json:"credential_ref,omitempty"`
}

// BackupRequest is backup action parameters containing no credential material.
type BackupRequest struct {
	// Classes maps the "classes" wire field.
	Classes []string `json:"classes,omitempty"`
	// SnapshotID maps the "snapshot_id" wire field.
	SnapshotID string `json:"snapshot_id,omitempty"`
	// Repo maps the "repo" wire field.
	Repo *BackupRepoTarget `json:"repo,omitempty"`
	// Confirm maps the "confirm" wire field.
	Confirm string `json:"confirm,omitempty"`
}

// BackupSnapshot is one observed backup snapshot.
type BackupSnapshot struct {
	// ID maps the "id" wire field.
	ID string `json:"id,omitempty"`
	// Source maps the "source" wire field.
	Source string `json:"source,omitempty"`
	// Classes maps the "classes" wire field.
	Classes []string `json:"classes,omitempty"`
	// StartedAt maps the "started_at" wire field.
	StartedAt string `json:"started_at,omitempty"`
	// FinishedAt maps the "finished_at" wire field.
	FinishedAt string `json:"finished_at,omitempty"`
	// TotalBytes maps the "total_bytes" wire field.
	TotalBytes int64 `json:"total_bytes,omitempty"`
}

// BackupResult is backup engine state and snapshots.
type BackupResult struct {
	// Engine maps the "engine" wire field.
	Engine string `json:"engine,omitempty"`
	// Phase maps the "phase" wire field.
	Phase string `json:"phase,omitempty"`
	// Classes maps the "classes" wire field.
	Classes []string `json:"classes,omitempty"`
	// Snapshots maps the "snapshots" wire field.
	Snapshots []BackupSnapshot `json:"snapshots,omitempty"`
	// RepoSizeBytes maps the "repo_size_bytes" wire field.
	RepoSizeBytes int64 `json:"repo_size_bytes,omitempty"`
	// Wiped maps the "wiped" wire field.
	Wiped bool `json:"wiped,omitempty"`
}

// Check is one named action check.
type Check struct {
	// Name maps the "name" wire field.
	Name string `json:"name"`
	// Status maps the "status" wire field.
	Status CheckStatus `json:"status"`
	// Detail maps the "detail" wire field.
	Detail string `json:"detail,omitempty"`
}

// HostObservation is measured host and Docker reachability.
type HostObservation struct {
	// Host maps the "host" wire field.
	Host string `json:"host,omitempty"`
	// Reachable maps the "reachable" wire field.
	Reachable bool `json:"reachable"`
	// DockerReachable maps the "docker_reachable" wire field.
	DockerReachable bool `json:"docker_reachable"`
	// FailureClass maps the "failure_class" wire field.
	FailureClass string `json:"failure_class,omitempty"`
}

// PlatformObservation is observed selected-PaaS identity.
type PlatformObservation struct {
	// Name maps the "name" wire field.
	Name string `json:"name,omitempty"`
	// Endpoint maps the "endpoint" wire field.
	Endpoint string `json:"endpoint,omitempty"`
	// ServerID maps the "server_id" wire field.
	ServerID string `json:"server_id,omitempty"`
	// ProjectUUID maps the "project_uuid" wire field.
	ProjectUUID string `json:"project_uuid,omitempty"`
	// EnvironmentUUID maps the "environment_uuid" wire field.
	EnvironmentUUID string `json:"environment_uuid,omitempty"`
	// DestinationUUID maps the "destination_uuid" wire field.
	DestinationUUID string `json:"destination_uuid,omitempty"`
}

// ContainerObservation is measured Docker container state.
type ContainerObservation struct {
	// ID maps the "id" wire field.
	ID string `json:"id,omitempty"`
	// Name maps the "name" wire field.
	Name string `json:"name,omitempty"`
	// State maps the "state" wire field.
	State string `json:"state,omitempty"`
	// Running maps the "running" wire field.
	Running bool `json:"running"`
	// Health maps the "health" wire field.
	Health string `json:"health,omitempty"`
}

// HTTPProbeObservation is measured HTTP health probe.
type HTTPProbeObservation struct {
	// URL maps the "url" wire field.
	URL string `json:"url"`
	// Reached maps the "reached" wire field.
	Reached bool `json:"reached"`
	// StatusCode maps the "status_code" wire field.
	StatusCode int `json:"status_code,omitempty"`
	// FailureClass maps the "failure_class" wire field.
	FailureClass string `json:"failure_class,omitempty"`
}

// ServiceObservation is measured service health and evidence.
type ServiceObservation struct {
	// Name maps the "name" wire field.
	Name string `json:"name"`
	// Status maps the "status" wire field.
	Status ServiceHealthStatus `json:"status"`
	// PlatformAppID maps the "platform_app_id" wire field.
	PlatformAppID string `json:"platform_app_id,omitempty"`
	// PlatformStatus maps the "platform_status" wire field.
	PlatformStatus string `json:"platform_status,omitempty"`
	// Containers maps the "containers" wire field.
	Containers []ContainerObservation `json:"containers,omitempty"`
	// HealthPath maps the "health_path" wire field.
	HealthPath string `json:"health_path,omitempty"`
	// Probe maps the "probe" wire field.
	Probe *HTTPProbeObservation `json:"probe,omitempty"`
	// FailureClass maps the "failure_class" wire field.
	FailureClass string `json:"failure_class,omitempty"`
}

// LiveObservation is versioned persistable live-runtime evidence.
type LiveObservation struct {
	// Version maps the "version" wire field.
	Version string `json:"version"`
	// ObservedAt maps the "observed_at" wire field.
	ObservedAt time.Time `json:"observed_at"`
	// Host maps the "host" wire field.
	Host HostObservation `json:"host"`
	// Platform maps the "platform" wire field.
	Platform *PlatformObservation `json:"platform,omitempty"`
	// Services maps the "services" wire field.
	Services []ServiceObservation `json:"services,omitempty"`
	// FailureClass maps the "failure_class" wire field.
	FailureClass string `json:"failure_class,omitempty"`
}

// OwnerIdentity is configured owner identity.
type OwnerIdentity struct {
	// Username maps the "username" wire field.
	Username string `json:"username,omitempty"`
	// Email maps the "email" wire field.
	Email string `json:"email,omitempty"`
	// DisplayName maps the "display_name" wire field.
	DisplayName string `json:"display_name,omitempty"`
	// Subject maps the "subject" wire field.
	Subject string `json:"subject,omitempty"`
	// Provider maps the "provider" wire field.
	Provider string `json:"provider,omitempty"`
}

// RecoveryOutput is opaque recovery references; no secret material.
type RecoveryOutput struct {
	// BundleRef maps the "bundle_ref" wire field.
	BundleRef string `json:"bundle_ref,omitempty"`
	// SecretRef maps the "secret_ref" wire field.
	SecretRef string `json:"secret_ref,omitempty"`
	// MachineSecretRef maps the "machine_secret_ref" wire field.
	MachineSecretRef string `json:"machine_secret_ref,omitempty"`
	// PassphraseHashPresent maps the "passphrase_hash_present" wire field.
	PassphraseHashPresent bool `json:"passphrase_hash_present,omitempty"`
}

// IdentityOutputs is owner and recovery output projection.
type IdentityOutputs struct {
	// Owner maps the "owner" wire field.
	Owner *OwnerIdentity `json:"owner,omitempty"`
	// Recovery maps the "recovery" wire field.
	Recovery *RecoveryOutput `json:"recovery,omitempty"`
}

// LoginGatewayOutput is login gateway endpoints.
type LoginGatewayOutput struct {
	// URL maps the "url" wire field.
	URL string `json:"url,omitempty"`
	// Label maps the "label" wire field.
	Label string `json:"label,omitempty"`
	// AdminURL maps the "admin_url" wire field.
	AdminURL string `json:"admin_url,omitempty"`
}

// ServiceOutput is one exposed StackKit service.
type ServiceOutput struct {
	// Name maps the "name" wire field.
	Name string `json:"name,omitempty"`
	// URL maps the "url" wire field.
	URL string `json:"url,omitempty"`
	// AdminURL maps the "admin_url" wire field.
	AdminURL string `json:"admin_url,omitempty"`
	// Metadata maps the "metadata" wire field.
	Metadata map[string]string `json:"metadata,omitempty"`
}

// StackKitOutputs is structured StackKit rollout outputs.
type StackKitOutputs struct {
	// Identity maps the "identity" wire field.
	Identity *IdentityOutputs `json:"identity,omitempty"`
	// LoginGateway maps the "login_gateway" wire field.
	LoginGateway *LoginGatewayOutput `json:"login_gateway,omitempty"`
	// Recovery maps the "recovery" wire field.
	Recovery *RecoveryOutput `json:"recovery,omitempty"`
	// Services maps the "services" wire field.
	Services []ServiceOutput `json:"services,omitempty"`
	// Metadata maps the "metadata" wire field.
	Metadata map[string]string `json:"metadata,omitempty"`
}

// RuntimeMetrics is measured host utilization.
type RuntimeMetrics struct {
	// CPUPercent maps the "cpu_percent" wire field.
	CPUPercent float64 `json:"cpu_percent"`
	// MemoryPercent maps the "memory_percent" wire field.
	MemoryPercent float64 `json:"memory_percent"`
	// DiskPercent maps the "disk_percent" wire field.
	DiskPercent float64 `json:"disk_percent"`
	// UptimeSeconds maps the "uptime_seconds" wire field.
	UptimeSeconds float64 `json:"uptime_seconds"`
	// UpdatedAt maps the "updated_at" wire field.
	UpdatedAt string `json:"updated_at,omitempty"`
}

// DeploymentRef is selected-PaaS deployment reference.
type DeploymentRef struct {
	// Platform maps the "platform" wire field.
	Platform string `json:"platform"`
	// AppName maps the "appName" wire field.
	AppName string `json:"appName"`
	// ExternalID maps the "externalId" wire field.
	ExternalID string `json:"externalId"`
	// DeploymentID maps the "deploymentId" wire field.
	DeploymentID string `json:"deploymentId,omitempty"`
	// ObservedStatus maps the "observedStatus" wire field.
	ObservedStatus string `json:"observedStatus,omitempty"`
	// ObservedAt maps the "observedAt" wire field.
	ObservedAt time.Time `json:"observedAt,omitempty"`
	// LastDeployed maps the "lastDeployed" wire field.
	LastDeployed time.Time `json:"lastDeployed,omitempty"`
}

// SetupDrop is secret-free first-run setup evidence.
type SetupDrop struct {
	// Name maps the "name" wire field.
	Name string `json:"name"`
	// Version maps the "version" wire field.
	Version string `json:"version,omitempty"`
	// Runner maps the "runner" wire field.
	Runner string `json:"runner,omitempty"`
	// Description maps the "description" wire field.
	Description string `json:"description,omitempty"`
	// RollbackNotes maps the "rollbackNotes" wire field.
	RollbackNotes []string `json:"rollbackNotes,omitempty"`
}

// PlatformAppState is artifact-ready selected-PaaS application state.
type PlatformAppState struct {
	// Name maps the "name" wire field.
	Name string `json:"name"`
	// Role maps the "role" wire field.
	Role string `json:"role,omitempty"`
	// Platform maps the "platform" wire field.
	Platform string `json:"platform"`
	// Management maps the "management" wire field.
	Management string `json:"management,omitempty"`
	// ExternalID maps the "externalId" wire field.
	ExternalID string `json:"externalId"`
	// DeploymentID maps the "deploymentId" wire field.
	DeploymentID string `json:"deploymentId,omitempty"`
	// ObservedStatus maps the "observedStatus" wire field.
	ObservedStatus string `json:"observedStatus,omitempty"`
	// ObservedAt maps the "observedAt" wire field.
	ObservedAt time.Time `json:"observedAt,omitempty"`
	// ComposePath maps the "composePath" wire field.
	ComposePath string `json:"composePath,omitempty"`
	// SetupPolicy maps the "setupPolicy" wire field.
	SetupPolicy string `json:"setupPolicy,omitempty"`
	// SetupDrops maps the "setupDrops" wire field.
	SetupDrops []SetupDrop `json:"setupDrops,omitempty"`
	// LastDeployed maps the "lastDeployed" wire field.
	LastDeployed time.Time `json:"lastDeployed,omitempty"`
}

// Request is stackKits-owned action request.
type Request struct {
	// Action maps the "action" wire field.
	Action Action `json:"action"`
	// StackID maps the "stack_id" wire field.
	StackID string `json:"stack_id"`
	// StackName maps the "stack_name" wire field.
	StackName string `json:"stack_name,omitempty"`
	// StackKit maps the "stackkit" wire field.
	StackKit string `json:"stackkit,omitempty"`
	// Mode maps the "mode" wire field.
	Mode string `json:"mode,omitempty"`
	// TenantID maps the "tenant_id" wire field.
	TenantID string `json:"tenant_id,omitempty"`
	// OwnerID maps the "owner_id" wire field.
	OwnerID string `json:"owner_id,omitempty"`
	// TofuDir maps the "tofu_dir" wire field.
	TofuDir string `json:"tofu_dir,omitempty"`
	// UnifiedPath maps the "unified_path" wire field.
	UnifiedPath string `json:"unified_path,omitempty"`
	// OwnerSpecRef maps the "owner_spec_ref" wire field.
	OwnerSpecRef *ScopedReference `json:"owner_spec_ref,omitempty"`
	// RuntimeTarget maps the "runtime_target" wire field.
	RuntimeTarget *RuntimeTarget `json:"runtime_target,omitempty"`
	// PlatformNodes maps the "platform_nodes" wire field.
	PlatformNodes []PlatformNode `json:"platform_nodes,omitempty"`
	// TechStackEnrollment maps the "techstack_enrollment" wire field.
	TechStackEnrollment *TechStackEnrollment `json:"techstack_enrollment,omitempty"`
	// Backup maps the "backup" wire field.
	Backup *BackupRequest `json:"backup,omitempty"`
}

// Response is stackKits-owned action response and evidence.
type Response struct {
	// Status maps the "status" wire field.
	Status Status `json:"status"`
	// Action maps the "action" wire field.
	Action Action `json:"action"`
	// StackID maps the "stack_id" wire field.
	StackID string `json:"stack_id"`
	// StackName maps the "stack_name" wire field.
	StackName string `json:"stack_name,omitempty"`
	// StackKit maps the "stackkit" wire field.
	StackKit string `json:"stackkit,omitempty"`
	// TofuDir maps the "tofu_dir" wire field.
	TofuDir string `json:"tofu_dir,omitempty"`
	// UnifiedPath maps the "unified_path" wire field.
	UnifiedPath string `json:"unified_path,omitempty"`
	// Mode maps the "mode" wire field.
	Mode Mode `json:"mode"`
	// Checks maps the "checks" wire field.
	Checks []Check `json:"checks,omitempty"`
	// StackKitOutputs maps the "stackkit_outputs" wire field.
	StackKitOutputs *StackKitOutputs `json:"stackkit_outputs,omitempty"`
	// Observation maps the "observation" wire field.
	Observation *LiveObservation `json:"observation,omitempty"`
	// RuntimeMetrics maps the "runtime_metrics" wire field.
	RuntimeMetrics *RuntimeMetrics `json:"runtime_metrics,omitempty"`
	// PlatformRefs maps the "platform_refs" wire field.
	PlatformRefs []DeploymentRef `json:"platform_refs,omitempty"`
	// PlatformSystemApps maps the "platform_system_apps" wire field.
	PlatformSystemApps []PlatformAppState `json:"platform_system_apps,omitempty"`
	// PlatformApps maps the "platform_apps" wire field.
	PlatformApps []PlatformAppState `json:"platform_apps,omitempty"`
	// Backup maps the "backup" wire field.
	Backup *BackupResult `json:"backup,omitempty"`
}

// NormalizeAction canonicalizes a StackAction name.
func NormalizeAction(action string) Action {
	action = strings.ToLower(strings.TrimSpace(action))
	action = strings.ReplaceAll(action, "-", "_")
	return Action(action)
}

// IsStackKitsAction reports whether StackKits owns the action.
func IsStackKitsAction(action Action) bool {
	switch action {
	case ActionStackKitRollout, ActionVerifyRollout, ActionRestoreDrill, ActionBackupRun, ActionBackupStatus, ActionBackupRestore, ActionBackupWipe:
		return true
	default:
		return false
	}
}

// IsBackupAction reports whether the node-side backup engine owns the action.
func IsBackupAction(action Action) bool {
	switch action {
	case ActionBackupRun, ActionBackupStatus, ActionBackupRestore, ActionBackupWipe:
		return true
	default:
		return false
	}
}
