// Package hermes — Hermes Agent module (scaffolded, draft).
//
// Hermes Agent personal assistant on the node's local Ollama model with persistent memory and skills; StackKits pins the policy floor as managed scope, grants are owner toolsets; private dashboard behind the kit login.
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package hermes

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "hermes"
		displayName: "Hermes Agent"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Hermes Agent personal assistant on the node's local Ollama model with persistent memory and skills; StackKits pins the policy floor as managed scope, grants are owner toolsets; private dashboard behind the kit login."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "512m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: hermes: foundation.#ServiceDefinition & {
		name:     "hermes"
		type:     "application"
		image:    "docker.io/nousresearch/hermes-agent"
		tag:      "v2026.9.24@sha256:fca358f12efd65bfaaca05884166f15c0e2788375ca30d77061ac1ebc96452b7"
		required: false
		status:   "implemented"

		network: {
			traefik: {
				enabled: true
				rule:    "Host(`ai-assistant.{{.domain}}`)"
				port:    9119
			}
			networks: ["private-ai-internal"]
		}

		accessPolicy: {
			outerAuth: "tinyauth-pocketid"
			appAuth:   "self-auth"
			reason:    "The dashboard runs the owner's agent: the gateway login protects the private route and Hermes asks for its own owner password."
		}

		upstream: {
			github: repo: "NousResearch/hermes-agent"
			registry: image: "docker.io/nousresearch/hermes-agent"
			track: "minor"
		}

		healthCheck: {
			enabled: true
			http: {
				path:   "/api/status"
				port:   9119
				scheme: "http"
			}
			interval: "30s"
			timeout:  "10s"
			retries:  3
		}

		resources: {
			memory:    "512m"
			memoryMax: "3g"
		}

		security: {
			noNewPrivileges: true
			capDrop: ["ALL"]
		}

		output: description: "Hermes Agent dashboard"
	}
}
