// Code generated by architecture-v2 bundlegen from the compiled CUE authority; DO NOT EDIT.
// Authority bundle manifest sha256:4ee7d4dd71033936935aebc8937a8683ba1c46553234cbfd516dfe530408f001.

package productkits

var active = []string{
	"basement-kit",
	"cloud-kit",
	"modern-homelab",
}
