// Code generated by architecture-v2 bundlegen from the compiled CUE authority; DO NOT EDIT.
// Authority bundle manifest sha256:733845947f525492cb9a51df06cce7fe6398a59b387d640c038817f0d77a4675.

package productkits

var active = []string{
	"basement-kit",
	"cloud-kit",
	"modern-homelab",
}
