// Code generated by architecture-v2 bundlegen from the compiled CUE authority; DO NOT EDIT.
// Authority bundle manifest sha256:8e8376b212471d100cfa1ceee8518698856fcd8ea4dd3b144b157c2a4dbcefec.

package productkits

var active = []string{
	"basement-kit",
	"cloud-kit",
	"modern-homelab",
}
