#!/bin/sh
# Static website entrypoint for High Availability Kit.
# Usage: curl -sSL stackkit.cc/ha | sh
set -eu
STACKKIT_INSTALL_URL="${STACKKIT_INSTALL_URL:-https://stackkit.cc/install}"
HOMELAB_DIR="${HOMELAB_DIR:-$HOME/ha-homelab}"

printf '\033[1;34m==> %s\033[0m\n' "Installing stackkit CLI + High Availability Kit definitions"
curl -sSL "$STACKKIT_INSTALL_URL" | sh -s -- ha-kit

mkdir -p "$HOMELAB_DIR"
cd "$HOMELAB_DIR"

printf '\033[1;34m==> %s\033[0m\n' "Starting guided init with High Availability Kit preselected"
stackkit init ha-kit
