package kitio

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// ExportTerraform produces a `terraform.tfvars.json` from the kit
// definition's compute-tier requirements + selections + features.
//
// This is intentionally a thin "kit-level" tfvars surface:
//   - tier sizing -> tfvars (cpu, memory, disk per tier)
//   - selected modules per group -> tfvars enable_<module> bool
//   - features -> tfvars feature_<name> bool
//
// Per-module Terraform fragments are still generated by the existing
// internal/cue Generator at deploy-time from a StackSpec, not here.
// This export covers the kit-definition contract surface only — what a
// downstream installer needs to know about the kit's defaults.
func ExportTerraform(def KitDefinition, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, err)
	}

	tfvars := buildKitTfvars(def)
	tfvarsBytes, err := json.MarshalIndent(tfvars, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal tfvars: %w", err)
	}
	tfvarsPath := filepath.Join(outDir, "kit.tfvars.json")
	if err := os.WriteFile(tfvarsPath, tfvarsBytes, 0o644); err != nil {
		return fmt.Errorf("write tfvars: %w", err)
	}

	// A small README that documents the contract surface
	readme := fmt.Sprintf(`# kit.tfvars.json — Generated kit-level Terraform inputs

Generated by stackkit kit export for slug=%q version=%q.

This file is the kit-level contract surface — tier sizing, feature flags,
and selected default modules. Per-module Terraform fragments are NOT in
this file; they are generated by stackkit generate at deploy-time from a
StackSpec (stack-spec.yaml).

Re-generate after kit-import:

	stackkit kit export --slug %s --output <dir> --format tfvars

`, def.Metadata.Name, def.Metadata.Version, def.Metadata.Name)
	if err := os.WriteFile(filepath.Join(outDir, "README.md"), []byte(readme), 0o644); err != nil {
		return fmt.Errorf("write readme: %w", err)
	}

	return nil
}

// buildKitTfvars assembles the kit-level tfvars structure.
func buildKitTfvars(def KitDefinition) map[string]interface{} {
	tfvars := map[string]interface{}{
		"kit_name":    def.Metadata.Name,
		"kit_version": def.Metadata.Version,
	}

	// Compute tier sizing
	tiers := map[string]interface{}{}
	for slug, t := range def.ComputeTiers {
		tiers[slug] = map[string]interface{}{
			"cpu":    t.Requirements.CPU,
			"memory": t.Requirements.Memory,
			"disk":   t.Requirements.Disk,
		}
	}
	tfvars["compute_tiers"] = tiers

	// Selected default modules per group
	modules := map[string]string{}
	for k, uc := range def.Application {
		if uc.DefaultTool != "" && (uc.Role == "default" || uc.Role == "required") {
			modules["application_"+normalizeKey(k)] = uc.DefaultTool
		}
	}
	for k, p := range def.Platform.AsMap {
		if p.DefaultTool != "" {
			modules["platform_"+normalizeKey(k)] = p.DefaultTool
		}
	}
	tfvars["default_modules"] = modules

	// Features
	tfvars["features"] = def.Features

	return tfvars
}

func normalizeKey(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out = append(out, r)
		case r == '-':
			out = append(out, '_')
		}
	}
	return string(out)
}
