package kitio

import (
	"bytes"
	"fmt"
	"sort"
	"text/template"
)

// ExportCUE renders a kit definition into CUE form.
//
// Two outputs:
//   - stackfileBytes: package <slug> with #StackKitConfig including
//     metadata + supportedOS + modes + features.
//   - servicesBytes:  package <slug> with the per-service-group selections
//     and per-tier sizing as commented-out placeholder records (the actual
//     module CUE definitions live in modules/*/module.cue and are not
//     duplicated here).
//
// This is a *valid CUE* representation of the DB-shape — it is NOT meant
// to byte-equal the hand-written base-kit/stackfile.cue, which carries
// hand-curated comments + schema constraints. The roundtrip test
// validates `cue eval` succeeds, not byte-equality.
func ExportCUE(def KitDefinition) (stackfileBytes, servicesBytes []byte, err error) {
	stackfileBytes, err = renderStackfileCUE(def)
	if err != nil {
		return nil, nil, fmt.Errorf("stackfile.cue: %w", err)
	}
	servicesBytes, err = renderServicesCUE(def)
	if err != nil {
		return nil, nil, fmt.Errorf("services.cue: %w", err)
	}
	return stackfileBytes, servicesBytes, nil
}

const stackfileTmpl = `// Generated by kitio.ExportCUE — DO NOT EDIT.
// Source-of-truth: DB row sk_stackkit slug={{.Slug}}
//                  + sk_stackkit_mode + sk_stackkit_compute_tier + sk_stackkit_service_selection
// To regenerate: stackkit kit export --slug {{.Slug}} --output ./generated/{{.Slug}}/

package {{.PackageName}}

#KitMetadata: {
	name:        "{{.Metadata.Name}}"
	version:     "{{.Metadata.Version}}"
	{{if .Metadata.License}}license:     "{{.Metadata.License}}"{{end}}
	{{if .Metadata.Author}}author:      "{{.Metadata.Author}}"{{end}}
	{{if .Metadata.Description}}description: """
		{{.Metadata.Description}}
		"""{{end}}
}

#SupportedOS: [{{range $i, $os := .SupportedOS}}{{if $i}}, {{end}}"{{$os}}"{{end}}]

#Features: {
{{range $k, $v := .Features}}	{{$k}}: {{if $v}}true{{else}}false{{end}}
{{end}}}

#Modes: {
{{range $slug, $mode := .Modes}}	{{$slug}}: {
		description: "{{$mode.Description}}"
		{{if $mode.TemplateDir}}templateDir: "{{$mode.TemplateDir}}"{{end}}
		{{if $mode.Engine}}engine:      "{{$mode.Engine}}"{{end}}
	}
{{end}}}

#ComputeTiers: {
{{range $slug, $tier := .ComputeTiers}}	{{$slug}}: {
		requirements: {
			{{if $tier.Requirements.CPU}}cpu:    {{$tier.Requirements.CPU}}{{end}}
			{{if $tier.Requirements.Memory}}memory: {{$tier.Requirements.Memory}}{{end}}
			{{if $tier.Requirements.Disk}}disk:   {{$tier.Requirements.Disk}}{{end}}
		}
		{{if $tier.AdditionalServices}}additionalServices: [{{range $i, $s := $tier.AdditionalServices}}{{if $i}}, {{end}}"{{$s}}"{{end}}]{{end}}
		{{if $tier.PaasOverride}}paasOverride: "{{$tier.PaasOverride}}"{{end}}
	}
{{end}}}
`

const servicesTmpl = `// Generated by kitio.ExportCUE — DO NOT EDIT.
// Per-service-group selections for kit slug={{.Slug}}.
// Each block records the kit's role + selected module + alternatives.
// Concrete module CUE definitions live in modules/<slug>/module.cue and
// are NOT duplicated here.

package {{.PackageName}}

#Foundation: {
{{range $key, $found := .Foundation}}	"{{$key}}": {
		role: "{{$found.Role}}"
		{{if $found.Alternatives}}alternatives: [{{range $i, $a := $found.Alternatives}}{{if $i}}, {{end}}"{{$a}}"{{end}}]{{end}}
	}
{{end}}}

#Platform: {
{{if .PlatformIsString}}	type: "{{.Platform.AsString}}"
{{else}}{{range $key, $plat := .Platform.AsMap}}	"{{$key}}": {
		role: "{{$plat.Role}}"
		{{if $plat.DefaultTool}}defaultTool: "{{$plat.DefaultTool}}"{{end}}
		{{if $plat.Alternatives}}alternatives: [{{range $i, $a := $plat.Alternatives}}{{if $i}}, {{end}}"{{$a}}"{{end}}]{{end}}
	}
{{end}}{{end}}}

#Application: {
{{range $key, $uc := .Application}}	"{{$key}}": {
		role: "{{$uc.Role}}"
		{{if $uc.DefaultTool}}defaultTool: "{{$uc.DefaultTool}}"{{end}}
		{{if $uc.Alternatives}}alternatives: [{{range $i, $a := $uc.Alternatives}}{{if $i}}, {{end}}"{{$a}}"{{end}}]{{end}}
	}
{{end}}}
`

type cueRenderCtx struct {
	Slug             string
	PackageName      string
	Metadata         KitMetadata
	SupportedOS      []string
	Features         map[string]bool
	Modes            map[string]ModeDef
	ComputeTiers     map[string]ComputeTierDef
	Foundation       map[string]FoundationDef
	Platform         PlatformField
	PlatformIsString bool
	Application      map[string]ApplicationDef
}

func renderStackfileCUE(def KitDefinition) ([]byte, error) {
	ctx := newCueCtx(def)
	return renderTemplate("stackfile", stackfileTmpl, ctx)
}

func renderServicesCUE(def KitDefinition) ([]byte, error) {
	ctx := newCueCtx(def)
	return renderTemplate("services", servicesTmpl, ctx)
}

func newCueCtx(def KitDefinition) cueRenderCtx {
	pkg := normalizeCUEPackageName(def.Metadata.Name)
	return cueRenderCtx{
		Slug:             def.Metadata.Name,
		PackageName:      pkg,
		Metadata:         def.Metadata,
		SupportedOS:      def.SupportedOS,
		Features:         def.Features,
		Modes:            def.Modes,
		ComputeTiers:     def.ComputeTiers,
		Foundation:       def.Foundation,
		Platform:         def.Platform,
		PlatformIsString: def.Platform.AsString != "",
		Application:      def.Application,
	}
}

func normalizeCUEPackageName(slug string) string {
	out := make([]rune, 0, len(slug))
	for _, r := range slug {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out = append(out, r)
		case r == '-' || r == '_':
			out = append(out, '_')
		}
	}
	if len(out) == 0 {
		return "kit"
	}
	return string(out)
}

func renderTemplate(name, tmpl string, data interface{}) ([]byte, error) {
	t, err := template.New(name).Parse(tmpl)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}
	return buf.Bytes(), nil
}

// SortedModeKeys returns mode keys in stable order.
func SortedModeKeys(m map[string]ModeDef) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
