package kitio

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// ExportCompose produces a Docker-Compose-style overview file at the kit
// level — NOT per-module compose fragments (those are generated by
// stackkit generate at deploy-time from the StackSpec + selected modules).
//
// What this writes is a `kit-overview.compose.yml` that records the kit's
// service-group selections in compose-comment form, useful for operators
// who want to read what a kit "is" without running stackkit generate.
func ExportCompose(def KitDefinition, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, err)
	}

	overview := buildComposeOverview(def)
	bytes, err := yaml.Marshal(overview)
	if err != nil {
		return fmt.Errorf("marshal compose overview: %w", err)
	}

	header := fmt.Sprintf(`# kit-overview.compose.yml — Generated by stackkit kit export
# Kit: %s @ %s
#
# This is NOT a deployable docker-compose file. It records the service-group
# selections of the kit in compose-yaml form so operators can see the kit
# composition at a glance. The actual deployable compose is produced by
# stackkit generate at deploy-time from a StackSpec.

`, def.Metadata.Name, def.Metadata.Version)
	combined := append([]byte(header), bytes...)
	overviewPath := filepath.Join(outDir, "kit-overview.compose.yml")
	if err := os.WriteFile(overviewPath, combined, 0o644); err != nil {
		return fmt.Errorf("write compose overview: %w", err)
	}
	return nil
}

func buildComposeOverview(def KitDefinition) map[string]interface{} {
	services := map[string]interface{}{}

	// Foundation
	for k, found := range def.Foundation {
		services["foundation-"+k] = map[string]interface{}{
			"image": "kombify/" + k + ":foundation",
			"labels": map[string]string{
				"stackkit.layer": "foundation",
				"stackkit.role":  string(found.Role),
				"stackkit.kit":   def.Metadata.Name,
			},
		}
	}
	// Platform map form
	for k, plat := range def.Platform.AsMap {
		image := plat.DefaultTool
		if image == "" {
			image = k
		}
		services["platform-"+k] = map[string]interface{}{
			"image": "kombify/" + image + ":platform",
			"labels": map[string]string{
				"stackkit.layer": "platform",
				"stackkit.role":  string(plat.Role),
				"stackkit.kit":   def.Metadata.Name,
			},
		}
	}
	// Application (L3)
	for k, uc := range def.Application {
		image := uc.DefaultTool
		if image == "" {
			image = k
		}
		services["app-"+k] = map[string]interface{}{
			"image": "kombify/" + image + ":app",
			"labels": map[string]string{
				"stackkit.layer":   "application",
				"stackkit.role":    string(uc.Role),
				"stackkit.usecase": k,
				"stackkit.kit":     def.Metadata.Name,
			},
		}
	}

	return map[string]interface{}{
		"version":  "3.8",
		"x-kit":    def.Metadata.Name,
		"services": services,
	}
}
