// Package calagopus — Calagopus Panel module (scaffolded, draft).
//
// Calagopus Panel and Wings upstream catalog, the recommended Game platform. The native-v2 game workload owns executable configuration, owner bootstrap and the governed Wings lifecycle-owner approval (ADR-0043, ADR-0048).
//
// Generated by `stackkit module scaffold` from module_facts.json (ADR-0027).
// Deterministic output: edit the facts and re-scaffold; do not hand-diff.
package calagopus

import "github.com/kombifyio/stackkits/foundation"

Contract: foundation.#ModuleContract & {
	metadata: {
		name:        "calagopus"
		displayName: "Calagopus Panel"
		version:     "0.1.0"
		layer:       "L3-application"
		description: "Calagopus Panel and Wings upstream catalog, the recommended Game platform. The native-v2 game workload owns executable configuration, owner bootstrap and the governed Wings lifecycle-owner approval (ADR-0043, ADR-0048)."
		core:        false
		maturity:    "draft"
	}

	requires: infrastructure: {
		docker:            true
		dockerSocket:      false
		persistentStorage: true
		minMemory:         "768m"
	}

	placementSupport: {
		local_only:         true
		standard:           true
		managed_serverless: false
	}

	services: {
		panel: foundation.#ServiceDefinition & {
			name:     "panel"
			type:     "application"
			image:    "ghcr.io/calagopus/panel"
			tag:      "1.2.4@sha256:95ee4a9ea6b3c1567179610ca8f5637f7e8d7f6bc4f97a4207afba6b9cd21d1a"
			required: false
			status:   "implemented"

			network: {
				traefik: {
					enabled: true
					rule:    "Host(`game.{{.domain}}`)"
					port:    8000
				}
				networks: ["game-internal"]
			}

			accessPolicy: {
				outerAuth: "self"
				appAuth:   "self-auth"
			}

			upstream: {
				github: repo: "calagopus/panel"
				registry: image: "ghcr.io/calagopus/panel"
				track: "minor"
			}

			volumes: [
				{
					source: "panel-data"
					target: "/var/lib/calagopus"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/"
					port:   8000
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Calagopus Panel dashboard"
		}
		"panel-database": foundation.#ServiceDefinition & {
			name:     "panel-database"
			type:     "database"
			image:    "docker.io/library/postgres"
			tag:      "18-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873"
			required: false
			status:   "implemented"

			network: networks: ["game-internal"]

			upstream: {
				github: repo: "docker-library/postgres"
				registry: image: "docker.io/library/postgres"
				track: "minor"
			}

			volumes: [
				{
					source: "panel-database-data"
					target: "/var/lib/postgresql"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled:  true
				command:  "pg_isready -U panel -d panel"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Calagopus Panel database (internal)"
		}
		"panel-cache": foundation.#ServiceDefinition & {
			name:     "panel-cache"
			type:     "cache"
			image:    "docker.io/valkey/valkey"
			tag:      "9-alpine@sha256:a0dbf4c1d5708782907c10e2c72deff317518518b5288a58416981d9db95d30b"
			required: false
			status:   "implemented"

			network: networks: ["game-internal"]

			upstream: {
				github: repo: "valkey-io/valkey"
				registry: image: "docker.io/valkey/valkey"
				track: "minor"
			}

			volumes: [
				{
					source: "panel-cache-data"
					target: "/data"
					type:   "volume"
					backup: false
				},
			]

			healthCheck: {
				enabled:  true
				command:  "valkey-cli ping"
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "64m"
				memoryMax: "256m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Calagopus Panel cache (internal)"
		}
		wings: foundation.#ServiceDefinition & {
			name:     "wings"
			type:     "application"
			image:    "ghcr.io/calagopus/wings"
			tag:      "1.2.4@sha256:61417524f2701e0fa614c0816f219268c7ae1043d4d45b07bbbbacbe781c2e5a"
			required: false
			status:   "implemented"

			network: networks: ["game-internal"]

			upstream: {
				github: repo: "calagopus/wings"
				registry: image: "ghcr.io/calagopus/wings"
				track: "minor"
			}

			volumes: [
				{
					source: "wings-data"
					target: "/stackkit/game-data"
					type:   "volume"
					backup: true
				},
			]

			healthCheck: {
				enabled: true
				http: {
					path:   "/api/system"
					port:   8080
					scheme: "http"
				}
				interval: "30s"
				timeout:  "10s"
				retries:  3
			}

			resources: {
				memory:    "128m"
				memoryMax: "512m"
			}

			security: {
				noNewPrivileges: true
				capDrop: ["ALL"]
			}

			output: description: "Calagopus Panel application (internal)"
		}
	}
}
